-- VHDL Entity JWXJ.ASS_LINE_C260207.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 17:33:22 2026/02/ 9
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ASS_LINE_C260207 IS
   GENERIC( 
      REG_NUM_M1 : std_logic_vector(1 downto 0) := "00"
   );
   PORT( 
      Clk            : IN     std_logic;
      FOP            : IN     std_logic;
      REG_CAP_MODE   : IN     std_logic_vector (7 DOWNTO 0);
      REG_EXPOTIME   : IN     std_logic_vector (15 DOWNTO 0);
      REG_FRAME_FREQ : IN     std_logic_vector (7 DOWNTO 0);
      REG_GAIN_MODE  : IN     std_logic;
      REG_GAIN_VAL   : IN     std_logic_vector (7 DOWNTO 0);
      REG_KC_X       : IN     std_logic_vector (15 DOWNTO 0);
      REG_KC_Y       : IN     std_logic_vector (15 DOWNTO 0);
      Reset          : IN     std_logic;
      S_TDATA        : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST        : IN     std_logic;
      S_TUSER        : IN     std_logic_vector (1 DOWNTO 0);
      S_TVALID       : IN     std_logic;
      M_TDATA        : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST        : OUT    std_logic;
      M_TUSER        : OUT    std_logic_vector (1 DOWNTO 0);
      M_TVALID       : OUT    std_logic
   );

-- Declarations

END ASS_LINE_C260207 ;

--
-- VHDL Architecture JWXJ.ASS_LINE_C260207.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 17:33:22 2026/02/ 9
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--d
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;


ARCHITECTURE struct OF ASS_LINE_C260207 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_FOP,
      ST_DATA,
      ST_EOP,
      ST_CNT,
      ST_WAIT,
      ST_SOP,
      ST_DATA_B,
      ST_GAIN_MODE,
      ST_FRAME_FREQ,
      ST_EXP,
      ST_GAIN_VAL,
      ST_KC_X,
      ST_KC_Y
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(9 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(9 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_DATA : std_logic;
   SIGNAL csm1_to_ST_WAIT : std_logic;
   SIGNAL csm1_to_ST_DATA_B : std_logic;


   -- Internal signal declarations
   SIGNAL Add_Cnt : std_logic;
   SIGNAL Cnt     : std_logic_vector(1 DOWNTO 0);
   SIGNAL End_Cnt : std_logic;



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      End_Cnt,
      FOP,
      State_c,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_DATA <= '0';
      csm1_to_ST_WAIT <= '0';
      csm1_to_ST_DATA_B <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (FOP='1') THEN 
               State_n <= ST_FOP;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_FOP => 
            State_n <= ST_EXP;
         WHEN ST_DATA => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_EOP;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_EOP => 
            State_n <= ST_CNT;
         WHEN ST_CNT => 
            IF (End_Cnt='1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_WAIT;
               csm1_to_ST_WAIT <= '1';
            END IF;
         WHEN ST_WAIT => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_SOP;
            ELSE
               State_n <= ST_WAIT;
            END IF;
         WHEN ST_SOP => 
            State_n <= ST_DATA_B;
            csm1_to_ST_DATA_B <= '1';
         WHEN ST_DATA_B => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_EOP;
            ELSE
               State_n <= ST_DATA_B;
            END IF;
         WHEN ST_GAIN_MODE => 
            State_n <= ST_GAIN_VAL;
         WHEN ST_FRAME_FREQ => 
            State_n <= ST_KC_X;
         WHEN ST_EXP => 
            State_n <= ST_GAIN_MODE;
         WHEN ST_GAIN_VAL => 
            State_n <= ST_FRAME_FREQ;
         WHEN ST_KC_X => 
            State_n <= ST_KC_Y;
         WHEN ST_KC_Y => 
            State_n <= ST_DATA;
            csm1_to_ST_DATA <= '1';
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_DATA,
      csm1_to_ST_WAIT,
      csm1_to_ST_DATA_B
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_DATA = '1') THEN
         csm1_next_timer <= "1010001011"; -- no cycles(652)-1=651
      ELSIF (csm1_to_ST_WAIT = '1') THEN
         csm1_next_timer <= "0001100011"; -- no cycles(100)-1=99
      ELSIF (csm1_to_ST_DATA_B = '1') THEN
         csm1_next_timer <= "1010010001"; -- no cycles(658)-1=657
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Cnt <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(Add_Cnt = '1') then
   			if(End_Cnt = '1') then
   				Cnt <= (others => '0');
   			else
   				Cnt <= Cnt + "01";
   			end if;
   		end if;
   	end if;
   end process;
   
   Add_Cnt <= '1' when (State_c = ST_CNT) else '0';
   End_Cnt <= '1' when (Add_Cnt = '1') and (Cnt = REG_NUM_M1) else '0';
   

   -- HDL Embedded Text Block 3 eb3
   -- eb3 3                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_TUSER <= "00";
   	elsif rising_edge(Clk) then
   		if(State_c = ST_FOP) then
   			M_TUSER <= "11";
   		elsif(State_c = ST_SOP) then
   			M_TUSER <= "01";
   		else
   			M_TUSER <= '0' & S_TUSER(0);
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_TVALID <= '0';
   		M_TDATA  <= X"0000";
   	elsif rising_edge(Clk) then
   		case(State_c) is 
   			when ST_FOP =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"00" & REG_CAP_MODE;
   			when ST_EXP =>
   				M_TVALID <= '1';
   				M_TDATA  <= REG_EXPOTIME;
   			when ST_GAIN_MODE=>
   				M_TVALID <= '1';
   				if(REG_GAIN_MODE = '1') then
   					M_TDATA <= X"0011";
   				else 
   					M_TDATA  <= X"0022";
   				end if;
   			when ST_GAIN_VAL =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"00" & REG_GAIN_VAL;
   			when ST_FRAME_FREQ =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"00" & REG_FRAME_FREQ;
   			when ST_KC_X =>
   				M_TVALID <= '1';
   				M_TDATA  <= REG_KC_X;
   			when ST_KC_Y =>
   				M_TVALID <= '1';
   				M_TDATA  <= REG_KC_Y;
   			when ST_SOP =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"0000";
   			when ST_DATA =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"0000";
   			when ST_DATA_B =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"0000";
   			when ST_EOP =>
   				M_TVALID <= '1';
   				M_TDATA  <= X"0000";
   			when others =>
   				M_TVALID <= S_TVALID;
   				M_TDATA  <= S_TDATA;
   		end case;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_TLAST <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_EOP) then
   			M_TLAST <= '1';
   		else
   			M_TLAST <= S_TLAST;
   		end if;
   	end if;
   end process;
   
   
   


   -- Instance port mappings.

END struct;
