-- VHDL Entity JWXJ.AXI2UART_BUG250302.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 11:15:00 2025/09/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY AXI2UART_BUG250302 IS
   GENERIC( 
      SYNC_HEAD : std_logic_vector(15 downto 0) := X"EB90"
   );
   PORT( 
      Clk            : IN     std_logic;
      REG_HEAD_TYPE  : IN     std_logic;
      REG_TIME       : IN     std_logic_vector (63 DOWNTO 0);
      Reset          : IN     std_logic;
      TDATA          : IN     std_logic_vector (7 DOWNTO 0);
      TLAST          : IN     std_logic;
      TUSER          : IN     std_logic_vector (7 DOWNTO 0);
      TVALID         : IN     std_logic;
      UART_Clk       : IN     std_logic;
      UART_ClkEn     : IN     std_logic;
      UART_Reset_n   : IN     std_logic;
      DEBUG_TX_Data  : OUT    std_logic_vector (7 DOWNTO 0);
      DEBUG_TX_Valid : OUT    std_logic;
      TX_EN          : OUT    std_logic;
      TX_PAD_O       : OUT    std_logic
   );

-- Declarations

END AXI2UART_BUG250302 ;

--
-- VHDL Architecture JWXJ.AXI2UART_BUG250302.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 11:15:00 2025/09/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY JWXJ;
LIBRARY xpm;

ARCHITECTURE struct OF AXI2UART_BUG250302 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_AXIS_DATA,
      ST_HEAD1,
      ST_HEAD2,
      ST_HEAD3,
      ST_ACK_RSP,
      ST_ENG_CNT_L,
      ST_DATA,
      ST_CRC_H,
      ST_TIME1,
      ST_TIME2,
      ST_TIME3,
      ST_TIME4,
      ST_TIME5,
      ST_TIME6,
      ST_TIME7,
      ST_TIME8,
      ST_ENG_HEAD,
      ST_TIMEOUT,
      ST_CHECK,
      ST_WAITBEFORE,
      s0,
      ST_RXEN,
      s1,
      ST_HEAD_CHECK,
      ST_EHEAD1,
      ST_EHEAD2
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(23 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(23 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_WAITBEFORE : std_logic;
   SIGNAL csm1_to_s0 : std_logic;
   SIGNAL csm1_to_s1 : std_logic;


   -- Internal signal declarations
   SIGNAL CRC_Calc         : std_logic_vector(7 DOWNTO 0);
   SIGNAL CRC_H_En         : std_logic;
   SIGNAL CrcEn            : std_logic;
   SIGNAL FIFO_AlmostEmpty : STD_LOGIC;
   SIGNAL FIFO_Din         : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL FIFO_Dout        : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL FIFO_RdEn        : STD_LOGIC;
   SIGNAL FIFO_WrEn        : STD_LOGIC;
   SIGNAL REG_ENG_CNT      : std_logic_vector(13 DOWNTO 0);
   SIGNAL REG_TUSER        : std_logic_vector(7 DOWNTO 0);
   SIGNAL Reset_n          : std_logic;
   SIGNAL TDATA_r          : std_logic_vector(7 DOWNTO 0);
   SIGNAL TDATA_r2         : std_logic_vector(7 DOWNTO 0);
   SIGNAL TLAST_r          : std_logic;
   SIGNAL TLAST_r2         : std_logic;
   SIGNAL TUSER_r          : std_logic_vector(7 DOWNTO 0);
   SIGNAL TUSER_r2         : std_logic_vector(7 DOWNTO 0);
   SIGNAL TVALID_r         : std_logic;
   SIGNAL TVALID_r2        : std_logic;
   SIGNAL TVALID_r3        : std_logic;
   SIGNAL TX_DIS           : std_logic;
   SIGNAL TX_DIS_s2        : std_logic;
   SIGNAL TX_Data          : std_logic_vector(8 DOWNTO 0);
   SIGNAL TX_Data_r        : std_logic_vector(8 DOWNTO 0);
   SIGNAL TX_EN_b          : std_logic;
   SIGNAL TX_Valid         : std_logic;
   SIGNAL TX_Valid_r       : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_8' of 'adff'
   SIGNAL mw_U_8reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_9' of 'adff'
   SIGNAL mw_U_9reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_10' of 'adff'
   SIGNAL mw_U_10reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_11' of 'adff'
   SIGNAL mw_U_11reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_12' of 'adff'
   SIGNAL mw_U_12reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_13' of 'adff'
   SIGNAL mw_U_13reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_14' of 'adff'
   SIGNAL mw_U_14reg_cval : std_logic;

attribute fsm_safe_state : string;
attribute fsm_safe_state of State_c : signal is "default_state";

   -- Component Declarations
   COMPONENT UART_FIFO_S2_SX
   PORT (
      clk          : IN     STD_LOGIC;
      din          : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      rd_en        : IN     STD_LOGIC;
      srst         : IN     STD_LOGIC;
      wr_en        : IN     STD_LOGIC;
      almost_empty : OUT    STD_LOGIC;
      dout         : OUT    STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      empty        : OUT    STD_LOGIC;
      full         : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT UART_TX_DRIVER_PT_C250303
   GENERIC (
      VARPARITY : std_logic := '1'
   );
   PORT (
      DATA          : IN     std_logic_vector (8 DOWNTO 0);
      SYS_Clk       : IN     std_logic;
      SYS_Reset_n   : IN     std_logic;
      UART_Clk      : IN     std_logic;
      UART_ClkEn    : IN     std_logic;
      UART_Reset_n  : IN     std_logic;
      VALID         : IN     std_logic;
      TX_DIS        : OUT    std_logic;
      TX_PAD_O      : OUT    std_logic;
      UART_TF_Empty : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT xpm_cdc_single
   GENERIC (
      DEST_SYNC_FF   : integer := 4;
      INIT_SYNC_FF   : integer := 0;
      SIM_ASSERT_CHK : integer := 0;
      SRC_INPUT_REG  : integer := 1;
      VERSION        : integer := 0
   );
   PORT (
      dest_clk : IN     std_logic;
      src_clk  : IN     std_logic;
      src_in   : IN     std_logic;
      dest_out : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   --FOR ALL : UART_FIFO_S2_SX USE ENTITY JWXJ.UART_FIFO_S2_SX;
   FOR ALL : UART_TX_DRIVER_PT_C250303 USE ENTITY JWXJ.UART_TX_DRIVER_PT_C250303;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      FIFO_AlmostEmpty,
      REG_HEAD_TYPE,
      REG_TUSER,
      State_c,
      TLAST_r2,
      TVALID_r,
      TX_DIS_s2,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_WAITBEFORE <= '0';
      csm1_to_s0 <= '0';
      csm1_to_s1 <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (TVALID_r='1') THEN 
               State_n <= ST_AXIS_DATA;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_AXIS_DATA => 
            IF ((TLAST_r2='1')) THEN 
               State_n <= ST_WAITBEFORE;
               csm1_to_ST_WAITBEFORE <= '1';
            ELSE
               State_n <= ST_AXIS_DATA;
            END IF;
         WHEN ST_HEAD1 => 
            State_n <= ST_HEAD2;
         WHEN ST_HEAD2 => 
            State_n <= ST_HEAD3;
         WHEN ST_HEAD3 => 
            State_n <= ST_TIMEOUT;
         WHEN ST_ACK_RSP => 
            State_n <= s1;
            csm1_to_s1 <= '1';
         WHEN ST_ENG_CNT_L => 
            State_n <= ST_TIME1;
         WHEN ST_DATA => 
            IF (FIFO_AlmostEmpty='1') THEN 
               State_n <= ST_CRC_H;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_CRC_H => 
            State_n <= s0;
            csm1_to_s0 <= '1';
         WHEN ST_TIME1 => 
            State_n <= ST_TIME2;
         WHEN ST_TIME2 => 
            State_n <= ST_TIME3;
         WHEN ST_TIME3 => 
            State_n <= ST_TIME4;
         WHEN ST_TIME4 => 
            State_n <= ST_TIME5;
         WHEN ST_TIME5 => 
            State_n <= ST_TIME6;
         WHEN ST_TIME6 => 
            State_n <= ST_TIME7;
         WHEN ST_TIME7 => 
            State_n <= ST_TIME8;
         WHEN ST_TIME8 => 
            State_n <= ST_DATA;
         WHEN ST_ENG_HEAD => 
            State_n <= ST_ENG_CNT_L;
         WHEN ST_TIMEOUT => 
            State_n <= ST_CHECK;
         WHEN ST_CHECK => 
            State_n <= ST_ACK_RSP;
         WHEN ST_WAITBEFORE => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_HEAD_CHECK;
            ELSE
               State_n <= ST_WAITBEFORE;
            END IF;
         WHEN s0 => 
            IF (TX_DIS_s2='1') THEN 
               State_n <= ST_RXEN;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_RXEN;
            ELSE
               State_n <= s0;
            END IF;
         WHEN ST_RXEN => 
            State_n <= ST_IDLE;
         WHEN s1 => 
            IF (TX_DIS_s2='1') THEN 
               State_n <= ST_RXEN;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_RXEN;
            ELSE
               State_n <= s1;
            END IF;
         WHEN ST_HEAD_CHECK => 
            IF ((REG_TUSER=X"00")and(REG_HEAD_TYPE='1')) THEN 
               State_n <= ST_EHEAD1;
            ELSE
               State_n <= ST_HEAD1;
            END IF;
         WHEN ST_EHEAD1 => 
            State_n <= ST_EHEAD2;
         WHEN ST_EHEAD2 => 
            State_n <= ST_ENG_HEAD;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_WAITBEFORE,
      csm1_to_s0,
      csm1_to_s1
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_WAITBEFORE = '1') THEN
         csm1_next_timer <= "000000000000001111100111"; -- no cycles(1000)-1=999
      ELSIF (csm1_to_s0 = '1') THEN
         csm1_next_timer <= "100110001001011001111111"; -- no cycles(10000000)-1=9999999
      ELSIF (csm1_to_s1 = '1') THEN
         csm1_next_timer <= "100110001001011001111111"; -- no cycles(10000000)-1=9999999
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		FIFO_WrEn <= '0';
   		FIFO_Din  <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_AXIS_DATA) and (TUSER_r2 = X"00") and (TVALID_r2 = '1') then
   			FIFO_WrEn <= '1';
   			FIFO_Din  <= TDATA_r2;
   		else
   			FIFO_WrEn <= '0';
   			FIFO_Din  <= (others => '0');
   		end if;
   	end if;
   end process;
   
   FIFO_RdEn <= '1' when (State_c = ST_DATA) else '0';
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		TX_Data <= (others => '0');
   		TX_Valid <= '0';
   	elsif rising_edge(Clk) then
   		case State_c is
   			when ST_DATA =>
   				TX_Data <= '0'& FIFO_Dout;
   				TX_Valid <= '1';
   			when ST_HEAD1 =>
   				TX_Data <= '0'& X"7E";
   				TX_Valid <= '1';
   			when ST_HEAD2 =>
   				TX_Data <= '0'& X"E7";
   				TX_Valid <= '1';
   			when ST_EHEAD1 =>
   				TX_Data <= '0'& X"E7";
   				TX_Valid <= '1';
   			when ST_EHEAD2 =>
   				TX_Data <= '0'& X"7E";
   				TX_Valid <= '1';
   			when ST_HEAD3 =>
   				TX_Data <= '0'& X"66";
   				TX_Valid <= '1';
   			when ST_TIMEOUT =>
   				if(REG_TUSER=X"10") then
   					TX_Data <= '0'& X"AA";
   				else
   					TX_Data <= '0'& X"00";
   				end if;
   			when ST_CHECK =>
   				if(REG_TUSER=X"01") then
   					TX_Data <= '0'& X"AA";
   				else
   					TX_Data <= '0'& X"00";
   				end if;
   			when ST_ACK_RSP =>
   				TX_Data <= '1'& X"F0";
   				TX_Valid <= '1';
   			when ST_ENG_HEAD  =>
   				TX_Data <= '0'& X"88";
   				TX_Valid <= '1';
   			when ST_ENG_CNT_L =>
   				TX_Data <= '0'& REG_ENG_CNT(7 downto 0);
   				TX_Valid <= '1';
   			when ST_TIME1 =>
   				TX_Data <= '0'& REG_TIME(63 downto 56);
   				TX_Valid <= '1';
   			when ST_TIME2 =>
   				TX_Data <= '0'& REG_TIME(55 downto 48);
   				TX_Valid <= '1';
   			when ST_TIME3 =>
   				TX_Data <= '0'& REG_TIME(47 downto 40);
   				TX_Valid <= '1';
   			when ST_TIME4 =>
   				TX_Data <= '0'& REG_TIME(39 downto 32);
   				TX_Valid <= '1';
   			when ST_TIME5 =>
   				TX_Data <= '0'& REG_TIME(31 downto 24);
   				TX_Valid <= '1';
   			when ST_TIME6 =>
   				TX_Data <= '0'& REG_TIME(23 downto 16);
   				TX_Valid <= '1';
   			when ST_TIME7 =>
   				TX_Data <= '0'& REG_TIME(15 downto 8);
   				TX_Valid <= '1';
   			when ST_TIME8 =>
   				TX_Data <= '0'& REG_TIME(7 downto 0);
   				TX_Valid <= '1';
   			when ST_CRC_H =>
   				TX_Data <= (others => '0');
   				TX_Valid <= '1';
   			when others =>
   			TX_Data <= (others => '0');
   			TX_Valid <= '0';
   		end case;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		CrcEn <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_IDLE) then
   			CrcEn <= '0';
   		elsif(State_c = ST_ENG_HEAD) or (State_c = ST_HEAD3)  then
   			CrcEn <= '1';
   		elsif(State_c = ST_CRC_H) or (State_c = ST_ACK_RSP)  then
   			CrcEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		CRC_H_En <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_CRC_H) or (State_c = ST_ACK_RSP) then
   			CRC_H_En <= '1';
   		else
   			CRC_H_En <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		TX_Data_r <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(CRC_H_En = '1') then
   			TX_Data_r <= '1' & CRC_Calc;
   		else
   			TX_Data_r <= TX_Data;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if rising_edge(Clk) then
   		TX_Valid_r <= TX_Valid;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		CRC_Calc <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_IDLE) then
   			CRC_Calc <= (others => '0');
   		elsif(CrcEn = '1') then
   			CRC_Calc <= CRC_Calc + TX_Data(7 downto 0);
   		end if;
   	end if;
   end process;
   
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_TUSER <= (others => '1');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_AXIS_DATA) and (TVALID_r2='1') and (TVALID_r3 = '0') then
   			REG_TUSER <= TUSER_r2;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_ENG_CNT <= (others => '1');
   	elsif rising_edge(Clk) then
   		if((State_c = ST_HEAD2)or(State_c = ST_EHEAD2)) and (REG_TUSER = X"00") then
   			REG_ENG_CNT <= REG_ENG_CNT + ("00"& X"001");
   		end if;
   	end if;
   end process;
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   

   -- HDL Embedded Text Block 4 eb4
   -- eb3 3                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		TX_EN_b <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_WAITBEFORE) then
   			TX_EN_b <= '1';
   		elsif(State_c = ST_RXEN) then
   			TX_EN_b <= '0';
   		end if;
   	end if;
   end process;


   -- ModuleWare code(v1.9) for instance 'U_3' of 'adff'
   TDATA_r <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_3reg_cval <= TDATA;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'adff'
   TLAST_r <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_4reg_cval <= TLAST;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'adff'
   TVALID_r <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_5reg_cval <= TVALID;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'adff'
   TUSER_r <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_6reg_cval <= TUSER;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'adff'
   TDATA_r2 <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_7reg_cval <= TDATA_r;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'adff'
   TVALID_r2 <= mw_U_8reg_cval;
   u_8seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_8reg_cval <= TVALID_r;
      END IF;
   END PROCESS u_8seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_9' of 'adff'
   TVALID_r3 <= mw_U_9reg_cval;
   u_9seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_9reg_cval <= TVALID_r2;
      END IF;
   END PROCESS u_9seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_10' of 'adff'
   TUSER_r2 <= mw_U_10reg_cval;
   u_10seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_10reg_cval <= TUSER_r;
      END IF;
   END PROCESS u_10seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_11' of 'adff'
   TLAST_r2 <= mw_U_11reg_cval;
   u_11seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_11reg_cval <= TLAST_r;
      END IF;
   END PROCESS u_11seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_12' of 'adff'
   DEBUG_TX_Data <= mw_U_12reg_cval;
   u_12seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_12reg_cval <= TX_Data(7 downto 0);
      END IF;
   END PROCESS u_12seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_13' of 'adff'
   DEBUG_TX_Valid <= mw_U_13reg_cval;
   u_13seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_13reg_cval <= TX_Valid;
      END IF;
   END PROCESS u_13seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_14' of 'adff'
   TX_EN <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_14reg_cval <= TX_EN_b;
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   Reset_n <= NOT(Reset);

   -- Instance port mappings.
   U_2 : UART_FIFO_S2_SX
      PORT MAP (
         clk          => Clk,
         srst         => Reset,
         din          => FIFO_Din,
         wr_en        => FIFO_WrEn,
         rd_en        => FIFO_RdEn,
         dout         => FIFO_Dout,
         full         => OPEN,
         empty        => OPEN,
         almost_empty => FIFO_AlmostEmpty
      );
   U_0 : UART_TX_DRIVER_PT_C250303
      GENERIC MAP (
         VARPARITY => '0'
      )
      PORT MAP (
         SYS_Clk       => Clk,
         SYS_Reset_n   => Reset_n,
         UART_Clk      => UART_Clk,
         UART_Reset_n  => UART_Reset_n,
         UART_ClkEn    => UART_ClkEn,
         TX_PAD_O      => TX_PAD_O,
         DATA          => TX_Data_r,
         VALID         => TX_Valid_r,
         UART_TF_Empty => OPEN,
         TX_DIS        => TX_DIS
      );
   U_17 : xpm_cdc_single
      PORT MAP (
         src_clk  => UART_Clk,
         src_in   => TX_DIS,
         dest_clk => Clk,
         dest_out => TX_DIS_s2
      );

END struct;
