-- VHDL Entity JWXJ.AXI2GTX_C250324.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 10:12:38 2025/09/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY AXI2GTX_C250324 IS
   GENERIC( 
      CHA_LABEL : std_logic_vector(7 downto 0) := X"33"
   );
   PORT( 
      Clk           : IN     std_logic;
      GReset        : IN     std_logic;
      REG_BASE_TIME : IN     std_logic_vector (63 DOWNTO 0);
      REG_TIME      : IN     std_logic_vector (63 DOWNTO 0);
      Reset         : IN     std_logic;
      TASKID        : IN     std_logic_vector (16 DOWNTO 0);
      TDATA         : IN     std_logic_vector (15 DOWNTO 0);
      TLAST         : IN     std_logic;
      TUSER         : IN     std_logic_vector (1 DOWNTO 0);
      TVALID        : IN     std_logic;
      VERSION       : IN     std_logic_vector (3 DOWNTO 0);
      REG_FRAME_CNT : OUT    std_logic_vector (15 DOWNTO 0);
      RG_Dout       : OUT    std_logic_vector (15 DOWNTO 0);
      RG_EOP        : OUT    std_logic;
      RG_SOP        : OUT    std_logic;
      RG_Vout       : OUT    std_logic
   );

-- Declarations

END AXI2GTX_C250324 ;

--
-- VHDL Architecture JWXJ.AXI2GTX_C250324.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 10:12:39 2025/09/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF AXI2GTX_C250324 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_HEAD1,
      ST_HEAD2,
      ST_HEAD3,
      ST_ENG_HEAD1,
      ST_ENG_HEAD2,
      ST_F_CNT,
      ST_H_CNT,
      ST_TIME1,
      ST_TIME2,
      ST_TIME3,
      ST_TIME4,
      ST_TIME5,
      ST_TIME6,
      ST_DATA,
      ST_CRC,
      ST_TIME7
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;


   -- Internal signal declarations
   SIGNAL CRC_Calc         : std_logic_vector(15 DOWNTO 0);
   SIGNAL CRC_Out_En       : std_logic;
   SIGNAL CrcEn            : std_logic;
   SIGNAL ENG_HEAD2L       : std_logic_vector(7 DOWNTO 0);
   SIGNAL ENG_HEAD2L_r     : std_logic_vector(7 DOWNTO 0);
   SIGNAL FIFO_AlmostEmpty : STD_LOGIC;
   SIGNAL FIFO_Din         : STD_LOGIC_VECTOR(16 DOWNTO 0);
   SIGNAL FIFO_Dout        : STD_LOGIC_VECTOR(16 DOWNTO 0);
   SIGNAL FIFO_RdEn        : STD_LOGIC;
   SIGNAL FIFO_WrEn        : STD_LOGIC;
   SIGNAL FOP              : std_logic;
   SIGNAL REG_F_CNT        : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_H_CNT        : std_logic_vector(15 DOWNTO 0);
   SIGNAL RG_Dout_b        : std_logic_vector(15 DOWNTO 0);
   SIGNAL RG_SOP_b         : std_logic;
   SIGNAL RG_Vout_b        : std_logic;
   SIGNAL SOP              : std_logic;
   SIGNAL SOP_r            : std_logic;
   SIGNAL SOP_r2           : std_logic;
   SIGNAL TDATA_r          : std_logic_vector(15 DOWNTO 0);
   SIGNAL TDATA_r2         : std_logic_vector(15 DOWNTO 0);
   SIGNAL TDATA_r3         : std_logic_vector(15 DOWNTO 0);
   SIGNAL TGOUP            : std_logic_vector(16 DOWNTO 0);
   SIGNAL TLAST_r          : std_logic;
   SIGNAL TLAST_r2         : std_logic;
   SIGNAL TLAST_r3         : std_logic;
   SIGNAL TUSER_r          : std_logic_vector(1 DOWNTO 0);
   SIGNAL TVALID_r         : std_logic;
   SIGNAL TVALID_r2        : std_logic;
   SIGNAL TVALID_r3        : std_logic;
   SIGNAL TX_Data          : std_logic_vector(15 DOWNTO 0);
   SIGNAL TX_Data_r        : std_logic_vector(15 DOWNTO 0);
   SIGNAL TX_Valid         : std_logic;
   SIGNAL TX_Valid_r       : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(1 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_9' of 'adff'
   SIGNAL mw_U_9reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_10' of 'adff'
   SIGNAL mw_U_10reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_11' of 'adff'
   SIGNAL mw_U_11reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_12' of 'adff'
   SIGNAL mw_U_12reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_13' of 'adff'
   SIGNAL mw_U_13reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_14' of 'adff'
   SIGNAL mw_U_14reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_15' of 'adff'
   SIGNAL mw_U_15reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_16' of 'adff'
   SIGNAL mw_U_16reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_17' of 'adff'
   SIGNAL mw_U_17reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_18' of 'adff'
   SIGNAL mw_U_18reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_19' of 'adff'
   SIGNAL mw_U_19reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_21' of 'adff'
   SIGNAL mw_U_21reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_22' of 'adff'
   SIGNAL mw_U_22reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_23' of 'adff'
   SIGNAL mw_U_23reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_24' of 'adff'
   SIGNAL mw_U_24reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_8' of 'split'
   SIGNAL mw_U_8temp_din : std_logic_vector(1 DOWNTO 0);

attribute fsm_safe_state : string;
attribute fsm_safe_state of State_c : signal is "default_state";

   -- Component Declarations
   COMPONENT CAP_NEG
   PORT (
      Clk  : IN     std_logic;
      Din  : IN     std_logic;
      Dout : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT CAP_POS
   PORT (
      Clk  : IN     std_logic;
      Din  : IN     std_logic;
      Dout : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT FrameBuffer_S
   PORT (
      clk          : IN     STD_LOGIC;
      din          : IN     STD_LOGIC_VECTOR ( 16 DOWNTO 0 );
      rd_en        : IN     STD_LOGIC;
      srst         : IN     STD_LOGIC;
      wr_en        : IN     STD_LOGIC;
      almost_empty : OUT    STD_LOGIC;
      dout         : OUT    STD_LOGIC_VECTOR ( 16 DOWNTO 0 );
      empty        : OUT    STD_LOGIC;
      full         : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CAP_NEG USE ENTITY JWXJ.CAP_NEG;
   FOR ALL : CAP_POS USE ENTITY JWXJ.CAP_POS;
   --FOR ALL : FrameBuffer_S USE ENTITY JWXJ.FrameBuffer_S;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      FIFO_Dout,
      SOP,
      State_c
   )
   -----------------------------------------------------------------
   BEGIN
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (SOP='1') THEN 
               State_n <= ST_HEAD1;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_HEAD1 => 
            State_n <= ST_HEAD2;
         WHEN ST_HEAD2 => 
            State_n <= ST_HEAD3;
         WHEN ST_HEAD3 => 
            State_n <= ST_ENG_HEAD1;
         WHEN ST_ENG_HEAD1 => 
            State_n <= ST_ENG_HEAD2;
         WHEN ST_ENG_HEAD2 => 
            State_n <= ST_F_CNT;
         WHEN ST_F_CNT => 
            State_n <= ST_H_CNT;
         WHEN ST_H_CNT => 
            State_n <= ST_TIME1;
         WHEN ST_TIME1 => 
            State_n <= ST_TIME2;
         WHEN ST_TIME2 => 
            State_n <= ST_TIME3;
         WHEN ST_TIME3 => 
            State_n <= ST_TIME4;
         WHEN ST_TIME4 => 
            State_n <= ST_TIME5;
         WHEN ST_TIME5 => 
            State_n <= ST_TIME6;
         WHEN ST_TIME6 => 
            State_n <= ST_TIME7;
         WHEN ST_DATA => 
            IF (FIFO_Dout(16)='1') THEN 
               State_n <= ST_CRC;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_CRC => 
            State_n <= ST_IDLE;
         WHEN ST_TIME7 => 
            State_n <= ST_DATA;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 


   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		FIFO_WrEn <= '0';
   		FIFO_Din  <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(TVALID_r3 = '1') then
   			FIFO_WrEn <= '1';
   			FIFO_Din  <= TGOUP;
   		else
   			FIFO_WrEn <= '0';
   			FIFO_Din  <= (others => '0');
   		end if;
   	end if;
   end process;
   
   FIFO_RdEn <= '1' when (State_c = ST_DATA) else '0';
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		TX_Data <= (others => '0');
   		TX_Valid <= '0';
   	elsif rising_edge(Clk) then
   		case State_c is
   			when ST_DATA =>
   				TX_Data <= FIFO_Dout(15 downto 0);
   				TX_Valid <= '1';
   			when ST_HEAD1 =>
   				TX_Data <= X"EB90";
   				TX_Valid <= '1';
   			when ST_HEAD2 =>
   				TX_Data <= X"B1E2";
   				TX_Valid <= '1';
   			when ST_HEAD3 =>
   				TX_Data <= X"4954";
   				TX_Valid <= '1';
   			when ST_ENG_HEAD1 =>
   				TX_Data <= X"FDFD";
   				TX_Valid <= '1';
   			when ST_ENG_HEAD2 =>
   				TX_Data <= CHA_LABEL & ENG_HEAD2L_r;
   				TX_Valid <= '1';
   			when ST_F_CNT =>
   				TX_Data <= REG_F_CNT;
   				TX_Valid <= '1';
   			when ST_H_CNT =>
   				TX_Data <= REG_H_CNT;
   				TX_Valid <= '1';
   			when ST_TIME1 =>
   				TX_Data <= REG_TIME(63 downto 48);
   				TX_Valid <= '1';
   			when ST_TIME2 =>
   				TX_Data <= REG_TIME(47 downto 32);
   				TX_Valid <= '1';
   			when ST_TIME3 =>
   				TX_Data <= REG_TIME(31 downto 16);
   				TX_Valid <= '1';
   			when ST_TIME4 =>
   				TX_Data <= REG_TIME(15 downto 0);
   				TX_Valid <= '1';
   			when ST_TIME5 =>
   				TX_Data <= REG_BASE_TIME(47 downto 32);
   				TX_Valid <= '1';
   			when ST_TIME6 =>
   				TX_Data <= REG_BASE_TIME(31 downto 16);
   				TX_Valid <= '1';
   			when ST_TIME7 =>
   				TX_Data <= REG_BASE_TIME(15 downto 0);
   				TX_Valid <= '1';
   			when ST_CRC =>
   				TX_Data <= (others => '0');
   				TX_Valid <= '1';
   			when others =>
   			TX_Data <= (others => '0');
   			TX_Valid <= '0';
   		end case;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		CrcEn <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_IDLE) then
   			CrcEn <= '0';
   		elsif(State_c = ST_ENG_HEAD1)  then
   			CrcEn <= '1';
   		elsif(State_c = ST_CRC)  then
   			CrcEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		CRC_Out_En <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_CRC) then
   			CRC_Out_En <= '1';
   		else
   			CRC_Out_En <= '0';
   		end if;
   	end if;
   end process;
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		TX_Data_r <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(CRC_Out_En = '1') then
   			TX_Data_r <= CRC_Calc;
   		else
   			TX_Data_r <= TX_Data;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if rising_edge(Clk) then
   		TX_Valid_r <= TX_Valid;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		CRC_Calc <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_IDLE) then
   			CRC_Calc <= (others => '0');
   		elsif(CrcEn = '1') then
   			CRC_Calc <= CRC_Calc + TX_Data;
   		end if;
   	end if;
   end process;
   
   
   
   process(GReset, Clk) begin
   	if(GReset = '1') then
   		REG_F_CNT <= (others => '1');
   	elsif rising_edge(Clk) then
   		if(FOP = '1') then
   			REG_F_CNT <= REG_F_CNT + X"0001";
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_H_CNT <= (others => '1');
   	elsif rising_edge(Clk) then
   		if(FOP = '1') then
   			REG_H_CNT <= (others => '1');
   		elsif(SOP = '1') then
   			REG_H_CNT <= REG_H_CNT + X"0001";
   		end if;
   	end if;
   end process;
   
   
   
   
   


   -- ModuleWare code(v1.9) for instance 'U_3' of 'adff'
   TDATA_r3 <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_3reg_cval <= TDATA_r2;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'adff'
   TLAST_r3 <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_4reg_cval <= TLAST_r2;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'adff'
   TVALID_r3 <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_5reg_cval <= TVALID_r2;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'adff'
   TUSER_r <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_6reg_cval <= TUSER;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_9' of 'adff'
   TVALID_r <= mw_U_9reg_cval;
   u_9seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_9reg_cval <= TVALID;
      END IF;
   END PROCESS u_9seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_10' of 'adff'
   TVALID_r2 <= mw_U_10reg_cval;
   u_10seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_10reg_cval <= TVALID_r;
      END IF;
   END PROCESS u_10seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_11' of 'adff'
   TDATA_r <= mw_U_11reg_cval;
   u_11seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_11reg_cval <= TDATA;
      END IF;
   END PROCESS u_11seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_12' of 'adff'
   RG_Dout_b <= mw_U_12reg_cval;
   u_12seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_12reg_cval <= TX_Data_r;
      END IF;
   END PROCESS u_12seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_13' of 'adff'
   RG_Vout_b <= mw_U_13reg_cval;
   u_13seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_13reg_cval <= TX_Valid_r;
      END IF;
   END PROCESS u_13seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_14' of 'adff'
   ENG_HEAD2L_r <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_14reg_cval <= ENG_HEAD2L;
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_15' of 'adff'
   TDATA_r2 <= mw_U_15reg_cval;
   u_15seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_15reg_cval <= TDATA_r;
      END IF;
   END PROCESS u_15seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_16' of 'adff'
   TLAST_r <= mw_U_16reg_cval;
   u_16seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_16reg_cval <= TLAST;
      END IF;
   END PROCESS u_16seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_17' of 'adff'
   TLAST_r2 <= mw_U_17reg_cval;
   u_17seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_17reg_cval <= TLAST_r;
      END IF;
   END PROCESS u_17seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_18' of 'adff'
   SOP_r2 <= mw_U_18reg_cval;
   u_18seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_18reg_cval <= SOP_r;
      END IF;
   END PROCESS u_18seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_19' of 'adff'
   SOP <= mw_U_19reg_cval;
   u_19seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_19reg_cval <= SOP_r2;
      END IF;
   END PROCESS u_19seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_21' of 'adff'
   RG_Dout <= mw_U_21reg_cval;
   u_21seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_21reg_cval <= RG_Dout_b;
      END IF;
   END PROCESS u_21seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'adff'
   RG_Vout <= mw_U_22reg_cval;
   u_22seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_22reg_cval <= RG_Vout_b;
      END IF;
   END PROCESS u_22seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_23' of 'adff'
   RG_SOP <= mw_U_23reg_cval;
   u_23seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_23reg_cval <= RG_SOP_b;
      END IF;
   END PROCESS u_23seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_24' of 'adff'
   REG_FRAME_CNT <= mw_U_24reg_cval;
   u_24seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_24reg_cval <= REG_F_CNT;
      END IF;
   END PROCESS u_24seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_0' of 'merge'
   u_0combo_proc: PROCESS(TASKID, VERSION)
   VARIABLE temp_dout : std_logic_vector(20 DOWNTO 0);
   BEGIN
      temp_dout :=  TASKID & VERSION;
      ENG_HEAD2L <= temp_dout(7 DOWNTO 0);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'merge'
   TGOUP <= TLAST_r3 & TDATA_r3;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'split'
   mw_U_8temp_din <= TUSER_r;
   u_8combo_proc: PROCESS (mw_U_8temp_din)
   VARIABLE temp_din: std_logic_vector(1 DOWNTO 0);
   BEGIN
      temp_din := mw_U_8temp_din(1 DOWNTO 0);
      SOP_r <= temp_din(0);
      FOP <= temp_din(1);
   END PROCESS u_8combo_proc;

   -- Instance port mappings.
   U_20 : CAP_NEG
      PORT MAP (
         Clk  => Clk,
         Din  => TX_Valid_r,
         Dout => RG_EOP
      );
   U_1 : CAP_POS
      PORT MAP (
         Clk  => Clk,
         Din  => TX_Valid_r,
         Dout => RG_SOP_b
      );
   U_2 : FrameBuffer_S
      PORT MAP (
         clk          => Clk,
         srst         => Reset,
         din          => FIFO_Din,
         wr_en        => FIFO_WrEn,
         rd_en        => FIFO_RdEn,
         dout         => FIFO_Dout,
         full         => OPEN,
         empty        => OPEN,
         almost_empty => FIFO_AlmostEmpty
      );

END struct;
