-- VHDL Entity JWXJ.BASIC_SEND_C220509.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 18:26:28 2025/03/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY BASIC_SEND_C220509 IS
   PORT( 
      Clk        : IN     std_logic;
      FIFO_Din   : IN     std_logic_vector (16 DOWNTO 0);
      FIFO_Empty : IN     std_logic;
      LS         : IN     std_logic_vector (15 DOWNTO 0);
      Req        : IN     std_logic;
      Reset      : IN     std_logic;
      Dout       : OUT    std_logic_vector (15 DOWNTO 0);
      FIFO_Rd    : OUT    std_logic;
      Kout       : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END BASIC_SEND_C220509 ;

--
-- VHDL Architecture JWXJ.BASIC_SEND_C220509.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 18:26:28 2025/03/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF BASIC_SEND_C220509 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_WAIT,
      ST_ACK,
      ST_IDLE,
      ST_DATA,
      ST_HEAD
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;


   -- Internal signal declarations
   SIGNAL AddWaitCnt : std_logic;
   SIGNAL EndWaitCnt : std_logic;
   SIGNAL ST_Cnt     : std_logic_vector(15 DOWNTO 0);
   SIGNAL WaitCnt    : std_logic_vector(15 DOWNTO 0);



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      EndWaitCnt,
      FIFO_Din,
      Req,
      State_c
   )
   -----------------------------------------------------------------
   BEGIN
      CASE State_c IS
         WHEN ST_WAIT => 
            IF (EndWaitCnt = '1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_WAIT;
            END IF;
         WHEN ST_ACK => 
            State_n <= ST_WAIT;
         WHEN ST_IDLE => 
            IF (Req = '1') THEN 
               State_n <= ST_HEAD;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_DATA => 
            IF (FIFO_Din(16) = '1') THEN 
               State_n <= ST_ACK;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_HEAD => 
            State_n <= ST_DATA;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 


   -- HDL Embedded Text Block 2 eb2
   
   
   FIFO_Rd <=  '1' when ((State_c = ST_DATA) and (FIFO_Empty = '0')) else '0';
   
   
   process(Reset, Clk) begin
      if(Reset = '1') then
         Dout <= X"C5BC";
         Kout <= "01";
      elsif rising_edge(Clk) then
         case (State_c) is
            when ST_HEAD =>
               Dout <= X"5CFB";
               Kout <= "11";
            when ST_DATA =>
   				Dout <= FIFO_Din(15 downto 0);
   				Kout <= "00";
   		 when ST_ACK  => 
   				Dout <= X"FDFE";
   				Kout <= "11";
            when others =>
               Dout <= X"C5BC";
               Kout <= "01";
         end case;
      end if;
   end process;
   
   
   
   
   

   -- HDL Embedded Text Block 4 eb4
   -- eb3 3                                        
   process(Clk,Reset) begin
      if(Reset = '1') then
         WaitCnt <= (others => '0');
      elsif rising_edge(Clk) then
         if (AddWaitCnt = '1') then
            if(EndWaitCnt = '1') then
               WaitCnt <= (others => '0');
            else
               WaitCnt <= WaitCnt + X"0001";
            end if;
         end if;
      end if;
   end process;
   
   AddWaitCnt <= '1' when (State_c = ST_WAIT) else '0';
   
   EndWaitCnt <= '1' when (AddWaitCnt = '1') and (WaitCnt = LS) else '0';
   
   process(Clk) begin
   	if rising_edge(Clk) then
   		if (State_c = ST_IDLE) then                                       
   		   ST_Cnt <= (others => '0');
   		else
   		   ST_Cnt <= ST_Cnt + X"0001";
   		end if;
   	end if;
   end process;
   
   
   
   
   
   
   


   -- Instance port mappings.

END struct;
