-- VHDL Entity JWXJ.DownSample.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 14:03:20 2025/03/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY DownSample IS
   PORT( 
      Clk      : IN     std_logic;
      FOP      : IN     std_logic;
      GReset   : IN     std_logic;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic;
      S_TUSER  : IN     std_logic;
      S_TVALID : IN     std_logic;
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic;
      M_TUSER  : OUT    std_logic;
      M_TVALID : OUT    std_logic
   );

-- Declarations

END DownSample ;

--
-- VHDL Architecture JWXJ.DownSample.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 14:03:20 2025/03/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF DownSample IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_WR,
      ST_SOP,
      ST_DATA,
      ST_EOP,
      ST_ROWCNT,
      ST_WAIT
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(11 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(11 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_WR : std_logic;
   SIGNAL csm1_to_ST_DATA : std_logic;


   -- Internal signal declarations
   SIGNAL Cnt         : std_logic;
   SIGNAL DATA        : std_logic_vector(15 DOWNTO 0);
   SIGNAL EOP         : std_logic;
   SIGNAL FIFO_Din    : std_logic_vector(15 DOWNTO 0);
   SIGNAL FIFO_Dout   : std_logic_vector(15 DOWNTO 0);
   SIGNAL FIFO_RdEn   : std_logic;
   SIGNAL FIFO_WrEn   : std_logic;
   SIGNAL M_SOP       : std_logic;
   SIGNAL M_SOP_r     : std_logic;
   SIGNAL M_TDATA_b   : std_logic_vector(15 DOWNTO 0);
   SIGNAL M_TDATA_c   : std_logic_vector(15 DOWNTO 0);
   SIGNAL M_TLAST_b   : std_logic;
   SIGNAL M_TLAST_b2  : std_logic;
   SIGNAL M_TVALID_b  : std_logic;
   SIGNAL Reset       : std_logic;
   SIGNAL RowCnt      : std_logic;
   SIGNAL SOP         : std_logic;
   SIGNAL S_TDATA_r   : std_logic_vector(15 DOWNTO 0);
   SIGNAL S_TDATA_r2  : std_logic_vector(15 DOWNTO 0);
   SIGNAL S_TDATA_r3  : std_logic_vector(15 DOWNTO 0);
   SIGNAL S_TLAST_r   : std_logic;
   SIGNAL S_TLAST_r2  : std_logic;
   SIGNAL S_TLAST_r3  : std_logic;
   SIGNAL S_TVALID_r  : std_logic;
   SIGNAL S_TVALID_r2 : std_logic;
   SIGNAL S_TVALID_r3 : std_logic;
   SIGNAL VALID       : std_logic;
   SIGNAL dout        : std_logic;
   SIGNAL dout1       : std_logic;
   SIGNAL dout2       : std_logic;
   SIGNAL dout3       : std_logic;
   SIGNAL dout4       : std_logic_vector(15 DOWNTO 0);
   SIGNAL empty       : std_logic;
   SIGNAL full        : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_19' of 'adff'
   SIGNAL mw_U_19reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_20' of 'adff'
   SIGNAL mw_U_20reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_21' of 'adff'
   SIGNAL mw_U_21reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_22' of 'adff'
   SIGNAL mw_U_22reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_23' of 'adff'
   SIGNAL mw_U_23reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_24' of 'adff'
   SIGNAL mw_U_24reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_25' of 'adff'
   SIGNAL mw_U_25reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_26' of 'adff'
   SIGNAL mw_U_26reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_27' of 'adff'
   SIGNAL mw_U_27reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_28' of 'adff'
   SIGNAL mw_U_28reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_29' of 'adff'
   SIGNAL mw_U_29reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_31' of 'adff'
   SIGNAL mw_U_31reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_32' of 'adff'
   SIGNAL mw_U_32reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_33' of 'adff'
   SIGNAL mw_U_33reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_34' of 'adff'
   SIGNAL mw_U_34reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_35' of 'adff'
   SIGNAL mw_U_35reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_36' of 'adff'
   SIGNAL mw_U_36reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_37' of 'adff'
   SIGNAL mw_U_37reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_38' of 'adff'
   SIGNAL mw_U_38reg_cval : std_logic;

   -- Component Declarations
   COMPONENT LINE_BUFFER_B16
   PORT (
      clk   : IN     std_logic;
      din   : IN     std_logic_vector (15 DOWNTO 0);
      rd_en : IN     std_logic;
      srst  : IN     std_logic;
      wr_en : IN     std_logic;
      dout  : OUT    std_logic_vector (15 DOWNTO 0);
      empty : OUT    std_logic;
      full  : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Cnt <= '0';
   	elsif rising_edge(Clk) then
   		if(SOP='1') then
   			Cnt <= '0';
   		elsif(VALID='1') then
   			Cnt <= not(Cnt);
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		FIFO_WrEn <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_WR) and (Cnt = '0') then
   			FIFO_WrEn <= '1';
   		else
   			FIFO_WrEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		FIFO_Din <= (others => '0');
   	elsif rising_edge(Clk) then
   		FIFO_Din <= DATA;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		FIFO_RdEn <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SOP) or (State_c = ST_DATA) or (State_c = ST_EOP) then
   			FIFO_RdEn <= '1';
   		else
   			FIFO_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_TVALID_b <= '0';
   	elsif rising_edge(Clk) then
   		if(FIFO_RdEn = '1') then
   			M_TVALID_b <= '1';
   		else
   			M_TVALID_b <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_TDATA_b <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(FIFO_RdEn = '1') then
   			M_TDATA_b <= FIFO_Dout;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_SOP <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SOP) then
   			M_SOP <= '1'; 
   		else
   			M_SOP <= '0';
   		end if;
   	end if;
   end process;
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_TLAST_b <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_EOP) then
   			M_TLAST_b <= '1';
   		else
   			M_TLAST_b <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RowCnt <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_ROWCNT) then
   			RowCnt <= not(RowCnt);
   		end if;
   	end if;
   end process;
   

   -- HDL Embedded Block 2 eb2
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      EOP,
      RowCnt,
      SOP,
      State_c,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_WR <= '0';
      csm1_to_ST_DATA <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (SOP='1') THEN 
               State_n <= ST_ROWCNT;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_WR => 
            IF (EOP='1') THEN 
               State_n <= ST_SOP;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_SOP;
            ELSE
               State_n <= ST_WR;
            END IF;
         WHEN ST_SOP => 
            State_n <= ST_DATA;
            csm1_to_ST_DATA <= '1';
         WHEN ST_DATA => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_EOP;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_EOP => 
            State_n <= ST_IDLE;
         WHEN ST_ROWCNT => 
            State_n <= ST_WAIT;
         WHEN ST_WAIT => 
            IF (RowCnt='1') THEN 
               State_n <= ST_WR;
               csm1_to_ST_WR <= '1';
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_WR,
      csm1_to_ST_DATA
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_WR = '1') THEN
         csm1_next_timer <= "011111111111"; -- no cycles(2048)-1=2047
      ELSIF (csm1_to_ST_DATA = '1') THEN
         csm1_next_timer <= "001111111101"; -- no cycles(1022)-1=1021
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;




   -- ModuleWare code(v1.9) for instance 'U_19' of 'adff'
   SOP <= mw_U_19reg_cval;
   u_19seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_19reg_cval <= S_TUSER;
      END IF;
   END PROCESS u_19seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_20' of 'adff'
   S_TVALID_r <= mw_U_20reg_cval;
   u_20seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_20reg_cval <= S_TVALID;
      END IF;
   END PROCESS u_20seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_21' of 'adff'
   S_TVALID_r2 <= mw_U_21reg_cval;
   u_21seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_21reg_cval <= S_TVALID_r;
      END IF;
   END PROCESS u_21seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'adff'
   S_TDATA_r <= mw_U_22reg_cval;
   u_22seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_22reg_cval <= S_TDATA;
      END IF;
   END PROCESS u_22seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_23' of 'adff'
   S_TDATA_r2 <= mw_U_23reg_cval;
   u_23seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_23reg_cval <= S_TDATA_r;
      END IF;
   END PROCESS u_23seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_24' of 'adff'
   S_TLAST_r <= mw_U_24reg_cval;
   u_24seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_24reg_cval <= S_TLAST;
      END IF;
   END PROCESS u_24seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_25' of 'adff'
   S_TLAST_r2 <= mw_U_25reg_cval;
   u_25seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_25reg_cval <= S_TLAST_r;
      END IF;
   END PROCESS u_25seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_26' of 'adff'
   M_SOP_r <= mw_U_26reg_cval;
   u_26seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_26reg_cval <= M_SOP;
      END IF;
   END PROCESS u_26seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_27' of 'adff'
   M_TVALID <= mw_U_27reg_cval;
   u_27seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_27reg_cval <= M_TVALID_b;
      END IF;
   END PROCESS u_27seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_28' of 'adff'
   M_TDATA <= mw_U_28reg_cval;
   u_28seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_28reg_cval <= M_TDATA_c;
      END IF;
   END PROCESS u_28seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_29' of 'adff'
   M_TLAST_b2 <= mw_U_29reg_cval;
   u_29seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_29reg_cval <= M_TLAST_b;
      END IF;
   END PROCESS u_29seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_31' of 'adff'
   M_TUSER <= mw_U_31reg_cval;
   u_31seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_31reg_cval <= M_SOP_r;
      END IF;
   END PROCESS u_31seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_32' of 'adff'
   M_TLAST <= mw_U_32reg_cval;
   u_32seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_32reg_cval <= M_TLAST_b2;
      END IF;
   END PROCESS u_32seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_33' of 'adff'
   VALID <= mw_U_33reg_cval;
   u_33seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_33reg_cval <= S_TVALID_r3;
      END IF;
   END PROCESS u_33seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_34' of 'adff'
   DATA <= mw_U_34reg_cval;
   u_34seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_34reg_cval <= S_TDATA_r3;
      END IF;
   END PROCESS u_34seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_35' of 'adff'
   EOP <= mw_U_35reg_cval;
   u_35seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_35reg_cval <= S_TLAST_r3;
      END IF;
   END PROCESS u_35seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_36' of 'adff'
   S_TVALID_r3 <= mw_U_36reg_cval;
   u_36seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_36reg_cval <= S_TVALID_r2;
      END IF;
   END PROCESS u_36seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_37' of 'adff'
   S_TDATA_r3 <= mw_U_37reg_cval;
   u_37seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_37reg_cval <= S_TDATA_r2;
      END IF;
   END PROCESS u_37seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_38' of 'adff'
   S_TLAST_r3 <= mw_U_38reg_cval;
   u_38seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_38reg_cval <= S_TLAST_r2;
      END IF;
   END PROCESS u_38seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'and'
   dout1 <= FIFO_WrEn AND dout;

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   dout2 <= FIFO_RdEn AND dout3;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'gnd'
   dout4 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_4' of 'inv'
   dout <= NOT(full);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'inv'
   dout3 <= NOT(empty);

   -- ModuleWare code(v1.9) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(dout4, M_TDATA_b, M_TVALID_b)
   BEGIN
      CASE M_TVALID_b IS
      WHEN '0' => M_TDATA_c <= dout4;
      WHEN '1' => M_TDATA_c <= M_TDATA_b;
      WHEN OTHERS => M_TDATA_c <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_2' of 'or'
   Reset <= GReset OR FOP;

   -- Instance port mappings.
   U_0 : LINE_BUFFER_B16
      PORT MAP (
         clk   => Clk,
         srst  => Reset,
         din   => FIFO_Din,
         wr_en => dout1,
         rd_en => dout2,
         dout  => FIFO_Dout,
         full  => full,
         empty => empty
      );

END struct;
