-- VHDL Entity JWXJ.FrameGen.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 10:19:58 2025/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FrameGen IS
   PORT( 
      Clk100M   : IN     std_logic;
      Clk25M    : IN     std_logic;
      DinA      : IN     std_logic_vector (11 DOWNTO 0);
      DinB      : IN     std_logic_vector (11 DOWNTO 0);
      DinC      : IN     std_logic_vector (11 DOWNTO 0);
      DinD      : IN     std_logic_vector (11 DOWNTO 0);
      Reset100M : IN     std_logic;
      Reset25M  : IN     std_logic;
      Vin       : IN     std_logic;
      Wr_En     : IN     std_logic;
      TDATA     : OUT    std_logic_vector (11 DOWNTO 0);
      TLAST     : OUT    std_logic;
      TVALID    : OUT    std_logic
   );

-- Declarations

END FrameGen ;

--
-- VHDL Architecture JWXJ.FrameGen.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 10:19:58 2025/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY JWXJ;
LIBRARY xpm;

ARCHITECTURE struct OF FrameGen IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_WR,
      ST_RDA,
      ST_RDB,
      ST_RDC,
      ST_RDD,
      ST_IDLE
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(9 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(9 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_RDA : std_logic;
   SIGNAL csm1_to_ST_RDB : std_logic;
   SIGNAL csm1_to_ST_RDC : std_logic;
   SIGNAL csm1_to_ST_RDD : std_logic;


   -- Internal signal declarations
   SIGNAL FIFOA_Dout          : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOA_RdEn          : std_logic;
   SIGNAL FIFOA_WrDin         : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOA_WrEn          : std_logic;
   SIGNAL FIFOB_Dout          : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOB_RdEn          : std_logic;
   SIGNAL FIFOB_WrDin         : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOB_WrEn          : std_logic;
   SIGNAL FIFOC_Dout          : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOC_RdEn          : std_logic;
   SIGNAL FIFOC_WrDin         : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOC_WrEn          : std_logic;
   SIGNAL FIFOD_AlmostEmpty   : std_logic;
   SIGNAL FIFOD_AlmostEmpty_r : std_logic;
   SIGNAL FIFOD_Dout          : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOD_RdEn          : std_logic;
   SIGNAL FIFOD_WrDin         : std_logic_vector(11 DOWNTO 0);
   SIGNAL FIFOD_WrEn          : std_logic;
   SIGNAL TDATA_b             : std_logic_vector(11 DOWNTO 0);
   SIGNAL TLAST_b             : std_logic;
   SIGNAL TVALID_b            : std_logic;
   SIGNAL Wr_En_s             : std_logic;


   -- Component Declarations
   COMPONENT ChanBuffer
   PORT (
      din          : IN     std_logic_vector (11 DOWNTO 0);
      rd_clk       : IN     std_logic;
      rd_en        : IN     std_logic;
      rst          : IN     std_logic;
      wr_clk       : IN     std_logic;
      wr_en        : IN     std_logic;
      almost_empty : OUT    std_logic;
      almost_full  : OUT    std_logic;
      dout         : OUT    std_logic_vector (11 DOWNTO 0);
      empty        : OUT    std_logic;
      full         : OUT    std_logic;
      rd_rst_busy  : OUT    std_logic;
      wr_rst_busy  : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT xpm_cdc_single
   GENERIC (
      DEST_SYNC_FF   : integer := 4;
      INIT_SYNC_FF   : integer := 0;
      SIM_ASSERT_CHK : integer := 0;
      SRC_INPUT_REG  : integer := 1;
      VERSION        : integer := 0
   );
   PORT (
      dest_clk : IN     std_logic;
      src_clk  : IN     std_logic;
      src_in   : IN     std_logic;
      dest_out : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process(Reset25M, Clk25M) begin
   	if(Reset25M = '1') then
   		FIFOA_WrEn <= '0';
   		FIFOB_WrEn <= '0';
   		FIFOC_WrEn <= '0';
   		FIFOD_WrEn <= '0';
   		FIFOA_WrDin <= (others => '0');
   		FIFOB_WrDin <= (others => '0');
   		FIFOC_WrDin <= (others => '0');
   		FIFOD_WrDin <= (others => '0');
   	elsif rising_edge(Clk25M) then
   		if(Wr_En_s = '1') then
   			FIFOA_WrEn <= Vin;
   			FIFOB_WrEn <= Vin;
   			FIFOC_WrEn <= Vin;
   			FIFOD_WrEn <= Vin;
   			FIFOA_WrDin <= DinA;
   			FIFOB_WrDin <= DinB;
   			FIFOC_WrDin <= DinC;
   			FIFOD_WrDin <= DinD;
   		else
   			FIFOA_WrEn <= '0';
   			FIFOB_WrEn <= '0';
   			FIFOC_WrEn <= '0';
   			FIFOD_WrEn <= '0';
   			FIFOA_WrDin <= (others => '0');
   			FIFOB_WrDin <= (others => '0');
   			FIFOC_WrDin <= (others => '0');
   			FIFOD_WrDin <= (others => '0');
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		FIFOA_RdEn <= '0';
   	elsif rising_edge(Clk100M) then
   		if(State_c = ST_RDA) and (Wr_En_s = '0') then
   			FIFOA_RdEn <= '1';
   		else
   			FIFOA_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		FIFOA_RdEn <= '0';
   	elsif rising_edge(Clk100M) then
   		if(State_c = ST_RDA) and (Wr_En_s = '0') then
   			FIFOA_RdEn <= '1';
   		else
   			FIFOA_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		FIFOB_RdEn <= '0';
   	elsif rising_edge(Clk100M) then
   		if(State_c = ST_RDB) and (Wr_En_s = '0') then
   			FIFOB_RdEn <= '1';
   		else
   			FIFOB_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		FIFOC_RdEn <= '0';
   	elsif rising_edge(Clk100M) then
   		if(State_c = ST_RDC) and (Wr_En_s = '0') then
   			FIFOC_RdEn <= '1';
   		else
   			FIFOC_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		FIFOD_RdEn <= '0';
   	elsif rising_edge(Clk100M) then
   		if(State_c = ST_RDD) and (Wr_En_s = '0') then
   			FIFOD_RdEn <= '1';
   		else
   			FIFOD_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		TVALID_b <= '0';
   	elsif rising_edge(Clk100M) then
   		TVALID_b <= FIFOA_RdEn or FIFOB_RdEn or FIFOC_RdEn or FIFOD_RdEn;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		TDATA_b <= (others => '0');
   	elsif rising_edge(Clk100M) then
   		if(FIFOA_RdEn = '1') then
   			TDATA_b <= FIFOA_Dout;
   		elsif(FIFOB_RdEn = '1') then
   			TDATA_b <= FIFOB_Dout;
   		elsif(FIFOC_RdEn = '1') then
   			TDATA_b <= FIFOC_Dout;
   		elsif(FIFOD_RdEn = '1') then
   			TDATA_b <= FIFOD_Dout;
   		else
   			TDATA_b <= (others => '0');
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if rising_edge(Clk100M) then
   		FIFOD_AlmostEmpty_r <= FIFOD_AlmostEmpty;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		TLAST_b <= '0';
   	elsif rising_edge(Clk100M) then
   		if(FIFOD_AlmostEmpty_r = '0') and (FIFOD_AlmostEmpty = '1') and (Wr_En_s = '0') then
   			TLAST_b <= '1';
   		else
   			TLAST_b <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		TVALID <= '0';
   		TDATA  <= (others => '0');
   		TLAST  <= '0';
   	elsif rising_edge(Clk100M) then
   		TVALID <= TVALID_b;
   		TDATA  <= TDATA_b;
   		TLAST  <= TLAST_b;
   	end if;
   end process;
   
   
   
   
   
   
   
   
   
   
   

   -- HDL Embedded Block 2 eb2
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk100M,
      Reset100M
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset100M = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk100M'EVENT AND Clk100M = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      FIFOD_AlmostEmpty,
      State_c,
      Wr_En_s,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_RDA <= '0';
      csm1_to_ST_RDB <= '0';
      csm1_to_ST_RDC <= '0';
      csm1_to_ST_RDD <= '0';
      CASE State_c IS
         WHEN ST_WR => 
            IF (Wr_En_s='0') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_WR;
            END IF;
         WHEN ST_RDA => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_RDB;
               csm1_to_ST_RDB <= '1';
            ELSE
               State_n <= ST_RDA;
            END IF;
         WHEN ST_RDB => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_RDC;
               csm1_to_ST_RDC <= '1';
            ELSE
               State_n <= ST_RDB;
            END IF;
         WHEN ST_RDC => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_RDD;
               csm1_to_ST_RDD <= '1';
            ELSE
               State_n <= ST_RDC;
            END IF;
         WHEN ST_RDD => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_RDD;
            END IF;
         WHEN ST_IDLE => 
            IF (Wr_En_s='1') THEN 
               State_n <= ST_WR;
            ELSIF ((Wr_En_s='0') and (FIFOD_AlmostEmpty='0')) THEN 
               State_n <= ST_RDA;
               csm1_to_ST_RDA <= '1';
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_RDA,
      csm1_to_ST_RDB,
      csm1_to_ST_RDC,
      csm1_to_ST_RDD
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_RDA = '1') THEN
         csm1_next_timer <= "0111111111"; -- no cycles(512)-1=511
      ELSIF (csm1_to_ST_RDB = '1') THEN
         csm1_next_timer <= "0111111111"; -- no cycles(512)-1=511
      ELSIF (csm1_to_ST_RDC = '1') THEN
         csm1_next_timer <= "0111111111"; -- no cycles(512)-1=511
      ELSIF (csm1_to_ST_RDD = '1') THEN
         csm1_next_timer <= "0111111111"; -- no cycles(512)-1=511
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;




   -- Instance port mappings.
   U_0 : ChanBuffer
      PORT MAP (
         rst          => Reset25M,
         wr_clk       => Clk25M,
         rd_clk       => Clk100M,
         din          => FIFOA_WrDin,
         wr_en        => FIFOA_WrEn,
         rd_en        => FIFOA_RdEn,
         dout         => FIFOA_Dout,
         full         => OPEN,
         almost_full  => OPEN,
         empty        => OPEN,
         almost_empty => OPEN,
         wr_rst_busy  => OPEN,
         rd_rst_busy  => OPEN
      );
   U_1 : ChanBuffer
      PORT MAP (
         rst          => Reset25M,
         wr_clk       => Clk25M,
         rd_clk       => Clk100M,
         din          => FIFOB_WrDin,
         wr_en        => FIFOB_WrEn,
         rd_en        => FIFOB_RdEn,
         dout         => FIFOB_Dout,
         full         => OPEN,
         almost_full  => OPEN,
         empty        => OPEN,
         almost_empty => OPEN,
         wr_rst_busy  => OPEN,
         rd_rst_busy  => OPEN
      );
   U_2 : ChanBuffer
      PORT MAP (
         rst          => Reset25M,
         wr_clk       => Clk25M,
         rd_clk       => Clk100M,
         din          => FIFOC_WrDin,
         wr_en        => FIFOC_WrEn,
         rd_en        => FIFOC_RdEn,
         dout         => FIFOC_Dout,
         full         => OPEN,
         almost_full  => OPEN,
         empty        => OPEN,
         almost_empty => OPEN,
         wr_rst_busy  => OPEN,
         rd_rst_busy  => OPEN
      );
   U_3 : ChanBuffer
      PORT MAP (
         rst          => Reset25M,
         wr_clk       => Clk25M,
         rd_clk       => Clk100M,
         din          => FIFOD_WrDin,
         wr_en        => FIFOD_WrEn,
         rd_en        => FIFOD_RdEn,
         dout         => FIFOD_Dout,
         full         => OPEN,
         almost_full  => OPEN,
         empty        => OPEN,
         almost_empty => FIFOD_AlmostEmpty,
         wr_rst_busy  => OPEN,
         rd_rst_busy  => OPEN
      );
   U_4 : xpm_cdc_single
      PORT MAP (
         src_clk  => Clk25M,
         src_in   => Wr_En,
         dest_clk => Clk100M,
         dest_out => Wr_En_s
      );

END struct;
