-- VHDL Entity JWXJ.FrameGenPingPang_C250322.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 13:47:30 2025/04/ 7
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FrameGenPingPang_C250322 IS
   PORT( 
      Clk100M   : IN     std_logic;
      Clk25M    : IN     std_logic;
      DinA      : IN     std_logic_vector (11 DOWNTO 0);
      DinB      : IN     std_logic_vector (11 DOWNTO 0);
      DinC      : IN     std_logic_vector (11 DOWNTO 0);
      DinD      : IN     std_logic_vector (11 DOWNTO 0);
      DinE      : IN     std_logic_vector (11 DOWNTO 0);
      DinF      : IN     std_logic_vector (11 DOWNTO 0);
      DinG      : IN     std_logic_vector (11 DOWNTO 0);
      DinH      : IN     std_logic_vector (11 DOWNTO 0);
      FOP       : IN     std_logic;
      REG_H     : IN     std_logic;
      Reset100M : IN     std_logic;
      Reset25M  : IN     std_logic;
      SOP       : IN     std_logic;
      D_FIFOH   : OUT    std_logic_vector (2 DOWNTO 0);
      TDATA     : OUT    std_logic_vector (11 DOWNTO 0);
      TLAST     : OUT    std_logic;
      TUSER     : OUT    std_logic_vector (1 DOWNTO 0);
      TVALID    : OUT    std_logic
   );

-- Declarations

END FrameGenPingPang_C250322 ;

--
-- VHDL Architecture JWXJ.FrameGenPingPang_C250322.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 13:47:30 2025/04/ 7
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY JWXJ;
LIBRARY xpm;

ARCHITECTURE struct OF FrameGenPingPang_C250322 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      SP_A,
      SP_B
   );
 
   -- Declare current and next state signals
   SIGNAL PING_State_c : CSM1_STATE_TYPE;
   SIGNAL PING_State_n : CSM1_STATE_TYPE;

   -- Non hierarchical state machine declarations
   TYPE CSM2_STATE_TYPE IS (
      ST_IDLE,
      ST_WAIT_BEFORE,
      ST_DATA,
      ST_WAIT_AFTER,
      ST_SWT
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM2_STATE_TYPE;
   SIGNAL State_n : CSM2_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm2_timer : std_logic_vector(9 DOWNTO 0);
   SIGNAL csm2_next_timer : std_logic_vector(9 DOWNTO 0);
   SIGNAL csm2_timeout : std_logic;
   SIGNAL csm2_to_ST_WAIT_BEFORE : std_logic;
   SIGNAL csm2_to_ST_DATA : std_logic;
   SIGNAL csm2_to_ST_WAIT_AFTER : std_logic;


   -- Internal signal declarations
   SIGNAL FOP25M       : std_logic;
   SIGNAL H_Flag       : std_logic;
   SIGNAL REG_FIRST    : std_logic;
   SIGNAL Reset100M_OR : std_logic;
   SIGNAL Reset25M_OR  : std_logic;
   SIGNAL SWT          : std_logic;
   SIGNAL TDATA_CA     : std_logic_vector(11 DOWNTO 0);
   SIGNAL TDATA_CB     : std_logic_vector(11 DOWNTO 0);
   SIGNAL TDATA_b      : std_logic_vector(11 DOWNTO 0);
   SIGNAL TDATA_b2     : std_logic_vector(11 DOWNTO 0);
   SIGNAL TLAST_CA     : std_logic;
   SIGNAL TLAST_CB     : std_logic;
   SIGNAL TLAST_b      : std_logic;
   SIGNAL TLAST_b2     : std_logic;
   SIGNAL TUSER_FOP    : std_logic;
   SIGNAL TUSER_SOP    : std_logic;
   SIGNAL TUSER_b      : std_logic_vector(1 DOWNTO 0);
   SIGNAL TVALID_CA    : std_logic;
   SIGNAL TVALID_CB    : std_logic;
   SIGNAL TVALID_b     : std_logic;
   SIGNAL TVALID_b2    : std_logic;
   SIGNAL Vin          : std_logic;
   SIGNAL Wr_EnA       : std_logic;
   SIGNAL Wr_EnB       : std_logic;
   SIGNAL dout         : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_13' of 'adff'
   SIGNAL mw_U_13reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_14' of 'adff'
   SIGNAL mw_U_14reg_cval : std_logic_vector(1 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_15' of 'adff'
   SIGNAL mw_U_15reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_16' of 'adff'
   SIGNAL mw_U_16reg_cval : std_logic;

   -- Component Declarations
   COMPONENT CAP_POS
   PORT (
      Clk  : IN     std_logic;
      Din  : IN     std_logic;
      Dout : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT FrameGen_C250322
   PORT (
      Clk100M   : IN     std_logic ;
      Clk25M    : IN     std_logic ;
      DinA      : IN     std_logic_vector (11 DOWNTO 0);
      DinB      : IN     std_logic_vector (11 DOWNTO 0);
      DinC      : IN     std_logic_vector (11 DOWNTO 0);
      DinD      : IN     std_logic_vector (11 DOWNTO 0);
      DinE      : IN     std_logic_vector (11 DOWNTO 0);
      DinF      : IN     std_logic_vector (11 DOWNTO 0);
      DinG      : IN     std_logic_vector (11 DOWNTO 0);
      DinH      : IN     std_logic_vector (11 DOWNTO 0);
      H_Flag    : IN     std_logic ;
      REG_H     : IN     std_logic ;
      Reset100M : IN     std_logic ;
      Reset25M  : IN     std_logic ;
      Vin       : IN     std_logic ;
      Wr_En     : IN     std_logic ;
      D_FIFOH   : OUT    std_logic_vector (2 DOWNTO 0);
      TDATA     : OUT    std_logic_vector (11 DOWNTO 0);
      TLAST     : OUT    std_logic ;
      TVALID    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT xpm_cdc_single
   GENERIC (
      DEST_SYNC_FF   : integer := 4;
      INIT_SYNC_FF   : integer := 0;
      SIM_ASSERT_CHK : integer := 0;
      SRC_INPUT_REG  : integer := 1;
      VERSION        : integer := 0
   );
   PORT (
      dest_clk : IN     std_logic;
      src_clk  : IN     std_logic;
      src_in   : IN     std_logic;
      dest_out : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CAP_POS USE ENTITY JWXJ.CAP_POS;
   FOR ALL : FrameGen_C250322 USE ENTITY JWXJ.FrameGen_C250322;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk25M,
      Reset25M
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset25M = '1') THEN
         PING_State_c <= SP_B;
      ELSIF (Clk25M'EVENT AND Clk25M = '1') THEN
         PING_State_c <= PING_State_n;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      PING_State_c,
      SWT
   )
   -----------------------------------------------------------------
   BEGIN
      CASE PING_State_c IS
         WHEN SP_A => 
            IF (SWT='1') THEN 
               PING_State_n <= SP_B;
            ELSE
               PING_State_n <= SP_A;
            END IF;
         WHEN SP_B => 
            IF (SWT='1') THEN 
               PING_State_n <= SP_A;
            ELSE
               PING_State_n <= SP_B;
            END IF;
         WHEN OTHERS =>
            PING_State_n <= SP_B;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 


   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		TVALID_b <= '0';
   		TDATA_b  <= (others => '0');
   		TLAST_b  <= '0';
   	elsif rising_edge(Clk100M) then
   		if(Wr_EnA='0') then
   			TVALID_b <= TVALID_CA;
   			TDATA_b  <= TDATA_CA;
   			TLAST_b  <= TLAST_CA;
   		else
   			TVALID_b <= TVALID_CB;
   			TDATA_b  <= TDATA_CB;
   			TLAST_b  <= TLAST_CB;
   		end if;
   	end if;
   end process;
   
   
   

   -- HDL Embedded Block 3 eb3
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm2_clocked_proc : PROCESS ( 
      Clk25M,
      Reset25M
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset25M = '1') THEN
         State_c <= ST_IDLE;
         csm2_timer <= (OTHERS => '0');
      ELSIF (Clk25M'EVENT AND Clk25M = '1') THEN
         State_c <= State_n;
         csm2_timer <= csm2_next_timer;
      END IF;
   END PROCESS csm2_clocked_proc;
 
   -----------------------------------------------------------------
   csm2_nextstate_proc : PROCESS ( 
      SOP,
      State_c,
      csm2_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm2_to_ST_WAIT_BEFORE <= '0';
      csm2_to_ST_DATA <= '0';
      csm2_to_ST_WAIT_AFTER <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (SOP='1') THEN 
               State_n <= ST_WAIT_BEFORE;
               csm2_to_ST_WAIT_BEFORE <= '1';
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_WAIT_BEFORE => 
            IF (csm2_timeout = '1') THEN 
               State_n <= ST_DATA;
               csm2_to_ST_DATA <= '1';
            ELSE
               State_n <= ST_WAIT_BEFORE;
            END IF;
         WHEN ST_DATA => 
            IF (csm2_timeout = '1') THEN 
               State_n <= ST_WAIT_AFTER;
               csm2_to_ST_WAIT_AFTER <= '1';
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_WAIT_AFTER => 
            IF (csm2_timeout = '1') THEN 
               State_n <= ST_SWT;
            ELSE
               State_n <= ST_WAIT_AFTER;
            END IF;
         WHEN ST_SWT => 
            State_n <= ST_IDLE;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm2_nextstate_proc;
 
   -----------------------------------------------------------------
   csm2_wait_combo_proc: PROCESS (
      csm2_timer,
      csm2_to_ST_WAIT_BEFORE,
      csm2_to_ST_DATA,
      csm2_to_ST_WAIT_AFTER
   )
   -----------------------------------------------------------------
   VARIABLE csm2_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm2_timer) = 0) THEN
         csm2_temp_timeout := '1';
      ELSE
         csm2_temp_timeout := '0';
      END IF;

      IF (csm2_to_ST_WAIT_BEFORE = '1') THEN
         csm2_next_timer <= "0000000111"; -- no cycles(8)-1=7
      ELSIF (csm2_to_ST_DATA = '1') THEN
         csm2_next_timer <= "0111111111"; -- no cycles(512)-1=511
      ELSIF (csm2_to_ST_WAIT_AFTER = '1') THEN
         csm2_next_timer <= "0000000001"; -- no cycles(2)-1=1
      ELSE
         IF (csm2_temp_timeout = '1') THEN
            csm2_next_timer <= (OTHERS=>'0');
         ELSE
            csm2_next_timer <= unsigned(csm2_timer) - '1';
         END IF;
      END IF;
      csm2_timeout <= csm2_temp_timeout;
   END PROCESS csm2_wait_combo_proc;



   -- HDL Embedded Text Block 4 eb4
   -- eb4 4                                        
   process(Reset25M, Clk25M) begin
   	if(Reset25M = '1') then
   		SWT <= '0';
   	elsif rising_edge(Clk25M) then
   		if(State_c = ST_SWT) then
   			SWT <= '1';
   		else
   			SWT <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset25M, Clk25M) begin
   	if(Reset25M = '1') then
   		Vin <= '0';
   	elsif rising_edge(Clk25M) then
   		if(State_c = ST_DATA) then
   			Vin <= '1';
   		else
   			Vin <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset25M, Clk25M) begin
   	if(Reset25M = '1') then
   		Wr_EnA <= '0';
   	elsif rising_edge(Clk25M) then
   		if(PING_State_c = SP_A) then
   			Wr_EnA <= '1';
   		else
   			Wr_EnA <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset100M, Clk100M) begin
   	if(Reset100M = '1') then
   		REG_FIRST <= '0';
   	elsif rising_edge(Clk100M) then
   		if(FOP = '1') then
   			REG_FIRST <= '1';
   		elsif(TLAST_b = '1') then
   			REG_FIRST <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset25M, Clk25M) begin
   	if(Reset25M = '1') then
   		H_Flag <= '0';
   	elsif rising_edge(Clk25M) then
   		if(SOP = '1' ) then
   			H_Flag <= '0';
   		else
   			H_Flag <= not(H_Flag);
   		end if;
   	end if;
   end process;
   
   
   
   
   
   
   
   
   
   
   


   -- ModuleWare code(v1.9) for instance 'U_3' of 'adff'
   TVALID_b2 <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_3reg_cval <= TVALID_b;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'adff'
   TDATA_b2 <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_4reg_cval <= TDATA_b;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'adff'
   TLAST_b2 <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_5reg_cval <= TLAST_b;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_13' of 'adff'
   TVALID <= mw_U_13reg_cval;
   u_13seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_13reg_cval <= TVALID_b2;
      END IF;
   END PROCESS u_13seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_14' of 'adff'
   TUSER <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_14reg_cval <= TUSER_b;
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_15' of 'adff'
   TDATA <= mw_U_15reg_cval;
   u_15seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_15reg_cval <= TDATA_b2;
      END IF;
   END PROCESS u_15seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_16' of 'adff'
   TLAST <= mw_U_16reg_cval;
   u_16seq_proc: PROCESS (Clk100M)BEGIN
      IF (Clk100M'EVENT AND Clk100M='1') THEN
         mw_U_16reg_cval <= TLAST_b2;
      END IF;
   END PROCESS u_16seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_11' of 'gnd'
   dout <= '0';

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   Wr_EnB <= NOT(Wr_EnA);

   -- ModuleWare code(v1.9) for instance 'U_12' of 'merge'
   TUSER_b <= TUSER_FOP & TUSER_SOP;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'mux'
   u_7combo_proc: PROCESS(dout, TUSER_SOP, REG_FIRST)
   BEGIN
      CASE REG_FIRST IS
      WHEN '0' => TUSER_FOP <= dout;
      WHEN '1' => TUSER_FOP <= TUSER_SOP;
      WHEN OTHERS => TUSER_FOP <= 'X';
      END CASE;
   END PROCESS u_7combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'or'
   Reset100M_OR <= FOP OR Reset100M;

   -- ModuleWare code(v1.9) for instance 'U_10' of 'or'
   Reset25M_OR <= FOP25M OR Reset25M;

   -- Instance port mappings.
   U_6 : CAP_POS
      PORT MAP (
         Clk  => Clk100M,
         Din  => TVALID_b,
         Dout => TUSER_SOP
      );
   U_0 : FrameGen_C250322
      PORT MAP (
         Clk100M   => Clk100M,
         Clk25M    => Clk25M,
         DinA      => DinA,
         DinB      => DinB,
         DinC      => DinC,
         DinD      => DinD,
         DinE      => DinE,
         DinF      => DinF,
         DinG      => DinG,
         DinH      => DinH,
         H_Flag    => H_Flag,
         REG_H     => REG_H,
         Reset100M => Reset100M_OR,
         Reset25M  => Reset25M_OR,
         Vin       => Vin,
         Wr_En     => Wr_EnA,
         D_FIFOH   => OPEN,
         TDATA     => TDATA_CA,
         TLAST     => TLAST_CA,
         TVALID    => TVALID_CA
      );
   U_1 : FrameGen_C250322
      PORT MAP (
         Clk100M   => Clk100M,
         Clk25M    => Clk25M,
         DinA      => DinA,
         DinB      => DinB,
         DinC      => DinC,
         DinD      => DinD,
         DinE      => DinE,
         DinF      => DinF,
         DinG      => DinG,
         DinH      => DinH,
         H_Flag    => H_Flag,
         REG_H     => REG_H,
         Reset100M => Reset100M_OR,
         Reset25M  => Reset25M_OR,
         Vin       => Vin,
         Wr_En     => Wr_EnB,
         D_FIFOH   => D_FIFOH,
         TDATA     => TDATA_CB,
         TLAST     => TLAST_CB,
         TVALID    => TVALID_CB
      );
   U_9 : xpm_cdc_single
      PORT MAP (
         src_clk  => Clk100M,
         src_in   => FOP,
         dest_clk => Clk25M,
         dest_out => FOP25M
      );

END struct;
