-- VHDL Entity JWXJ.FrameCtrl_C250820.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 15:46:37 2025/08/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FrameCtrl_C250820 IS
   PORT( 
      Clk        : IN     std_logic;
      ClkMs_En   : IN     std_logic;
      FREQ_valid : IN     STD_LOGIC;
      Freq       : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);
      Reset      : IN     std_logic;
      Start      : IN     std_logic;
      Stop       : IN     std_logic;
      CF         : OUT    STD_LOGIC;
      FOP        : OUT    std_logic
   );

-- Declarations

END FrameCtrl_C250820 ;

--
-- VHDL Architecture JWXJ.FrameCtrl_C250820.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 15:46:37 2025/08/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;
USE IEEE.NUMERIC_STD.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF FrameCtrl_C250820 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DivOut_Valid      : STD_LOGIC;
   SIGNAL Div_Res           : std_logic_vector(15 DOWNTO 0);
   SIGNAL Div_Valid         : STD_LOGIC;
   SIGNAL Pulse_Interval    : std_logic_vector(15 DOWNTO 0);
   SIGNAL dout              : std_logic_vector(15 DOWNTO 0);
   SIGNAL m_axis_dout_tdata : STD_LOGIC_VECTOR( 23 DOWNTO 0 );
   SIGNAL pulse_out         : STD_LOGIC;


   -- ModuleWare signal declarations(v1.9) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- Component Declarations
   COMPONENT Div
   PORT (
      aclk                   : IN     STD_LOGIC;
      s_axis_dividend_tdata  : IN     STD_LOGIC_VECTOR ( 15 DOWNTO 0 );
      s_axis_dividend_tvalid : IN     STD_LOGIC;
      s_axis_divisor_tdata   : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      s_axis_divisor_tvalid  : IN     STD_LOGIC;
      m_axis_dout_tdata      : OUT    STD_LOGIC_VECTOR ( 23 DOWNTO 0 );
      m_axis_dout_tvalid     : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Input_Passthrough
   PORT (
      clk    : IN     STD_LOGIC;
      input  : IN     STD_LOGIC;
      rst    : IN     STD_LOGIC;
      start  : IN     STD_LOGIC;
      stop   : IN     STD_LOGIC;
      output : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Pulse_Generator
   GENERIC (
      COUNTER_WIDTH : positive := 32
   );
   PORT (
      clk            : IN     STD_LOGIC;
      ms_pulse       : IN     STD_LOGIC;
      pulse_interval : IN     STD_LOGIC_VECTOR (COUNTER_WIDTH - 1 DOWNTO 0);
      rst            : IN     STD_LOGIC;
      pulse_out      : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Pulse_Widener
   GENERIC (
      PULSE_WIDTH : positive := 5
   );
   PORT (
      clk       : IN     STD_LOGIC;
      pulse_in  : IN     STD_LOGIC;
      rst       : IN     STD_LOGIC;
      pulse_out : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   --FOR ALL : Div USE ENTITY JWXJ.Div;
   FOR ALL : Input_Passthrough USE ENTITY JWXJ.Input_Passthrough;
   FOR ALL : Pulse_Generator USE ENTITY JWXJ.Pulse_Generator;
   FOR ALL : Pulse_Widener USE ENTITY JWXJ.Pulse_Widener;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Pulse_Interval <= X"0064";
   	elsif rising_edge(Clk) then
   		if(Div_Valid = '1') then
   			Pulse_Interval <= Div_Res;
   		end if;
   	end if;
   end process;


   -- ModuleWare code(v1.9) for instance 'U_2' of 'adff'
   Div_Res <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_2reg_cval <= m_axis_dout_tdata(23 DOWNTO 8);
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'adff'
   Div_Valid <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_5reg_cval <= DivOut_Valid;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'constval'
   dout <= "0010011100010000";

   -- Instance port mappings.
   U_0 : Div
      PORT MAP (
         aclk                   => Clk,
         s_axis_divisor_tvalid  => FREQ_valid,
         s_axis_divisor_tdata   => Freq,
         s_axis_dividend_tvalid => FREQ_valid,
         s_axis_dividend_tdata  => dout,
         m_axis_dout_tvalid     => DivOut_Valid,
         m_axis_dout_tdata      => m_axis_dout_tdata
      );
   U_3 : Input_Passthrough
      PORT MAP (
         clk    => Clk,
         rst    => Reset,
         start  => Start,
         stop   => Stop,
         input  => pulse_out,
         output => FOP
      );
   U_4 : Pulse_Generator
      GENERIC MAP (
         COUNTER_WIDTH => 16
      )
      PORT MAP (
         clk            => Clk,
         rst            => Reset,
         ms_pulse       => ClkMs_En,
         pulse_interval => Pulse_Interval,
         pulse_out      => pulse_out
      );
   U_97 : Pulse_Widener
      GENERIC MAP (
         PULSE_WIDTH => 10
      )
      PORT MAP (
         clk       => Clk,
         rst       => Reset,
         pulse_in  => pulse_out,
         pulse_out => CF
      );

END struct;
