-- VHDL Entity JWXJ.FrameCtrl_C250414.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 11:10:52 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FrameCtrl_C250414 IS
   GENERIC( 
      DEF_CLKNUM : std_logic_vector(15 downto 0) := X"03E8"
   );
   PORT( 
      Clk      : IN     std_logic;
      ClkMs_En : IN     std_logic;
      Din      : IN     std_logic_vector (7 DOWNTO 0);
      Reset    : IN     std_logic;
      Start    : IN     std_logic;
      Stop     : IN     std_logic;
      FOP      : OUT    std_logic
   );

-- Declarations

END FrameCtrl_C250414 ;

--
-- VHDL Architecture JWXJ.FrameCtrl_C250414.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 11:10:53 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF FrameCtrl_C250414 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_CNT,
      ST_CLR,
      ST_DIV_IN,
      ST_CHK,
      ST_DIV_OUT,
      ST_WAIT,
      ST_DEFAULT,
      ST_SET,
      ST_RST
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(4 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(4 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_DIV_OUT : std_logic;


   -- Internal signal declarations
   SIGNAL Add_Cnt           : std_logic;
   SIGNAL Cnt               : std_logic_vector(15 DOWNTO 0);
   SIGNAL DivIn_Tvalid      : STD_LOGIC;
   SIGNAL DivOut_Tvalid     : STD_LOGIC;
   SIGNAL Div_Res           : std_logic_vector(15 DOWNTO 0);
   SIGNAL End_Cnt           : std_logic;
   SIGNAL Freq              : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL Ready             : std_logic;
   SIGNAL XX                : std_logic_vector(15 DOWNTO 0);
   SIGNAL dout              : std_logic_vector(15 DOWNTO 0);
   SIGNAL m_axis_dout_tdata : STD_LOGIC_VECTOR( 23 DOWNTO 0 );


   -- ModuleWare signal declarations(v1.9) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(15 DOWNTO 0);

   -- Component Declarations
   COMPONENT Div
   PORT (
      aclk                   : IN     STD_LOGIC;
      s_axis_dividend_tdata  : IN     STD_LOGIC_VECTOR ( 15 DOWNTO 0 );
      s_axis_dividend_tvalid : IN     STD_LOGIC;
      s_axis_divisor_tdata   : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      s_axis_divisor_tvalid  : IN     STD_LOGIC;
      m_axis_dout_tdata      : OUT    STD_LOGIC_VECTOR ( 23 DOWNTO 0 );
      m_axis_dout_tvalid     : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Div USE ENTITY JWXJ.Div;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      DivOut_Tvalid,
      End_Cnt,
      Ready,
      Start,
      State_c,
      Stop,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_DIV_OUT <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (Start='1') THEN 
               State_n <= ST_CHK;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_CNT => 
            IF (End_Cnt='1') THEN 
               State_n <= ST_CLR;
            ELSIF (Stop='1') THEN 
               State_n <= ST_RST;
            ELSE
               State_n <= ST_CNT;
            END IF;
         WHEN ST_CLR => 
            State_n <= ST_CNT;
         WHEN ST_DIV_IN => 
            State_n <= ST_DIV_OUT;
            csm1_to_ST_DIV_OUT <= '1';
         WHEN ST_CHK => 
            State_n <= ST_WAIT;
         WHEN ST_DIV_OUT => 
            IF (DivOut_Tvalid='1') THEN 
               State_n <= ST_SET;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_DEFAULT;
            ELSE
               State_n <= ST_DIV_OUT;
            END IF;
         WHEN ST_WAIT => 
            IF (Ready='1') THEN 
               State_n <= ST_DIV_IN;
            ELSIF (Ready='0') THEN 
               State_n <= ST_DEFAULT;
            ELSE
               State_n <= ST_WAIT;
            END IF;
         WHEN ST_DEFAULT => 
            State_n <= ST_CNT;
         WHEN ST_SET => 
            State_n <= ST_CNT;
         WHEN ST_RST => 
            State_n <= ST_IDLE;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_DIV_OUT
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_DIV_OUT = '1') THEN
         csm1_next_timer <= "10011"; -- no cycles(20)-1=19
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		FOP <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_CLR) then
   			FOP <= '1';
   		else
   			FOP <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Cnt <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_CLR) or (State_c = ST_RST) then
   			Cnt <= (others => '0');
   		elsif(Add_Cnt = '1') then
   			if(End_Cnt = '1') then
   				Cnt <= (others => '0');
   			else
   				Cnt <= Cnt + X"0001";
   			end if;
   		end if;
   	end if;
   end process;
   
   Add_Cnt <= '1' when (State_c = ST_CNT) and (ClkMs_En = '1') else '0';
   End_Cnt <= '1' when (Add_Cnt = '1') and (Cnt = XX) else '0';
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		XX <= DEF_CLKNUM;
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SET) then
   			XX <= Div_Res;
   		elsif(State_c = ST_DEFAULT) then
   			XX <= DEF_CLKNUM;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Ready <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_CHK) then
   			if(Din > X"C8") then
   				Ready <= '0';
   			else
   				Ready <= '1';
   			end if;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		DivIn_Tvalid <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_DIV_IN) then
   			DivIn_Tvalid <= '1';
   		else
   			DivIn_Tvalid <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Freq <= X"05";
   	elsif rising_edge(Clk) then
   		if(State_c = ST_DIV_IN) then
   			Freq <= Din;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		XX <= DEF_CLKNUM;
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SET) then
   			XX <= Div_Res;
   		elsif(State_c = ST_DEFAULT) then
   			XX <= DEF_CLKNUM;
   		end if;
   	end if;
   end process;
   
   
   
   
   


   -- ModuleWare code(v1.9) for instance 'U_2' of 'adff'
   Div_Res <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_2reg_cval <= m_axis_dout_tdata(23 DOWNTO 8);
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'constval'
   dout <= "0010011100010000";

   -- Instance port mappings.
   U_0 : Div
      PORT MAP (
         aclk                   => Clk,
         s_axis_divisor_tvalid  => DivIn_Tvalid,
         s_axis_divisor_tdata   => Freq,
         s_axis_dividend_tvalid => DivIn_Tvalid,
         s_axis_dividend_tdata  => dout,
         m_axis_dout_tvalid     => DivOut_Tvalid,
         m_axis_dout_tdata      => m_axis_dout_tdata
      );

END struct;
