-- VHDL Entity JWXJ.JWXJ_TOP.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 15:41:50 2025/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY JWXJ_TOP IS
   PORT( 
      Clk         : IN     std_logic;
      Clk25M      : IN     std_logic;
      OPT_B_Clk   : IN     std_logic;
      OPT_B_Reset : IN     std_logic;
      OPT_Z_Clk   : IN     std_logic;
      OPT_Z_Reset : IN     std_logic;
      Reset       : IN     std_logic;
      Reset25M    : IN     std_logic;
      Start       : IN     std_logic;
      GTX_B_Dout  : OUT    std_logic_vector (15 DOWNTO 0);
      GTX_B_Kout  : OUT    std_logic_vector (1 DOWNTO 0);
      GTX_Z_Dout  : OUT    std_logic_vector (15 DOWNTO 0);
      GTX_Z_Kout  : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END JWXJ_TOP ;

--
-- VHDL Architecture JWXJ.JWXJ_TOP.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 15:41:50 2025/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF JWXJ_TOP IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL B_Req                 : std_logic;
   SIGNAL DinA                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinB                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinC                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinD                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL FOP                   : std_logic;
   SIGNAL GTXFIFO_B_Dout        : std_logic_vector(16 DOWNTO 0);
   SIGNAL GTXFIFO_B_Empty       : std_logic;
   SIGNAL GTXFIFO_B_Full        : std_logic;
   SIGNAL GTXFIFO_B_Rd          : std_logic;
   SIGNAL GTXFIFO_B_rd_rst_busy : std_logic;
   SIGNAL GTXFIFO_Z_Dout        : std_logic_vector(16 DOWNTO 0);
   SIGNAL GTXFIFO_Z_Empty       : std_logic;
   SIGNAL GTXFIFO_Z_Full        : std_logic;
   SIGNAL GTXFIFO_Z_Rd          : std_logic;
   SIGNAL GTXFIFO_Z_rd_rst_busy : std_logic;
   SIGNAL LS                    : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_BASE_TIME         : std_logic_vector(63 DOWNTO 0);
   SIGNAL REG_TIME              : std_logic_vector(63 DOWNTO 0);
   SIGNAL RG_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL RG_Vout               : std_logic;
   SIGNAL Reset25M_n            : std_logic;
   SIGNAL SOP                   : std_logic;
   SIGNAL Self_Sync_Rx          : STD_LOGIC;
   SIGNAL TASKID                : std_logic_vector(16 DOWNTO 0);
   SIGNAL TDATA                 : std_logic_vector(11 DOWNTO 0);
   SIGNAL TDATA16               : std_logic_vector(15 DOWNTO 0);
   SIGNAL TLAST                 : std_logic;
   SIGNAL TUSER                 : std_logic_vector(1 DOWNTO 0);
   SIGNAL TVALID                : std_logic;
   SIGNAL VERSION               : std_logic_vector(3 DOWNTO 0);
   SIGNAL Z_Req                 : std_logic;
   SIGNAL dout                  : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout1                 : std_logic;
   SIGNAL dout2                 : std_logic;
   SIGNAL dout3                 : std_logic;
   SIGNAL dout4                 : std_logic;
   SIGNAL dout5                 : std_logic;
   SIGNAL dout6                 : std_logic;


attribute keep: string;

attribute keep of TDATA: signal is "true";
attribute keep of TVALID: signal is "true";
attribute keep of TLAST: signal is "true";

   -- Component Declarations
   COMPONENT AXI2GTX_C250311
   GENERIC (
      CHA_LABEL : std_logic_vector(7 downto 0) := X"33"
   );
   PORT (
      Clk           : IN     std_logic ;
      REG_BASE_TIME : IN     std_logic_vector (63 DOWNTO 0);
      REG_TIME      : IN     std_logic_vector (63 DOWNTO 0);
      Reset         : IN     std_logic ;
      TASKID        : IN     std_logic_vector (16 DOWNTO 0);
      TDATA         : IN     std_logic_vector (15 DOWNTO 0);
      TLAST         : IN     std_logic ;
      TUSER         : IN     std_logic_vector (1 DOWNTO 0);
      TVALID        : IN     std_logic ;
      VERSION       : IN     std_logic_vector (3 DOWNTO 0);
      RG_Dout       : OUT    std_logic_vector (16 DOWNTO 0);
      RG_Vout       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BASIC_SEND_C220509
   PORT (
      Clk        : IN     std_logic ;
      FIFO_Din   : IN     std_logic_vector (16 DOWNTO 0);
      FIFO_Empty : IN     std_logic ;
      LS         : IN     std_logic_vector (15 DOWNTO 0);
      Req        : IN     std_logic ;
      Reset      : IN     std_logic ;
      Dout       : OUT    std_logic_vector (15 DOWNTO 0);
      FIFO_Rd    : OUT    std_logic ;
      Kout       : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT FrameCtrl
   PORT (
      Clk   : IN     std_logic ;
      Reset : IN     std_logic ;
      Start : IN     std_logic ;
      FOP   : OUT    std_logic ;
      SOP   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FrameGenPingPang
   PORT (
      Clk100M   : IN     std_logic ;
      Clk25M    : IN     std_logic ;
      DinA      : IN     std_logic_vector (11 DOWNTO 0);
      DinB      : IN     std_logic_vector (11 DOWNTO 0);
      DinC      : IN     std_logic_vector (11 DOWNTO 0);
      DinD      : IN     std_logic_vector (11 DOWNTO 0);
      FOP       : IN     std_logic ;
      Reset100M : IN     std_logic ;
      Reset25M  : IN     std_logic ;
      SOP       : IN     std_logic ;
      TDATA     : OUT    std_logic_vector (11 DOWNTO 0);
      TLAST     : OUT    std_logic ;
      TUSER     : OUT    std_logic_vector (1 DOWNTO 0);
      TVALID    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT GTX_FIFO
   PORT (
      din         : IN     std_logic_vector (16 DOWNTO 0);
      rd_clk      : IN     std_logic;
      rd_en       : IN     std_logic;
      rst         : IN     std_logic;
      wr_clk      : IN     std_logic;
      wr_en       : IN     std_logic;
      dout        : OUT    std_logic_vector (16 DOWNTO 0);
      empty       : OUT    std_logic;
      full        : OUT    std_logic;
      rd_rst_busy : OUT    std_logic;
      wr_rst_busy : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT IMA_GEN
   PORT (
      Clk_Ref        : IN     STD_LOGIC;
      Cmd_Check2     : IN     STD_LOGIC;
      Rst_Ref        : IN     STD_LOGIC;
      Frame_Circle_S : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);
      Self_Image_Out : OUT    STD_LOGIC;
      Self_Par_Chan1 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan2 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan3 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan4 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan5 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan6 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan7 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan8 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Sync_Rx   : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AXI2GTX_C250311 USE ENTITY JWXJ.AXI2GTX_C250311;
   FOR ALL : BASIC_SEND_C220509 USE ENTITY JWXJ.BASIC_SEND_C220509;
   FOR ALL : FrameCtrl USE ENTITY JWXJ.FrameCtrl;
   FOR ALL : FrameGenPingPang USE ENTITY JWXJ.FrameGenPingPang;
   FOR ALL : IMA_GEN USE ENTITY JWXJ.IMA_GEN;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_9' of 'and'
   dout2 <= RG_Vout AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'and'
   dout5 <= RG_Vout AND dout3;

   -- ModuleWare code(v1.9) for instance 'U_18' of 'constval'
   LS <= "0000000000101000";

   -- ModuleWare code(v1.9) for instance 'U_6' of 'gnd'
   dout <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_8' of 'gnd'
   VERSION <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_15' of 'gnd'
   TASKID <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_16' of 'gnd'
   REG_BASE_TIME <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_17' of 'gnd'
   REG_TIME <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_10' of 'inv'
   dout1 <= NOT(GTXFIFO_Z_Full);

   -- ModuleWare code(v1.9) for instance 'U_12' of 'inv'
   Z_Req <= NOT(GTXFIFO_Z_Empty);

   -- ModuleWare code(v1.9) for instance 'U_19' of 'inv'
   Reset25M_n <= NOT(Reset25M);

   -- ModuleWare code(v1.9) for instance 'U_21' of 'inv'
   B_Req <= NOT(GTXFIFO_B_Empty);

   -- ModuleWare code(v1.9) for instance 'U_23' of 'inv'
   dout3 <= NOT(GTXFIFO_B_Full);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'merge'
   TDATA16 <= dout & TDATA;

   -- ModuleWare code(v1.9) for instance 'U_92' of 'or'
   dout4 <= GTXFIFO_Z_rd_rst_busy OR OPT_Z_Reset;

   -- ModuleWare code(v1.9) for instance 'U_93' of 'or'
   dout6 <= GTXFIFO_B_rd_rst_busy OR OPT_B_Reset;

   -- Instance port mappings.
   U_14 : AXI2GTX_C250311
      GENERIC MAP (
         CHA_LABEL => X"33"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => Reset,
         TASKID        => TASKID,
         TDATA         => TDATA16,
         TLAST         => TLAST,
         TUSER         => TUSER,
         TVALID        => TVALID,
         VERSION       => VERSION,
         RG_Dout       => RG_Dout,
         RG_Vout       => RG_Vout
      );
   U_11 : BASIC_SEND_C220509
      PORT MAP (
         Clk        => OPT_Z_Clk,
         FIFO_Din   => GTXFIFO_Z_Dout,
         FIFO_Empty => GTXFIFO_Z_Empty,
         LS         => LS,
         Req        => Z_Req,
         Reset      => dout4,
         Dout       => GTX_Z_Dout,
         FIFO_Rd    => GTXFIFO_Z_Rd,
         Kout       => GTX_Z_Kout
      );
   U_13 : BASIC_SEND_C220509
      PORT MAP (
         Clk        => OPT_B_Clk,
         FIFO_Din   => GTXFIFO_B_Dout,
         FIFO_Empty => GTXFIFO_B_Empty,
         LS         => LS,
         Req        => B_Req,
         Reset      => dout6,
         Dout       => GTX_B_Dout,
         FIFO_Rd    => GTXFIFO_B_Rd,
         Kout       => GTX_B_Kout
      );
   U_7 : FrameCtrl
      PORT MAP (
         Clk   => Clk,
         Reset => Reset,
         Start => Start,
         FOP   => FOP,
         SOP   => SOP
      );
   U_1 : FrameGenPingPang
      PORT MAP (
         Clk100M   => Clk,
         Clk25M    => Clk25M,
         DinA      => DinA,
         DinB      => DinB,
         DinC      => DinC,
         DinD      => DinD,
         FOP       => FOP,
         Reset100M => Reset,
         Reset25M  => Reset25M,
         SOP       => Self_Sync_Rx,
         TDATA     => TDATA,
         TLAST     => TLAST,
         TUSER     => TUSER,
         TVALID    => TVALID
      );
   U_4 : GTX_FIFO
      PORT MAP (
         rst         => Reset,
         wr_clk      => Clk,
         rd_clk      => OPT_Z_Clk,
         din         => RG_Dout,
         wr_en       => dout2,
         rd_en       => GTXFIFO_Z_Rd,
         dout        => GTXFIFO_Z_Dout,
         full        => GTXFIFO_Z_Full,
         empty       => GTXFIFO_Z_Empty,
         wr_rst_busy => OPEN,
         rd_rst_busy => GTXFIFO_Z_rd_rst_busy
      );
   U_20 : GTX_FIFO
      PORT MAP (
         rst         => Reset,
         wr_clk      => Clk,
         rd_clk      => OPT_B_Clk,
         din         => RG_Dout,
         wr_en       => dout5,
         rd_en       => GTXFIFO_B_Rd,
         dout        => GTXFIFO_B_Dout,
         full        => GTXFIFO_B_Full,
         empty       => GTXFIFO_B_Empty,
         wr_rst_busy => OPEN,
         rd_rst_busy => GTXFIFO_B_rd_rst_busy
      );
   U_0 : IMA_GEN
      PORT MAP (
         Clk_Ref        => Clk25M,
         Rst_Ref        => Reset25M_n,
         Self_Sync_Rx   => Self_Sync_Rx,
         Self_Image_Out => OPEN,
         Self_Par_Chan1 => DinA,
         Self_Par_Chan2 => DinB,
         Self_Par_Chan3 => DinC,
         Self_Par_Chan4 => DinD,
         Self_Par_Chan5 => OPEN,
         Self_Par_Chan6 => OPEN,
         Self_Par_Chan7 => OPEN,
         Self_Par_Chan8 => OPEN,
         Cmd_Check2     => SOP,
         Frame_Circle_S => OPEN
      );

END struct;
