-- VHDL Entity JWXJ.JWXJ_YC_C250912.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 17:54:06 2025/12/ 5
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY JWXJ_YC_C250912 IS
   PORT( 
      AWREADY         : IN     std_logic;
      CMA_POWER       : IN     std_logic;
      CMA_Sen_State   : IN     std_logic_vector (7 DOWNTO 0);
      CMB_POWER       : IN     std_logic;
      CMB_Sen_State   : IN     std_logic_vector (7 DOWNTO 0);
      Clk             : IN     std_logic;
      ClkMs_En        : IN     std_logic;
      REGA_CAP_ENABLE : IN     std_logic;
      REGA_EXPOTIME   : IN     std_logic_vector (15 DOWNTO 0);
      REGA_FRAME_FREQ : IN     std_logic_vector (7 DOWNTO 0);
      REGA_GAIN_MODE  : IN     std_logic;
      REGA_GAIN_VAL   : IN     std_logic_vector (7 DOWNTO 0);
      REGA_IN_NUM     : IN     std_logic_vector (15 DOWNTO 0);
      REGA_KC_X       : IN     std_logic_vector (15 DOWNTO 0);
      REGA_KC_Y       : IN     std_logic_vector (15 DOWNTO 0);
      REGA_OUT_NUM    : IN     std_logic_vector (15 DOWNTO 0);
      REGA_STATE      : IN     std_logic_vector (7 DOWNTO 0);
      REGB_CAP_ENABLE : IN     std_logic;
      REGB_EXPOTIME   : IN     std_logic_vector (15 DOWNTO 0);
      REGB_FRAME_FREQ : IN     std_logic_vector (7 DOWNTO 0);
      REGB_GAIN_MODE  : IN     std_logic;
      REGB_GAIN_VAL   : IN     std_logic_vector (7 DOWNTO 0);
      REGB_IN_NUM     : IN     std_logic_vector (15 DOWNTO 0);
      REGB_KC_X       : IN     std_logic_vector (15 DOWNTO 0);
      REGB_KC_Y       : IN     std_logic_vector (15 DOWNTO 0);
      REGB_OUT_NUM    : IN     std_logic_vector (15 DOWNTO 0);
      REGB_STATE      : IN     std_logic_vector (7 DOWNTO 0);
      REG_CAP_MODE    : IN     std_logic_vector (7 DOWNTO 0);
      REG_CMD_NUM     : IN     std_logic_vector (15 DOWNTO 0);
      REG_CX          : IN     std_logic_vector (15 DOWNTO 0);
      REG_ERR         : IN     std_logic_vector (15 DOWNTO 0);
      REG_NUM         : IN     std_logic_vector (15 DOWNTO 0);
      REG_OUTPUT_MODE : IN     std_logic_vector (7 DOWNTO 0);
      REG_TASKID      : IN     std_logic_vector (7 DOWNTO 0);
      REG_VERSION     : IN     std_logic_vector (7 DOWNTO 0);
      Reset           : IN     std_logic;
      Rsp_Start       : IN     std_logic;
      Rsp_State       : IN     std_logic_vector (1 DOWNTO 0);
      WREADY          : IN     std_logic;
      AWADDR          : OUT    std_logic_vector (7 DOWNTO 0);
      AWLEN           : OUT    std_logic_vector (7 DOWNTO 0);
      AWVALID         : OUT    std_logic;
      WDATA           : OUT    std_logic_vector (7 DOWNTO 0);
      WLAST           : OUT    std_logic;
      WVALID          : OUT    std_logic
   );

-- Declarations

END JWXJ_YC_C250912 ;

--
-- VHDL Architecture JWXJ.JWXJ_YC_C250912.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 17:54:06 2025/12/ 5
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--d
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;


ARCHITECTURE struct OF JWXJ_YC_C250912 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_REG13,
      ST_REG14,
      ST_REG15,
      ST_REG16,
      ST_REG17,
      ST_REG18,
      ST_REG19,
      ST_REG20,
      ST_REG21,
      ST_REG22,
      ST_REG23,
      ST_REG24,
      ST_REG25,
      ST_REG26,
      ST_REG27,
      ST_REG28,
      ST_REG29,
      ST_REG30,
      ST_REG31,
      ST_REG32,
      ST_REG33,
      ST_REG34,
      ST_REG35,
      ST_WAIT_A,
      ST_WAIT3,
      ST_YC_AWADDR_A,
      ST_WAIT4,
      ST_WAIT_B,
      ST_YC_AWADDR_B,
      s5,
      s6,
      s7,
      ST_YC_WAIT,
      ST_YC_AWADDR_C,
      ST_WAIT5,
      ST_REG36,
      ST_REG37,
      ST_REG38,
      ST_REG39,
      s8,
      ST_REG40,
      ST_REG41,
      ST_REG42,
      ST_REG43,
      ST_REG44,
      ST_REG45,
      ST_REG46,
      ST_REG47,
      s9,
      ST_REG48,
      ST_REG49,
      ST_REG50,
      ST_REG51,
      ST_WAIT_C,
      ST_YC_AWADDR_D,
      ST_WAIT6,
      ST_REG52,
      ST_REG53,
      ST_REG54,
      ST_REG55,
      s10,
      ST_REG56,
      ST_REG57,
      ST_WAIT_D
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(16 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(16 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_REG13 : std_logic;
   SIGNAL csm1_to_ST_REG14 : std_logic;
   SIGNAL csm1_to_ST_REG15 : std_logic;
   SIGNAL csm1_to_ST_REG16 : std_logic;
   SIGNAL csm1_to_ST_REG17 : std_logic;
   SIGNAL csm1_to_ST_REG18 : std_logic;
   SIGNAL csm1_to_ST_REG19 : std_logic;
   SIGNAL csm1_to_ST_REG20 : std_logic;
   SIGNAL csm1_to_ST_REG21 : std_logic;
   SIGNAL csm1_to_ST_REG22 : std_logic;
   SIGNAL csm1_to_ST_REG23 : std_logic;
   SIGNAL csm1_to_ST_REG24 : std_logic;
   SIGNAL csm1_to_ST_REG25 : std_logic;
   SIGNAL csm1_to_ST_REG26 : std_logic;
   SIGNAL csm1_to_ST_REG27 : std_logic;
   SIGNAL csm1_to_ST_REG28 : std_logic;
   SIGNAL csm1_to_ST_REG29 : std_logic;
   SIGNAL csm1_to_ST_REG30 : std_logic;
   SIGNAL csm1_to_ST_REG31 : std_logic;
   SIGNAL csm1_to_ST_REG32 : std_logic;
   SIGNAL csm1_to_ST_REG33 : std_logic;
   SIGNAL csm1_to_ST_REG34 : std_logic;
   SIGNAL csm1_to_ST_REG35 : std_logic;
   SIGNAL csm1_to_ST_WAIT_A : std_logic;
   SIGNAL csm1_to_ST_YC_AWADDR_A : std_logic;
   SIGNAL csm1_to_ST_WAIT_B : std_logic;
   SIGNAL csm1_to_ST_YC_AWADDR_B : std_logic;
   SIGNAL csm1_to_ST_YC_WAIT : std_logic;
   SIGNAL csm1_to_ST_YC_AWADDR_C : std_logic;
   SIGNAL csm1_to_ST_REG36 : std_logic;
   SIGNAL csm1_to_ST_REG37 : std_logic;
   SIGNAL csm1_to_ST_REG38 : std_logic;
   SIGNAL csm1_to_ST_REG39 : std_logic;
   SIGNAL csm1_to_ST_REG40 : std_logic;
   SIGNAL csm1_to_ST_REG41 : std_logic;
   SIGNAL csm1_to_ST_REG42 : std_logic;
   SIGNAL csm1_to_ST_REG43 : std_logic;
   SIGNAL csm1_to_ST_REG44 : std_logic;
   SIGNAL csm1_to_ST_REG45 : std_logic;
   SIGNAL csm1_to_ST_REG46 : std_logic;
   SIGNAL csm1_to_ST_REG47 : std_logic;
   SIGNAL csm1_to_ST_REG48 : std_logic;
   SIGNAL csm1_to_ST_REG49 : std_logic;
   SIGNAL csm1_to_ST_REG50 : std_logic;
   SIGNAL csm1_to_ST_REG51 : std_logic;
   SIGNAL csm1_to_ST_WAIT_C : std_logic;
   SIGNAL csm1_to_ST_YC_AWADDR_D : std_logic;
   SIGNAL csm1_to_ST_REG52 : std_logic;
   SIGNAL csm1_to_ST_REG53 : std_logic;
   SIGNAL csm1_to_ST_REG54 : std_logic;
   SIGNAL csm1_to_ST_REG55 : std_logic;
   SIGNAL csm1_to_ST_REG56 : std_logic;
   SIGNAL csm1_to_ST_REG57 : std_logic;
   SIGNAL csm1_to_ST_WAIT_D : std_logic;


   -- Internal signal declarations
   SIGNAL Heart_Cnt       : std_logic_vector(11 DOWNTO 0);
   SIGNAL REGA_OUT_NUM_M1 : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGB_OUT_NUM_M1 : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_KY          : std_logic_vector(7 DOWNTO 0);
   SIGNAL REG_KY0         : std_logic;
   SIGNAL REG_KY1         : std_logic;
   SIGNAL REG_KY2         : std_logic;
   SIGNAL REG_KY43        : std_logic_vector(1 DOWNTO 0);
   SIGNAL REG_KY65        : std_logic_vector(1 DOWNTO 0);
   SIGNAL REG_KY7         : std_logic;
   SIGNAL WVALID_b        : std_logic;


attribute fsm_safe_state : string;
attribute fsm_safe_state of State_c : signal is "default_state";


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      AWREADY,
      State_c,
      WREADY,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_REG13 <= '0';
      csm1_to_ST_REG14 <= '0';
      csm1_to_ST_REG15 <= '0';
      csm1_to_ST_REG16 <= '0';
      csm1_to_ST_REG17 <= '0';
      csm1_to_ST_REG18 <= '0';
      csm1_to_ST_REG19 <= '0';
      csm1_to_ST_REG20 <= '0';
      csm1_to_ST_REG21 <= '0';
      csm1_to_ST_REG22 <= '0';
      csm1_to_ST_REG23 <= '0';
      csm1_to_ST_REG24 <= '0';
      csm1_to_ST_REG25 <= '0';
      csm1_to_ST_REG26 <= '0';
      csm1_to_ST_REG27 <= '0';
      csm1_to_ST_REG28 <= '0';
      csm1_to_ST_REG29 <= '0';
      csm1_to_ST_REG30 <= '0';
      csm1_to_ST_REG31 <= '0';
      csm1_to_ST_REG32 <= '0';
      csm1_to_ST_REG33 <= '0';
      csm1_to_ST_REG34 <= '0';
      csm1_to_ST_REG35 <= '0';
      csm1_to_ST_WAIT_A <= '0';
      csm1_to_ST_YC_AWADDR_A <= '0';
      csm1_to_ST_WAIT_B <= '0';
      csm1_to_ST_YC_AWADDR_B <= '0';
      csm1_to_ST_YC_WAIT <= '0';
      csm1_to_ST_YC_AWADDR_C <= '0';
      csm1_to_ST_REG36 <= '0';
      csm1_to_ST_REG37 <= '0';
      csm1_to_ST_REG38 <= '0';
      csm1_to_ST_REG39 <= '0';
      csm1_to_ST_REG40 <= '0';
      csm1_to_ST_REG41 <= '0';
      csm1_to_ST_REG42 <= '0';
      csm1_to_ST_REG43 <= '0';
      csm1_to_ST_REG44 <= '0';
      csm1_to_ST_REG45 <= '0';
      csm1_to_ST_REG46 <= '0';
      csm1_to_ST_REG47 <= '0';
      csm1_to_ST_REG48 <= '0';
      csm1_to_ST_REG49 <= '0';
      csm1_to_ST_REG50 <= '0';
      csm1_to_ST_REG51 <= '0';
      csm1_to_ST_WAIT_C <= '0';
      csm1_to_ST_YC_AWADDR_D <= '0';
      csm1_to_ST_REG52 <= '0';
      csm1_to_ST_REG53 <= '0';
      csm1_to_ST_REG54 <= '0';
      csm1_to_ST_REG55 <= '0';
      csm1_to_ST_REG56 <= '0';
      csm1_to_ST_REG57 <= '0';
      csm1_to_ST_WAIT_D <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            State_n <= ST_YC_WAIT;
            csm1_to_ST_YC_WAIT <= '1';
         WHEN ST_REG13 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG14;
               csm1_to_ST_REG14 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG13;
            END IF;
         WHEN ST_REG14 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG15;
               csm1_to_ST_REG15 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG14;
            END IF;
         WHEN ST_REG15 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG16;
               csm1_to_ST_REG16 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG15;
            END IF;
         WHEN ST_REG16 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG17;
               csm1_to_ST_REG17 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG16;
            END IF;
         WHEN ST_REG17 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG18;
               csm1_to_ST_REG18 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG17;
            END IF;
         WHEN ST_REG18 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG19;
               csm1_to_ST_REG19 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG18;
            END IF;
         WHEN ST_REG19 => 
            IF (WREADY='1') THEN 
               State_n <= ST_WAIT_A;
               csm1_to_ST_WAIT_A <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s5;
            ELSE
               State_n <= ST_REG19;
            END IF;
         WHEN ST_REG20 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG21;
               csm1_to_ST_REG21 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG20;
            END IF;
         WHEN ST_REG21 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG22;
               csm1_to_ST_REG22 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG21;
            END IF;
         WHEN ST_REG22 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG23;
               csm1_to_ST_REG23 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG22;
            END IF;
         WHEN ST_REG23 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG24;
               csm1_to_ST_REG24 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG23;
            END IF;
         WHEN ST_REG24 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG25;
               csm1_to_ST_REG25 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG24;
            END IF;
         WHEN ST_REG25 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG26;
               csm1_to_ST_REG26 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG25;
            END IF;
         WHEN ST_REG26 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG27;
               csm1_to_ST_REG27 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG26;
            END IF;
         WHEN ST_REG27 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG28;
               csm1_to_ST_REG28 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s6;
            ELSE
               State_n <= ST_REG27;
            END IF;
         WHEN ST_REG28 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG29;
               csm1_to_ST_REG29 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG28;
            END IF;
         WHEN ST_REG29 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG30;
               csm1_to_ST_REG30 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG29;
            END IF;
         WHEN ST_REG30 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG31;
               csm1_to_ST_REG31 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG30;
            END IF;
         WHEN ST_REG31 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG32;
               csm1_to_ST_REG32 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG31;
            END IF;
         WHEN ST_REG32 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG33;
               csm1_to_ST_REG33 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG32;
            END IF;
         WHEN ST_REG33 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG34;
               csm1_to_ST_REG34 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG33;
            END IF;
         WHEN ST_REG34 => 
            IF (WREADY='1') THEN 
               State_n <= ST_REG35;
               csm1_to_ST_REG35 <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG34;
            END IF;
         WHEN ST_REG35 => 
            IF (WREADY='1') THEN 
               State_n <= ST_WAIT_B;
               csm1_to_ST_WAIT_B <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= s7;
            ELSE
               State_n <= ST_REG35;
            END IF;
         WHEN ST_WAIT_A => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_YC_AWADDR_B;
               csm1_to_ST_YC_AWADDR_B <= '1';
            ELSE
               State_n <= ST_WAIT_A;
            END IF;
         WHEN ST_WAIT3 => 
            State_n <= ST_REG13;
            csm1_to_ST_REG13 <= '1';
         WHEN ST_YC_AWADDR_A => 
            IF (AWREADY='1') THEN 
               State_n <= ST_WAIT3;
            ELSE
               State_n <= ST_YC_AWADDR_A;
            END IF;
         WHEN ST_WAIT4 => 
            State_n <= ST_REG20;
            csm1_to_ST_REG20 <= '1';
         WHEN ST_WAIT_B => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_YC_AWADDR_C;
               csm1_to_ST_YC_AWADDR_C <= '1';
            ELSE
               State_n <= ST_WAIT_B;
            END IF;
         WHEN ST_YC_AWADDR_B => 
            IF (AWREADY='1') THEN 
               State_n <= ST_WAIT4;
            ELSE
               State_n <= ST_YC_AWADDR_B;
            END IF;
         WHEN s5 => 
            State_n <= ST_IDLE;
         WHEN s6 => 
            State_n <= ST_IDLE;
         WHEN s7 => 
            State_n <= s6;
         WHEN ST_YC_WAIT => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_YC_AWADDR_A;
               csm1_to_ST_YC_AWADDR_A <= '1';
            ELSE
               State_n <= ST_YC_WAIT;
            END IF;
         WHEN ST_YC_AWADDR_C => 
            IF (AWREADY='1') THEN 
               State_n <= ST_WAIT5;
            ELSE
               State_n <= ST_YC_AWADDR_C;
            END IF;
         WHEN ST_WAIT5 => 
            State_n <= ST_REG36;
            csm1_to_ST_REG36 <= '1';
         WHEN ST_REG36 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG37;
               csm1_to_ST_REG37 <= '1';
            ELSE
               State_n <= ST_REG36;
            END IF;
         WHEN ST_REG37 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG38;
               csm1_to_ST_REG38 <= '1';
            ELSE
               State_n <= ST_REG37;
            END IF;
         WHEN ST_REG38 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG39;
               csm1_to_ST_REG39 <= '1';
            ELSE
               State_n <= ST_REG38;
            END IF;
         WHEN ST_REG39 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG40;
               csm1_to_ST_REG40 <= '1';
            ELSE
               State_n <= ST_REG39;
            END IF;
         WHEN s8 => 
            State_n <= ST_IDLE;
         WHEN ST_REG40 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG41;
               csm1_to_ST_REG41 <= '1';
            ELSE
               State_n <= ST_REG40;
            END IF;
         WHEN ST_REG41 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG42;
               csm1_to_ST_REG42 <= '1';
            ELSE
               State_n <= ST_REG41;
            END IF;
         WHEN ST_REG42 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG43;
               csm1_to_ST_REG43 <= '1';
            ELSE
               State_n <= ST_REG42;
            END IF;
         WHEN ST_REG43 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s8;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG44;
               csm1_to_ST_REG44 <= '1';
            ELSE
               State_n <= ST_REG43;
            END IF;
         WHEN ST_REG44 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG45;
               csm1_to_ST_REG45 <= '1';
            ELSE
               State_n <= ST_REG44;
            END IF;
         WHEN ST_REG45 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG46;
               csm1_to_ST_REG46 <= '1';
            ELSE
               State_n <= ST_REG45;
            END IF;
         WHEN ST_REG46 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG47;
               csm1_to_ST_REG47 <= '1';
            ELSE
               State_n <= ST_REG46;
            END IF;
         WHEN ST_REG47 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG48;
               csm1_to_ST_REG48 <= '1';
            ELSE
               State_n <= ST_REG47;
            END IF;
         WHEN s9 => 
            State_n <= s8;
         WHEN ST_REG48 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG49;
               csm1_to_ST_REG49 <= '1';
            ELSE
               State_n <= ST_REG48;
            END IF;
         WHEN ST_REG49 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG50;
               csm1_to_ST_REG50 <= '1';
            ELSE
               State_n <= ST_REG49;
            END IF;
         WHEN ST_REG50 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG51;
               csm1_to_ST_REG51 <= '1';
            ELSE
               State_n <= ST_REG50;
            END IF;
         WHEN ST_REG51 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s9;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_WAIT_C;
               csm1_to_ST_WAIT_C <= '1';
            ELSE
               State_n <= ST_REG51;
            END IF;
         WHEN ST_WAIT_C => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_YC_AWADDR_D;
               csm1_to_ST_YC_AWADDR_D <= '1';
            ELSE
               State_n <= ST_WAIT_C;
            END IF;
         WHEN ST_YC_AWADDR_D => 
            IF (AWREADY='1') THEN 
               State_n <= ST_WAIT6;
            ELSE
               State_n <= ST_YC_AWADDR_D;
            END IF;
         WHEN ST_WAIT6 => 
            State_n <= ST_REG52;
            csm1_to_ST_REG52 <= '1';
         WHEN ST_REG52 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG53;
               csm1_to_ST_REG53 <= '1';
            ELSE
               State_n <= ST_REG52;
            END IF;
         WHEN ST_REG53 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG54;
               csm1_to_ST_REG54 <= '1';
            ELSE
               State_n <= ST_REG53;
            END IF;
         WHEN ST_REG54 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG55;
               csm1_to_ST_REG55 <= '1';
            ELSE
               State_n <= ST_REG54;
            END IF;
         WHEN ST_REG55 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG56;
               csm1_to_ST_REG56 <= '1';
            ELSE
               State_n <= ST_REG55;
            END IF;
         WHEN s10 => 
            State_n <= ST_IDLE;
         WHEN ST_REG56 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_REG57;
               csm1_to_ST_REG57 <= '1';
            ELSE
               State_n <= ST_REG56;
            END IF;
         WHEN ST_REG57 => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSIF (WREADY='1') THEN 
               State_n <= ST_WAIT_D;
               csm1_to_ST_WAIT_D <= '1';
            ELSE
               State_n <= ST_REG57;
            END IF;
         WHEN ST_WAIT_D => 
            IF (csm1_timeout = '1') THEN 
               State_n <= s10;
            ELSE
               State_n <= ST_WAIT_D;
            END IF;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_REG13,
      csm1_to_ST_REG14,
      csm1_to_ST_REG15,
      csm1_to_ST_REG16,
      csm1_to_ST_REG17,
      csm1_to_ST_REG18,
      csm1_to_ST_REG19,
      csm1_to_ST_REG20,
      csm1_to_ST_REG21,
      csm1_to_ST_REG22,
      csm1_to_ST_REG23,
      csm1_to_ST_REG24,
      csm1_to_ST_REG25,
      csm1_to_ST_REG26,
      csm1_to_ST_REG27,
      csm1_to_ST_REG28,
      csm1_to_ST_REG29,
      csm1_to_ST_REG30,
      csm1_to_ST_REG31,
      csm1_to_ST_REG32,
      csm1_to_ST_REG33,
      csm1_to_ST_REG34,
      csm1_to_ST_REG35,
      csm1_to_ST_WAIT_A,
      csm1_to_ST_YC_AWADDR_A,
      csm1_to_ST_WAIT_B,
      csm1_to_ST_YC_AWADDR_B,
      csm1_to_ST_YC_WAIT,
      csm1_to_ST_YC_AWADDR_C,
      csm1_to_ST_REG36,
      csm1_to_ST_REG37,
      csm1_to_ST_REG38,
      csm1_to_ST_REG39,
      csm1_to_ST_REG40,
      csm1_to_ST_REG41,
      csm1_to_ST_REG42,
      csm1_to_ST_REG43,
      csm1_to_ST_REG44,
      csm1_to_ST_REG45,
      csm1_to_ST_REG46,
      csm1_to_ST_REG47,
      csm1_to_ST_REG48,
      csm1_to_ST_REG49,
      csm1_to_ST_REG50,
      csm1_to_ST_REG51,
      csm1_to_ST_WAIT_C,
      csm1_to_ST_YC_AWADDR_D,
      csm1_to_ST_REG52,
      csm1_to_ST_REG53,
      csm1_to_ST_REG54,
      csm1_to_ST_REG55,
      csm1_to_ST_REG56,
      csm1_to_ST_REG57,
      csm1_to_ST_WAIT_D
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_REG13 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG14 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG15 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG16 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG17 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG18 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG19 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG20 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG21 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG22 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG23 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG24 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG25 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG26 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG27 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG28 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG29 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG30 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG31 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG32 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG33 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG34 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG35 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_WAIT_A = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_YC_AWADDR_A = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_WAIT_B = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_YC_AWADDR_B = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_YC_WAIT = '1') THEN
         csm1_next_timer <= "11101010010111111"; -- no cycles(120000)-1=119999
      ELSIF (csm1_to_ST_YC_AWADDR_C = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG36 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG37 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG38 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG39 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG40 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG41 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG42 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG43 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG44 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG45 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG46 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG47 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG48 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG49 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG50 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG51 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_WAIT_C = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_YC_AWADDR_D = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG52 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG53 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG54 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG55 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG56 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_REG57 = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSIF (csm1_to_ST_WAIT_D = '1') THEN
         csm1_next_timer <= "00000000000110001"; -- no cycles(50)-1=49
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_KY7 <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_CAP_MODE = X"11") then
   			REG_KY7 <= '1';
   		else
   			REG_KY7 <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_KY65 <= "00";
   	elsif rising_edge(Clk) then
   		if(CMA_Sen_State = X"04") then
   			REG_KY65 <= "01";
   		elsif(CMA_Sen_State = X"11") then
   			REG_KY65 <= "10";
   		else
   			REG_KY65 <= "00";
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_KY43 <= "00";
   	elsif rising_edge(Clk) then
   		if(CMB_Sen_State = X"04") then
   			REG_KY43 <= "01";
   		elsif(CMB_Sen_State = X"11") then
   			REG_KY43 <= "10";
   		else
   			REG_KY43 <= "00";
   		end if;
   	end if;
   end process;
   
   
   process(Clk) begin
   	if rising_edge(Clk) then
   		REG_KY2  <= CMA_POWER and CMB_POWER;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_KY1 <= '0';
   	elsif rising_edge(Clk) then
   		if(Rsp_Start = '1') and (Rsp_State = "00") then
   			REG_KY1 <= not REG_KY1;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Heart_Cnt <= (others => '0');
   		REG_KY0   <= '0';
   	elsif rising_edge(Clk) then
   		if(ClkMs_En = '1') then
   			if(Heart_Cnt = conv_std_logic_vector(999,12)) then
   				Heart_Cnt <= (others => '0');
   				REG_KY0   <= not REG_KY0;
   			else
   				Heart_Cnt <= Heart_Cnt + X"001";
   			end if;
   		end if;
   	end if;
   end process;
   
   
   

   -- HDL Embedded Text Block 4 eb4
   -- eb2 2                                        
   process(State_c) begin
   	
   	if(State_c = ST_YC_AWADDR_A)  then   -- 4  16
   		AWADDR <= X"00";
   		AWLEN  <= X"06";
   		AWVALID <= '1';
   	elsif(State_c = ST_YC_AWADDR_B)  then   -- 20 16
   		AWADDR <= X"07";
   		AWLEN  <= X"0F";
   		AWVALID <= '1';
   	elsif(State_c = ST_YC_AWADDR_C)  then   -- 36 16
   		AWADDR <= X"17";
   		AWLEN  <= X"0F";
   		AWVALID <= '1';
   	elsif(State_c = ST_YC_AWADDR_D)  then   -- 52 6
   		AWADDR <= X"27";
   		AWLEN  <= X"05";
   		AWVALID <= '1';
   	else
   		AWADDR <= X"00";
   		AWLEN  <= X"00";
   		AWVALID <= '0';
   	end if;
   
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		WDATA  <= X"00";
   	elsif rising_edge(Clk) then
   		case State_c is 
   			when ST_REG13   	=> 
   				WDATA  <= REG_KY;
   			when ST_REG14   	=>
   				WDATA  <= REG_VERSION;
   			when ST_REG15		=>
   				WDATA  <= REG_CAP_MODE;
   			when ST_REG16		=> 
   				WDATA  <= REG_ERR(15 downto 8);
   			when ST_REG17		=> 
   				WDATA  <= REG_ERR(7 downto 0);
   			when ST_REG18		=>
   				WDATA  <= REG_CX(15 downto 8);
   			when ST_REG19 =>
   				WDATA  <= REG_CX(7 downto 0);
   			when ST_REG20	=>
   				WDATA  <= REG_CMD_NUM(15 downto 8);
   			when ST_REG21	=>
   				WDATA  <= REG_CMD_NUM(7 downto 0);
   			when ST_REG22	=>
   				WDATA  <= REGA_IN_NUM(15 downto 8);
   			when ST_REG23	=>
   				WDATA  <= REGA_IN_NUM(7 downto 0) ;
   			when ST_REG24	=> 
   				WDATA  <= REGA_OUT_NUM_M1(15 downto 8);
   			when ST_REG25	=>
   				WDATA  <= REGA_OUT_NUM_M1(7 downto 0);
   			when ST_REG26 =>
   				WDATA  <= REG_TASKID;
   			when ST_REG27	=>
   				WDATA  <= REGA_KC_X(15 downto 8);
   			when ST_REG28	=>
   				WDATA  <= REGA_KC_X(7 downto 0);
   			when ST_REG29	=> 
   				WDATA  <= REGA_KC_Y(15 downto 8);
   			when ST_REG30	=> 
   				WDATA  <= REGA_KC_Y(7 downto 0);
   			when ST_REG31  =>
   				if(REGA_CAP_ENABLE = '1') then
   					WDATA <= X"55";
   				else
   					WDATA <= X"00";
   				end if;
   			when ST_REG32  =>
   				WDATA <= REGA_FRAME_FREQ;
   			
   			when ST_REG33  =>
   				WDATA <= REG_OUTPUT_MODE;
   			when ST_REG35	=> 
   				if(REGA_GAIN_MODE = '1') then
   					WDATA <= X"11";
   				else 
   					WDATA  <= X"22";
   				end if;
   			when ST_REG36	=> 
   				WDATA  <= REGA_EXPOTIME(15 downto 8);
   			when ST_REG37	=> 
   				WDATA  <= REGA_EXPOTIME(7 downto 0);
   			when ST_REG38	=> 
   				WDATA  <= REGA_GAIN_VAL;
   			when ST_REG39	=> 
   				WDATA  <= REGA_STATE;
   			when ST_REG40  =>
   				WDATA  <= REGB_IN_NUM(15 downto 8);
   			when ST_REG41  =>
   				WDATA  <= REGB_IN_NUM(7 downto 0);
   			when ST_REG42  =>
   				WDATA  <= REGB_OUT_NUM_M1(15 downto 8);
   			when ST_REG43  =>
   				WDATA  <= REGB_OUT_NUM_M1(7 downto 0);
   			when ST_REG45  =>
   				WDATA  <= REGB_KC_X(15 downto 8);
   			when ST_REG46  =>
   				WDATA  <= REGB_KC_X(7 downto 0);
   				
   			when ST_REG47  =>
   				WDATA  <= REGB_KC_Y(15 downto 8);
   			when ST_REG48  =>
   				WDATA  <= REGB_KC_Y(7 downto 0);
   			when ST_REG49  =>
   				if(REGB_CAP_ENABLE = '1') then
   					WDATA <= X"55";
   				else
   					WDATA <= X"00";
   				end if;
   			when ST_REG50  =>
   				WDATA <= REGB_FRAME_FREQ;
   				
   			when ST_REG51  =>
   				if(CMA_POWER = '1') then
   					WDATA <= X"11";
   				else
   					WDATA <= X"00";
   				end if;
   			when ST_REG52  =>
   				if(CMB_POWER = '1') then
   					WDATA <= X"11";
   				else
   					WDATA <= X"00";
   				end if;
   			when ST_REG53	=> 
   				if(REGB_GAIN_MODE = '1') then
   					WDATA <= X"11";
   				else 
   					WDATA  <= X"22";
   				end if;
   			when ST_REG54	=> 
   				WDATA  <= REGB_EXPOTIME(15 downto 8);
   			when ST_REG55	=> 
   				WDATA  <= REGB_EXPOTIME(7 downto 0);
   			when ST_REG56	=> 
   				WDATA  <= REGB_GAIN_VAL;
   			when ST_REG57	=> 
   				WDATA  <= REGB_STATE;
   								
   			when others =>
   				WDATA  <= X"00";
   		end case;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		WVALID_b <= '0';
   	elsif rising_edge(Clk) then
   		case State_c is 
   			when ST_REG13 =>
   				WVALID_b <= '1';
   			when ST_REG20 =>
   				WVALID_b <= '1';
   			when ST_REG36 =>
   				WVALID_b <= '1';
   			when ST_REG52 =>
   				WVALID_b <= '1';
   			--
   			when ST_WAIT_A =>
   				WVALID_b <= '0';
   			when ST_WAIT_B =>
   				WVALID_b <= '0';
   			when ST_WAIT_C =>
   				WVALID_b <= '0';
   			when ST_WAIT_D =>
   				WVALID_b <= '0';
   			when others =>
   				WVALID_b <= WVALID_b;
   		end case;
   	end if;
   end process;
   
   WVALID <= WVALID_b;
   
   
      process(Reset, Clk) begin
      	if(Reset = '1') then
      		WLAST <= '0';
      	elsif rising_edge(Clk) then
      		case State_c is
      			when ST_REG19 =>
      				WLAST <= '1';
      			when ST_REG35 =>
      				WLAST <= '1';
      			when ST_REG51 =>
      				WLAST <= '1';
      			when ST_REG57 =>
      				WLAST <= '1';
      			when others =>
      				WLAST <= '0';
      		end case;
      	end if;
      end process;
   
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_OUT_NUM_M1 <= (others => '0');
   		REGB_OUT_NUM_M1 <= (others => '0');
   	elsif rising_edge(Clk) then
   		REGA_OUT_NUM_M1 <= REGA_OUT_NUM + X"0001";
   		REGB_OUT_NUM_M1 <= REGB_OUT_NUM + X"0001";
   	end if;
   end process;
   
   


   -- ModuleWare code(v1.9) for instance 'U_0' of 'merge'
   REG_KY <= REG_KY7 & REG_KY65 & REG_KY43 & REG_KY2 & REG_KY1 & REG_KY0;

   -- Instance port mappings.

END struct;
