-- VHDL Entity JWXJ.JWXJ_TOP_C250322.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 15:33:18 2025/03/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY JWXJ_TOP_C250322 IS
   PORT( 
      Clk         : IN     std_logic;
      Clk25M      : IN     std_logic;
      KC_En       : IN     std_logic;
      OPT_B_Clk   : IN     std_logic;
      OPT_B_Reset : IN     std_logic;
      OPT_Z_Clk   : IN     std_logic;
      OPT_Z_Reset : IN     std_logic;
      Reset       : IN     std_logic;
      Reset25M    : IN     std_logic;
      Start       : IN     std_logic;
      GTX_B_Dout  : OUT    std_logic_vector (15 DOWNTO 0);
      GTX_B_Kout  : OUT    std_logic_vector (1 DOWNTO 0);
      GTX_Z_Dout  : OUT    std_logic_vector (15 DOWNTO 0);
      GTX_Z_Kout  : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END JWXJ_TOP_C250322 ;

--
-- VHDL Architecture JWXJ.JWXJ_TOP_C250322.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 15:33:18 2025/03/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF JWXJ_TOP_C250322 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BING_TDATA            : std_logic_vector(15 DOWNTO 0);
   SIGNAL BING_TLAST            : std_logic;
   SIGNAL BING_TUSER            : std_logic;
   SIGNAL BING_TVALID           : std_logic;
   SIGNAL B_Req                 : std_logic;
   SIGNAL D_TDATA               : std_logic_vector(15 DOWNTO 0);
   SIGNAL D_TLAST               : std_logic;
   SIGNAL D_TUSER               : std_logic;
   SIGNAL D_TVALID              : std_logic;
   SIGNAL DinA                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinB                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinC                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinD                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinE                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinF                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinG                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinH                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL FOP                   : std_logic;
   SIGNAL FOP_Reset             : std_logic;
   SIGNAL GTXFIFO_B_Dout        : std_logic_vector(16 DOWNTO 0);
   SIGNAL GTXFIFO_B_Empty       : std_logic;
   SIGNAL GTXFIFO_B_Full        : std_logic;
   SIGNAL GTXFIFO_B_Rd          : std_logic;
   SIGNAL GTXFIFO_B_rd_rst_busy : std_logic;
   SIGNAL GTXFIFO_Z_Dout        : std_logic_vector(16 DOWNTO 0);
   SIGNAL GTXFIFO_Z_Empty       : std_logic;
   SIGNAL GTXFIFO_Z_Full        : std_logic;
   SIGNAL GTXFIFO_Z_Rd          : std_logic;
   SIGNAL GTXFIFO_Z_rd_rst_busy : std_logic;
   SIGNAL KC_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL KC_Vout               : std_logic;
   SIGNAL LS                    : std_logic_vector(15 DOWNTO 0);
   SIGNAL M_TDATA               : std_logic_vector(11 DOWNTO 0);
   SIGNAL M_TLAST               : std_logic;
   SIGNAL M_TUSER               : std_logic;
   SIGNAL M_TVALID              : std_logic;
   SIGNAL QZ_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL QZ_TDATA              : std_logic_vector(15 DOWNTO 0);
   SIGNAL QZ_TLAST              : std_logic;
   SIGNAL QZ_TUSER              : std_logic_vector(1 DOWNTO 0);
   SIGNAL QZ_TVALID             : std_logic;
   SIGNAL QZ_Vout               : std_logic;
   SIGNAL REG_BASE_TIME         : std_logic_vector(63 DOWNTO 0);
   SIGNAL REG_TIME              : std_logic_vector(63 DOWNTO 0);
   SIGNAL RG_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL RG_Vout               : std_logic;
   SIGNAL Reset25M_n            : std_logic;
   SIGNAL SOP                   : std_logic;
   SIGNAL Self_Sync_Rx          : STD_LOGIC;
   SIGNAL TASKID                : std_logic_vector(16 DOWNTO 0);
   SIGNAL TDATA                 : std_logic_vector(11 DOWNTO 0);
   SIGNAL VERSION               : std_logic_vector(3 DOWNTO 0);
   SIGNAL W_TDATA               : std_logic_vector(15 DOWNTO 0);
   SIGNAL W_TLAST               : std_logic;
   SIGNAL W_TUSER               : std_logic_vector(1 DOWNTO 0);
   SIGNAL W_TVALID              : std_logic;
   SIGNAL X                     : std_logic_vector(11 DOWNTO 0);
   SIGNAL Y                     : std_logic_vector(11 DOWNTO 0);
   SIGNAL Z_Req                 : std_logic;
   SIGNAL dout                  : std_logic;
   SIGNAL dout1                 : std_logic;
   SIGNAL dout2                 : std_logic;
   SIGNAL dout3                 : std_logic;
   SIGNAL dout4                 : std_logic;
   SIGNAL dout5                 : std_logic;
   SIGNAL dout6                 : std_logic;
   SIGNAL dout7                 : std_logic_vector(3 DOWNTO 0);


attribute keep: string;

attribute keep of QZ_TDATA: signal is "true";
attribute keep of QZ_TVALID: signal is "true";
attribute keep of QZ_TLAST: signal is "true";

   -- Component Declarations
   COMPONENT AXI2GTX_C250324
   GENERIC (
      CHA_LABEL : std_logic_vector(7 downto 0) := X"33"
   );
   PORT (
      Clk           : IN     std_logic ;
      REG_BASE_TIME : IN     std_logic_vector (63 DOWNTO 0);
      REG_TIME      : IN     std_logic_vector (63 DOWNTO 0);
      Reset         : IN     std_logic ;
      TASKID        : IN     std_logic_vector (16 DOWNTO 0);
      TDATA         : IN     std_logic_vector (15 DOWNTO 0);
      TLAST         : IN     std_logic ;
      TUSER         : IN     std_logic_vector (1 DOWNTO 0);
      TVALID        : IN     std_logic ;
      VERSION       : IN     std_logic_vector (3 DOWNTO 0);
      RG_Dout       : OUT    std_logic_vector (16 DOWNTO 0);
      RG_Vout       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BASIC_SEND_C220509
   PORT (
      Clk        : IN     std_logic ;
      FIFO_Din   : IN     std_logic_vector (16 DOWNTO 0);
      FIFO_Empty : IN     std_logic ;
      LS         : IN     std_logic_vector (15 DOWNTO 0);
      Req        : IN     std_logic ;
      Reset      : IN     std_logic ;
      Dout       : OUT    std_logic_vector (15 DOWNTO 0);
      FIFO_Rd    : OUT    std_logic ;
      Kout       : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT BING
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (11 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic ;
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BorderProcess
   PORT (
      Clk       : IN     std_logic ;
      GReset    : IN     std_logic ;
      S_TDATA   : IN     std_logic_vector (11 DOWNTO 0);
      S_TLAST   : IN     std_logic ;
      S_TUSER   : IN     std_logic_vector (1 DOWNTO 0);
      S_TVALID  : IN     std_logic ;
      FOP_Reset : OUT    std_logic ;
      M_TDATA   : OUT    std_logic_vector (11 DOWNTO 0);
      M_TLAST   : OUT    std_logic ;
      M_TUSER   : OUT    std_logic ;
      M_TVALID  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DownSample
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic ;
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FrameCtrl
   PORT (
      Clk   : IN     std_logic ;
      Reset : IN     std_logic ;
      Start : IN     std_logic ;
      FOP   : OUT    std_logic ;
      SOP   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FrameGenPingPang_C250322
   PORT (
      Clk100M   : IN     std_logic ;
      Clk25M    : IN     std_logic ;
      DinA      : IN     std_logic_vector (11 DOWNTO 0);
      DinB      : IN     std_logic_vector (11 DOWNTO 0);
      DinC      : IN     std_logic_vector (11 DOWNTO 0);
      DinD      : IN     std_logic_vector (11 DOWNTO 0);
      DinE      : IN     std_logic_vector (11 DOWNTO 0);
      DinF      : IN     std_logic_vector (11 DOWNTO 0);
      DinG      : IN     std_logic_vector (11 DOWNTO 0);
      DinH      : IN     std_logic_vector (11 DOWNTO 0);
      FOP       : IN     std_logic ;
      REG_H     : IN     std_logic ;
      Reset100M : IN     std_logic ;
      Reset25M  : IN     std_logic ;
      SOP       : IN     std_logic ;
      TDATA     : OUT    std_logic_vector (11 DOWNTO 0);
      TLAST     : OUT    std_logic ;
      TUSER     : OUT    std_logic_vector (1 DOWNTO 0);
      TVALID    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT GTX_FIFO
   PORT (
      din         : IN     std_logic_vector (16 DOWNTO 0);
      rd_clk      : IN     std_logic;
      rd_en       : IN     std_logic;
      rst         : IN     std_logic;
      wr_clk      : IN     std_logic;
      wr_en       : IN     std_logic;
      dout        : OUT    std_logic_vector (16 DOWNTO 0);
      empty       : OUT    std_logic;
      full        : OUT    std_logic;
      rd_rst_busy : OUT    std_logic;
      wr_rst_busy : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT IMA_GEN_G400B
   PORT (
      Clk_Ref        : IN     STD_LOGIC;
      Cmd_Check2     : IN     STD_LOGIC;
      Rst_Ref        : IN     STD_LOGIC;
      Frame_Circle_S : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);
      Self_Image_Out : OUT    STD_LOGIC;
      Self_Par_Chan1 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan2 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan3 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan4 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan5 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan6 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan7 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Par_Chan8 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);
      Self_Sync_Rx   : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Window
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      X        : IN     std_logic_vector (11 DOWNTO 0);
      Y        : IN     std_logic_vector (11 DOWNTO 0);
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic_vector (1 DOWNTO 0);
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AXI2GTX_C250324 USE ENTITY JWXJ.AXI2GTX_C250324;
   FOR ALL : BASIC_SEND_C220509 USE ENTITY JWXJ.BASIC_SEND_C220509;
   FOR ALL : BING USE ENTITY JWXJ.BING;
   FOR ALL : BorderProcess USE ENTITY JWXJ.BorderProcess;
   FOR ALL : DownSample USE ENTITY JWXJ.DownSample;
   FOR ALL : FrameCtrl USE ENTITY JWXJ.FrameCtrl;
   FOR ALL : FrameGenPingPang_C250322 USE ENTITY JWXJ.FrameGenPingPang_C250322;
   FOR ALL : IMA_GEN_G400B USE ENTITY JWXJ.IMA_GEN_G400B;
   FOR ALL : Window USE ENTITY JWXJ.Window;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_9' of 'and'
   dout2 <= RG_Vout AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'and'
   dout5 <= RG_Vout AND dout3;

   -- ModuleWare code(v1.9) for instance 'U_18' of 'constval'
   LS <= "0000000000101000";

   -- ModuleWare code(v1.9) for instance 'U_24' of 'constval'
   X <= "001100100000";

   -- ModuleWare code(v1.9) for instance 'U_25' of 'constval'
   Y <= "000000000011";

   -- ModuleWare code(v1.9) for instance 'U_8' of 'gnd'
   VERSION <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_15' of 'gnd'
   TASKID <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_16' of 'gnd'
   REG_BASE_TIME <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_17' of 'gnd'
   REG_TIME <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_31' of 'gnd'
   dout7 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_10' of 'inv'
   dout1 <= NOT(GTXFIFO_Z_Full);

   -- ModuleWare code(v1.9) for instance 'U_12' of 'inv'
   Z_Req <= NOT(GTXFIFO_Z_Empty);

   -- ModuleWare code(v1.9) for instance 'U_19' of 'inv'
   Reset25M_n <= NOT(Reset25M);

   -- ModuleWare code(v1.9) for instance 'U_21' of 'inv'
   B_Req <= NOT(GTXFIFO_B_Empty);

   -- ModuleWare code(v1.9) for instance 'U_23' of 'inv'
   dout3 <= NOT(GTXFIFO_B_Full);

   -- ModuleWare code(v1.9) for instance 'U_30' of 'merge'
   QZ_TDATA <= dout7 & TDATA;

   -- ModuleWare code(v1.9) for instance 'U_28' of 'mux'
   u_28combo_proc: PROCESS(QZ_Dout, KC_Dout, KC_En)
   BEGIN
      CASE KC_En IS
      WHEN '0' => RG_Dout <= QZ_Dout;
      WHEN '1' => RG_Dout <= KC_Dout;
      WHEN OTHERS => RG_Dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_28combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_29' of 'mux'
   u_29combo_proc: PROCESS(QZ_Vout, KC_Vout, KC_En)
   BEGIN
      CASE KC_En IS
      WHEN '0' => RG_Vout <= QZ_Vout;
      WHEN '1' => RG_Vout <= KC_Vout;
      WHEN OTHERS => RG_Vout <= 'X';
      END CASE;
   END PROCESS u_29combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_92' of 'or'
   dout4 <= GTXFIFO_Z_rd_rst_busy OR OPT_Z_Reset;

   -- ModuleWare code(v1.9) for instance 'U_93' of 'or'
   dout6 <= GTXFIFO_B_rd_rst_busy OR OPT_B_Reset;

   -- ModuleWare code(v1.9) for instance 'U_26' of 'vdd'
   dout <= '1';

   -- Instance port mappings.
   U_14 : AXI2GTX_C250324
      GENERIC MAP (
         CHA_LABEL => X"33"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => Reset,
         TASKID        => TASKID,
         TDATA         => W_TDATA,
         TLAST         => W_TLAST,
         TUSER         => W_TUSER,
         TVALID        => W_TVALID,
         VERSION       => VERSION,
         RG_Dout       => KC_Dout,
         RG_Vout       => KC_Vout
      );
   U_27 : AXI2GTX_C250324
      GENERIC MAP (
         CHA_LABEL => X"55"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => Reset,
         TASKID        => TASKID,
         TDATA         => QZ_TDATA,
         TLAST         => QZ_TLAST,
         TUSER         => QZ_TUSER,
         TVALID        => QZ_TVALID,
         VERSION       => VERSION,
         RG_Dout       => QZ_Dout,
         RG_Vout       => QZ_Vout
      );
   U_11 : BASIC_SEND_C220509
      PORT MAP (
         Clk        => OPT_Z_Clk,
         FIFO_Din   => GTXFIFO_Z_Dout,
         FIFO_Empty => GTXFIFO_Z_Empty,
         LS         => LS,
         Req        => Z_Req,
         Reset      => dout4,
         Dout       => GTX_Z_Dout,
         FIFO_Rd    => GTXFIFO_Z_Rd,
         Kout       => GTX_Z_Kout
      );
   U_13 : BASIC_SEND_C220509
      PORT MAP (
         Clk        => OPT_B_Clk,
         FIFO_Din   => GTXFIFO_B_Dout,
         FIFO_Empty => GTXFIFO_B_Empty,
         LS         => LS,
         Req        => B_Req,
         Reset      => dout6,
         Dout       => GTX_B_Dout,
         FIFO_Rd    => GTXFIFO_B_Rd,
         Kout       => GTX_B_Kout
      );
   U_3 : BING
      PORT MAP (
         Clk      => Clk,
         FOP      => FOP_Reset,
         GReset   => Reset,
         S_TDATA  => M_TDATA,
         S_TLAST  => M_TLAST,
         S_TUSER  => M_TUSER,
         S_TVALID => M_TVALID,
         M_TDATA  => BING_TDATA,
         M_TLAST  => BING_TLAST,
         M_TUSER  => BING_TUSER,
         M_TVALID => BING_TVALID
      );
   U_2 : BorderProcess
      PORT MAP (
         Clk       => Clk,
         GReset    => Reset,
         S_TDATA   => TDATA,
         S_TLAST   => QZ_TLAST,
         S_TUSER   => QZ_TUSER,
         S_TVALID  => QZ_TVALID,
         FOP_Reset => FOP_Reset,
         M_TDATA   => M_TDATA,
         M_TLAST   => M_TLAST,
         M_TUSER   => M_TUSER,
         M_TVALID  => M_TVALID
      );
   U_5 : DownSample
      PORT MAP (
         Clk      => Clk,
         FOP      => FOP_Reset,
         GReset   => Reset,
         S_TDATA  => BING_TDATA,
         S_TLAST  => BING_TLAST,
         S_TUSER  => BING_TUSER,
         S_TVALID => BING_TVALID,
         M_TDATA  => D_TDATA,
         M_TLAST  => D_TLAST,
         M_TUSER  => D_TUSER,
         M_TVALID => D_TVALID
      );
   U_7 : FrameCtrl
      PORT MAP (
         Clk   => Clk,
         Reset => Reset,
         Start => Start,
         FOP   => FOP,
         SOP   => SOP
      );
   U_1 : FrameGenPingPang_C250322
      PORT MAP (
         Clk100M   => Clk,
         Clk25M    => Clk25M,
         DinA      => DinA,
         DinB      => DinB,
         DinC      => DinC,
         DinD      => DinD,
         DinE      => DinE,
         DinF      => DinF,
         DinG      => DinG,
         DinH      => DinH,
         FOP       => FOP,
         REG_H     => dout,
         Reset100M => Reset,
         Reset25M  => Reset25M,
         SOP       => Self_Sync_Rx,
         TDATA     => TDATA,
         TLAST     => QZ_TLAST,
         TUSER     => QZ_TUSER,
         TVALID    => QZ_TVALID
      );
   U_4 : GTX_FIFO
      PORT MAP (
         rst         => Reset,
         wr_clk      => Clk,
         rd_clk      => OPT_Z_Clk,
         din         => RG_Dout,
         wr_en       => dout2,
         rd_en       => GTXFIFO_Z_Rd,
         dout        => GTXFIFO_Z_Dout,
         full        => GTXFIFO_Z_Full,
         empty       => GTXFIFO_Z_Empty,
         wr_rst_busy => OPEN,
         rd_rst_busy => GTXFIFO_Z_rd_rst_busy
      );
   U_20 : GTX_FIFO
      PORT MAP (
         rst         => Reset,
         wr_clk      => Clk,
         rd_clk      => OPT_B_Clk,
         din         => RG_Dout,
         wr_en       => dout5,
         rd_en       => GTXFIFO_B_Rd,
         dout        => GTXFIFO_B_Dout,
         full        => GTXFIFO_B_Full,
         empty       => GTXFIFO_B_Empty,
         wr_rst_busy => OPEN,
         rd_rst_busy => GTXFIFO_B_rd_rst_busy
      );
   U_0 : IMA_GEN_G400B
      PORT MAP (
         Clk_Ref        => Clk25M,
         Rst_Ref        => Reset25M_n,
         Self_Sync_Rx   => Self_Sync_Rx,
         Self_Image_Out => OPEN,
         Self_Par_Chan1 => DinA,
         Self_Par_Chan2 => DinB,
         Self_Par_Chan3 => DinC,
         Self_Par_Chan4 => DinD,
         Self_Par_Chan5 => DinE,
         Self_Par_Chan6 => DinF,
         Self_Par_Chan7 => DinG,
         Self_Par_Chan8 => DinH,
         Cmd_Check2     => SOP,
         Frame_Circle_S => OPEN
      );
   U_6 : Window
      PORT MAP (
         Clk      => Clk,
         FOP      => FOP_Reset,
         GReset   => Reset,
         S_TDATA  => D_TDATA,
         S_TLAST  => D_TLAST,
         S_TUSER  => D_TUSER,
         S_TVALID => D_TVALID,
         X        => X,
         Y        => Y,
         M_TDATA  => W_TDATA,
         M_TLAST  => W_TLAST,
         M_TUSER  => W_TUSER,
         M_TVALID => W_TVALID
      );

END struct;
