-- VHDL Entity JWXJ.JWXJ_TOP_C250514.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 11:14:21 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY JWXJ_TOP_C250514 IS
   PORT( 
      B_RX_PAD_I         : IN     std_logic;
      CMA_DATA_SER_N     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);   -- the negative LVDS outputs of CMOSA, 8 channels
      CMA_DATA_SER_P     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);   -- the positive LVDS outputs of CMOSA, 8 channels
      CMA_Power_On       : IN     STD_LOGIC;                       -- sensor power supply, 1 power on, 0 power off
      CMA_SPI_OUT        : IN     STD_LOGIC;                       -- CMOSA spi output signal
      CMB_DATA_SER_N     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);
      CMB_DATA_SER_P     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);   -- the positive LVDS outputs of the sensor, 8 channels
      CMB_Power_On       : IN     STD_LOGIC;                       -- sensor power supply, 1 power on, 0 power off
      CMB_SPI_OUT        : IN     STD_LOGIC;                       -- sensor spi output signal
      Clk                : IN     std_logic;
      Clk25M             : IN     std_logic;
      Clk80M             : IN     std_logic;                       -- system clk 80MHz
      ClkMs_En           : IN     std_logic;
      Clk_Ddr            : IN     STD_LOGIC;                       -- cmos sample ddr clk, 150MHz
      OPT_B_Clk          : IN     std_logic;
      OPT_B_Reset        : IN     std_logic;
      OPT_Z_Clk          : IN     std_logic;
      OPT_Z_Reset        : IN     std_logic;
      Reset              : IN     std_logic;
      Reset25M_n         : IN     std_logic;                       -- Clk_Ref correspond rst signal
      Reset80M_n         : IN     std_logic;                       -- Clk_Sys correspond rst signal
      Rst_Ddr_n          : IN     STD_LOGIC;                       -- Clk_Ddr correspond rst signal
      TICK_START         : IN     std_logic;                       --对时脉冲
      UART_Clk           : IN     std_logic;
      UART_ClkEn         : IN     std_logic;
      UART_Reset_n       : IN     std_logic;
      Z_RX_PAD_I         : IN     std_logic;
      B_TX_PAD_O         : OUT    std_logic;
      -- CMA_CLK_REF        : OUT    STD_LOGIC;                       -- CMOSA reference clock
      CMA_HDR            : OUT    STD_LOGIC;
      CMA_Image_Out      : OUT    STD_LOGIC;                       -- pull high when the image's output is valid
      CMA_ROW            : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);  -- CMOSA read and reset addr
      CMA_RS             : OUT    STD_LOGIC;
      CMA_RST            : OUT    STD_LOGIC;
      CMA_SEN_RST_N      : OUT    STD_LOGIC;                       -- the rst of CMOSA, low level valid
      CMA_SPI_CLK        : OUT    STD_LOGIC;                       -- CMOSA spi clk in 20MHz/50ns
      CMA_SPI_IN         : OUT    STD_LOGIC;                       -- CMOSA spi input signal
      CMA_SPI_READ       : OUT    STD_LOGIC;                       -- the enable of reading CMOSA spi
      CMA_SPI_WRITE      : OUT    STD_LOGIC;                       -- the enable of writing CMOSA spi
      CMA_SYNC           : OUT    STD_LOGIC;
      CMA_Self_Image_Out : OUT    STD_LOGIC;                       -- pull high when the image is ready to output
      CMA_Sen_Status     : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);   -- the status of sensor, 00H none, 01H training, 10H shooting
      CMA_Spi_Gain       : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);   -- read spi gain register, odd & even
      CMA_TAB            : OUT    STD_LOGIC;
      CMA_TAC            : OUT    STD_LOGIC;
      CMA_TADR           : OUT    STD_LOGIC;
      CMA_TADS           : OUT    STD_LOGIC;
      CMA_TAZ            : OUT    STD_LOGIC;
      CMA_TBS            : OUT    STD_LOGIC;
      CMA_TINITE         : OUT    STD_LOGIC;
      CMA_TINITO         : OUT    STD_LOGIC;
      CMA_TPC            : OUT    STD_LOGIC;
      CMA_TRAIN          : OUT    STD_LOGIC;
      CMA_TRD            : OUT    STD_LOGIC;
      CMA_TS             : OUT    STD_LOGIC;
      CMA_TSE            : OUT    STD_LOGIC;
      CMA_TSO            : OUT    STD_LOGIC;
      CMA_TWS            : OUT    STD_LOGIC;
      CMA_TX             : OUT    STD_LOGIC;
      -- CMB_CLK_REF        : OUT    STD_LOGIC;                       -- CMOSB reference clock
      CMB_HDR            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_Image_Out      : OUT    STD_LOGIC;                       -- pull high when the image's output is valid
      CMB_ROW            : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);  -- sensor read and reset addr
      CMB_RS             : OUT    STD_LOGIC;                       -- digital control signal
      CMB_RST            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_SEN_RST_N      : OUT    STD_LOGIC;                       -- the rst of sensor, low level valid
      CMB_SPI_CLK        : OUT    STD_LOGIC;                       -- sensor spi clk in 25MHz/50ns
      CMB_SPI_IN         : OUT    STD_LOGIC;                       -- sensor spi input signal
      CMB_SPI_READ       : OUT    STD_LOGIC;                       -- the enable of of reading spi
      CMB_SPI_WRITE      : OUT    STD_LOGIC;                       -- the enable of of writing spi
      CMB_SYNC           : OUT    STD_LOGIC;                       -- digital control signal
      CMB_Self_Image_Out : OUT    STD_LOGIC;                       -- pull high when the image is ready to output
      CMB_Sen_Status     : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);   -- the status of sensor, 00H none, 01H training, 10H shooting
      CMB_Spi_Gain       : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);   -- read spi gain register, odd & even
      CMB_TAB            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TAC            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TADR           : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TADS           : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TAZ            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TBS            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TINITE         : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TINITO         : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TPC            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TRAIN          : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TRD            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TS             : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TSE            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TSO            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TWS            : OUT    STD_LOGIC;                       -- digital control signal
      CMB_TX             : OUT    STD_LOGIC;                       -- digital control signal
      DEBUG_ENG          : OUT    std_logic_vector (9 DOWNTO 0);
      DEBUG_FC           : OUT    std_logic_vector (2 DOWNTO 0);
      DEBUG_TX           : OUT    std_logic_vector (8 DOWNTO 0);
      DEBUG_UART_Dout    : OUT    std_logic_vector (7 DOWNTO 0);
      DEBUG_UART_Valid   : OUT    std_logic;
      D_DinA             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinB             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinC             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinD             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinE             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinF             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinG             : OUT    std_logic_vector (11 DOWNTO 0);
      D_DinH             : OUT    std_logic_vector (11 DOWNTO 0);
      D_FOP_Reset        : OUT    std_logic;
      D_GLOBAL_SOP       : OUT    STD_LOGIC;
      D_QZ               : OUT    std_logic_vector (20 DOWNTO 0);
      D_REG_H_CNT        : OUT    std_logic_vector (15 DOWNTO 0);
      D_RG_Dout          : OUT    std_logic_vector (16 DOWNTO 0);
      D_RG_Vout          : OUT    std_logic;
      Eng_Start          : OUT    std_logic;
      GTX_B_Dout         : OUT    std_logic_vector (15 DOWNTO 0);
      GTX_B_Kout         : OUT    std_logic_vector (1 DOWNTO 0);
      GTX_Z_Dout         : OUT    std_logic_vector (15 DOWNTO 0);
      GTX_Z_Kout         : OUT    std_logic_vector (1 DOWNTO 0);
      REG_FRAME_NUM      : OUT    std_logic_vector (15 DOWNTO 0);
      SUP_EN1            : OUT    STD_LOGIC;                       -- CMOSA supply1
      SUP_EN10           : OUT    STD_LOGIC;                       -- CMOSB supply1
      SUP_EN11           : OUT    STD_LOGIC;                       -- CMOSB supply1
      SUP_EN12           : OUT    STD_LOGIC;                       -- CMOSB supply2
      SUP_EN13           : OUT    STD_LOGIC;                       -- CMOSB supply2
      SUP_EN14           : OUT    STD_LOGIC;                       -- CMOSB supply2
      SUP_EN15           : OUT    STD_LOGIC;                       -- CMOSB supply2
      SUP_EN16           : OUT    STD_LOGIC;                       -- CMOSB supply2
      SUP_EN2            : OUT    STD_LOGIC;                       -- CMOSA supply1
      SUP_EN3            : OUT    STD_LOGIC;                       -- CMOSA supply1
      SUP_EN4            : OUT    STD_LOGIC;                       -- CMOSA supply2
      SUP_EN5            : OUT    STD_LOGIC;                       -- CMOSA supply2
      SUP_EN6            : OUT    STD_LOGIC;                       -- CMOSA supply2
      SUP_EN7            : OUT    STD_LOGIC;                       -- CMOSA supply2
      SUP_EN8            : OUT    STD_LOGIC;                       -- CMOSA supply2
      SUP_EN9            : OUT    STD_LOGIC;                       -- CMOSB supply1
      Z_TX_PAD_O         : OUT    std_logic
   );

-- Declarations

END JWXJ_TOP_C250514 ;

--
-- VHDL Architecture JWXJ.JWXJ_TOP_C250514.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 11:14:26 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;
USE IEEE.NUMERIC_STD.all;
LIBRARY UNISIM;
USE UNISIM.VComponents.all;

LIBRARY JWXJ;
LIBRARY xpm;

ARCHITECTURE struct OF JWXJ_TOP_C250514 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL AWADDR                : std_logic_vector(9 DOWNTO 0);
   SIGNAL AWLEN                 : std_logic_vector(7 DOWNTO 0);
   SIGNAL AWREADY               : std_logic;
   SIGNAL AWVALID               : std_logic;
   SIGNAL BING_TDATA            : std_logic_vector(15 DOWNTO 0);
   SIGNAL BING_TLAST            : std_logic;
   SIGNAL BING_TUSER            : std_logic;
   SIGNAL BING_TVALID           : std_logic;
   SIGNAL BREADY                : std_logic;
   SIGNAL BVALID                : std_logic;
   SIGNAL B_Req                 : std_logic;
   SIGNAL CALIB_MS              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CALIB_NS              : std_logic_vector(19 DOWNTO 0);
   SIGNAL CALIB_SEC             : std_logic_vector(31 DOWNTO 0);
   SIGNAL CB_KC_Dout            : std_logic_vector(15 DOWNTO 0);
   SIGNAL CB_KC_EOP             : std_logic;
   SIGNAL CB_KC_SOP             : std_logic;
   SIGNAL CB_KC_Vout            : std_logic;
   SIGNAL CB_M_TDATA            : std_logic_vector(15 DOWNTO 0);
   SIGNAL CB_M_TLAST            : std_logic;
   SIGNAL CB_M_TUSER            : std_logic_vector(1 DOWNTO 0);
   SIGNAL CB_M_TVALID           : std_logic;
   SIGNAL CB_QZ_TDATA           : std_logic_vector(15 DOWNTO 0);
   SIGNAL CMA_Data_Par_Chan1    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel1 data
   SIGNAL CMA_Data_Par_Chan2    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel2 data
   SIGNAL CMA_Data_Par_Chan3    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel3 data
   SIGNAL CMA_Data_Par_Chan4    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel4 data
   SIGNAL CMA_Data_Par_Chan5    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel5 data
   SIGNAL CMA_Data_Par_Chan6    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel6 data
   SIGNAL CMA_Data_Par_Chan7    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel7 data
   SIGNAL CMA_Data_Par_Chan8    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel8 data
   SIGNAL CMA_FOP               : std_logic;
   SIGNAL CMA_Self_Par_Chan1    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel1 data
   SIGNAL CMA_Self_Par_Chan2    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel2 data
   SIGNAL CMA_Self_Par_Chan3    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel3 data
   SIGNAL CMA_Self_Par_Chan4    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel4 data
   SIGNAL CMA_Self_Par_Chan5    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel5 data
   SIGNAL CMA_Self_Par_Chan6    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel6 data
   SIGNAL CMA_Self_Par_Chan7    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel7 data
   SIGNAL CMA_Self_Par_Chan8    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel8 data
   SIGNAL CMA_Self_Sync_Rx      : STD_LOGIC;                        -- the one clk sync signal of every line
   ---------SENSOR---------
   SIGNAL CMA_Sen_Supply1       : STD_LOGIC;
   SIGNAL CMA_Sen_Supply2       : STD_LOGIC;
   SIGNAL CMA_Shoot_Pulse       : STD_LOGIC;
   SIGNAL CMA_Sync_Rx           : STD_LOGIC;                        -- the one clk sync signal of every line
   SIGNAL CMB_Data_Par_Chan1    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel1 data
   SIGNAL CMB_Data_Par_Chan2    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel2 data
   SIGNAL CMB_Data_Par_Chan3    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel3 data
   SIGNAL CMB_Data_Par_Chan4    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel4 data
   SIGNAL CMB_Data_Par_Chan5    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel5 data
   SIGNAL CMB_Data_Par_Chan6    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel6 data
   SIGNAL CMB_Data_Par_Chan7    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel7 data
   SIGNAL CMB_Data_Par_Chan8    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- training output channel8 data
   SIGNAL CMB_DinA              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinB              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinC              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinD              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinE              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinF              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinG              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_DinH              : std_logic_vector(11 DOWNTO 0);
   SIGNAL CMB_FOP               : std_logic;
   SIGNAL CMB_GLOBAL_SOP        : std_logic;
   SIGNAL CMB_QZ_Data           : std_logic_vector(15 DOWNTO 0);
   SIGNAL CMB_QZ_Dout           : std_logic_vector(16 DOWNTO 0);
   SIGNAL CMB_QZ_EOP            : std_logic;
   SIGNAL CMB_QZ_TDATA          : std_logic_vector(15 DOWNTO 0);
   SIGNAL CMB_QZ_TLAST          : std_logic;
   SIGNAL CMB_QZ_TUSER          : std_logic_vector(1 DOWNTO 0);
   SIGNAL CMB_QZ_TVALID         : std_logic;
   SIGNAL CMB_QZ_Vout           : std_logic;
   SIGNAL CMB_Self_Par_Chan1    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel1 data
   SIGNAL CMB_Self_Par_Chan2    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel2 data
   SIGNAL CMB_Self_Par_Chan3    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel3 data
   SIGNAL CMB_Self_Par_Chan4    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel4 data
   SIGNAL CMB_Self_Par_Chan5    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel5 data
   SIGNAL CMB_Self_Par_Chan6    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel6 data
   SIGNAL CMB_Self_Par_Chan7    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel7 data
   SIGNAL CMB_Self_Par_Chan8    : STD_LOGIC_VECTOR(11 DOWNTO 0);    -- selfcheck output channel8 data
   SIGNAL CMB_Self_Sync_Rx      : STD_LOGIC;                        -- the one clk sync signal of every line
   SIGNAL CMB_Sen_Supply1       : STD_LOGIC;                        -- sensor supply1 signal
   SIGNAL CMB_Sen_Supply2       : STD_LOGIC;                        -- sensor supply2 signal
   SIGNAL CMB_Shoot_Pulse       : STD_LOGIC;
   SIGNAL CMB_Sync_Rx           : STD_LOGIC;                        -- the one clk sync signal of every line
   SIGNAL CMB_TDATA             : std_logic_vector(11 DOWNTO 0);
   SIGNAL DEBUG_TX_Data         : std_logic_vector(7 DOWNTO 0);
   SIGNAL DEBUG_TX_Valid        : std_logic;
   SIGNAL D_FIFOH               : std_logic_vector(2 DOWNTO 0);
   SIGNAL D_TDATA               : std_logic_vector(15 DOWNTO 0);
   SIGNAL D_TLAST               : std_logic;
   SIGNAL D_TUSER               : std_logic;
   SIGNAL D_TVALID              : std_logic;
   SIGNAL DinA                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinB                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinC                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinD                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinE                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinF                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinG                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL DinH                  : std_logic_vector(11 DOWNTO 0);
   SIGNAL ENG_TDATA             : std_logic_vector(7 DOWNTO 0);
   SIGNAL ENG_TLAST             : std_logic;
   SIGNAL ENG_TUSER             : std_logic_vector(7 DOWNTO 0);
   SIGNAL ENG_TVALID            : std_logic;
   SIGNAL Eng_Ack               : std_logic;
   SIGNAL FOP_Reset             : std_logic;
   SIGNAL GLOBAL_SOP            : STD_LOGIC;
   SIGNAL GTXFIFO_B_Dout        : std_logic_vector(16 DOWNTO 0);
   SIGNAL GTXFIFO_B_Empty       : std_logic;
   SIGNAL GTXFIFO_B_Full        : std_logic;
   SIGNAL GTXFIFO_B_Rd          : std_logic;
   SIGNAL GTXFIFO_B_rd_rst_busy : std_logic;
   SIGNAL GTXFIFO_Z_Dout        : std_logic_vector(16 DOWNTO 0);
   SIGNAL GTXFIFO_Z_Empty       : std_logic;
   SIGNAL GTXFIFO_Z_Full        : std_logic;
   SIGNAL GTXFIFO_Z_Rd          : std_logic;
   SIGNAL GTXFIFO_Z_rd_rst_busy : std_logic;
   SIGNAL KC_Dout               : std_logic_vector(15 DOWNTO 0);
   SIGNAL KC_En                 : std_logic_vector(1 DOWNTO 0);
   SIGNAL KC_Eop                : std_logic;
   SIGNAL KC_Sop                : std_logic;
   SIGNAL KC_Vout               : std_logic;
   SIGNAL LS                    : std_logic_vector(15 DOWNTO 0);
   SIGNAL MG_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL MG_Vout               : std_logic;
   SIGNAL M_TDATA               : std_logic_vector(11 DOWNTO 0);
   SIGNAL M_TLAST               : std_logic;
   SIGNAL M_TUSER               : std_logic;
   SIGNAL M_TVALID              : std_logic;
   SIGNAL QZ_Data               : std_logic_vector(15 DOWNTO 0);
   SIGNAL QZ_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL QZ_EOP                : std_logic;
   SIGNAL QZ_TDATA              : std_logic_vector(15 DOWNTO 0);
   SIGNAL QZ_TLAST              : std_logic;
   SIGNAL QZ_TUSER              : std_logic_vector(1 DOWNTO 0);
   SIGNAL QZ_TVALID             : std_logic;
   SIGNAL QZ_Vout               : std_logic;
   SIGNAL REGA_CAP_ENABLE       : std_logic;
   SIGNAL REGA_CAP_START        : std_logic;
   SIGNAL REGA_CAP_STOP         : std_logic;
   SIGNAL REGA_EXPOTIME         : std_logic_vector(15 DOWNTO 0);    -- Exposure_Line 0000H~FFFFH default 0100H
   SIGNAL REGA_FRAME_FREQ       : std_logic_vector(7 DOWNTO 0);
   SIGNAL REGA_GAIN_MODE        : std_logic;
   SIGNAL REGA_GAIN_VAL         : std_logic_vector(7 DOWNTO 0);     -- gain value, default odd 0100, even 0111
   SIGNAL REGA_KC_X             : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGA_KC_Y             : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGB_CAP_ENABLE       : std_logic;
   SIGNAL REGB_CAP_START        : std_logic;
   SIGNAL REGB_CAP_STOP         : std_logic;
   SIGNAL REGB_EXPOTIME         : std_logic_vector(15 DOWNTO 0);    -- Exposure_Line 0000H~FFFFH default 0100H
   SIGNAL REGB_FRAME_FREQ       : std_logic_vector(7 DOWNTO 0);
   SIGNAL REGB_GAIN_MODE        : std_logic;
   SIGNAL REGB_GAIN_VAL         : std_logic_vector(7 DOWNTO 0);     -- gain value, default odd 0100, even 0111
   SIGNAL REGB_KC_X             : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGB_KC_Y             : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_BASE_TIME         : std_logic_vector(63 DOWNTO 0);
   SIGNAL REG_CAP_MODE          : std_logic_vector(7 DOWNTO 0);
   SIGNAL REG_CMD_NUM           : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_CX                : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_Check             : std_logic;
   SIGNAL REG_ERR               : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_FRAME_NUM_b       : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_NUM               : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_OUTPUT_MODE       : std_logic_vector(7 DOWNTO 0);
   SIGNAL REG_SET_PULSE         : std_logic;                        -- the set signal pulse
   SIGNAL REG_SET_PULSE_b       : std_logic;
   SIGNAL REG_SYNCTIME          : std_logic_vector(63 DOWNTO 0);
   SIGNAL REG_TASKID            : std_logic_vector(7 DOWNTO 0);
   SIGNAL REG_TIME              : std_logic_vector(63 DOWNTO 0);
   SIGNAL RG_Dout               : std_logic_vector(16 DOWNTO 0);
   SIGNAL RG_Vout               : std_logic;
   SIGNAL Reset25M              : std_logic;
   SIGNAL Rsp_Ack               : std_logic;
   SIGNAL Rsp_Start             : std_logic;
   SIGNAL Rsp_State             : std_logic_vector(1 DOWNTO 0);
   SIGNAL TASKID                : std_logic_vector(16 DOWNTO 0);
   SIGNAL TDATA                 : std_logic_vector(11 DOWNTO 0);
   SIGNAL TX_PAD_O              : std_logic;
   SIGNAL VERSION               : std_logic_vector(3 DOWNTO 0);
   SIGNAL WDATA                 : std_logic_vector(7 DOWNTO 0);
   SIGNAL WLAST                 : std_logic;
   SIGNAL WREADY                : std_logic;
   SIGNAL WVALID                : std_logic;
   SIGNAL W_TDATA               : std_logic_vector(15 DOWNTO 0);
   SIGNAL W_TLAST               : std_logic;
   SIGNAL W_TUSER               : std_logic_vector(1 DOWNTO 0);
   SIGNAL W_TVALID              : std_logic;
   SIGNAL X1                    : std_logic_vector(11 DOWNTO 0);
   SIGNAL Y1                    : std_logic_vector(11 DOWNTO 0);
   SIGNAL YC_AWADDR             : std_logic_vector(7 DOWNTO 0);
   SIGNAL YC_AWLEN              : std_logic_vector(7 DOWNTO 0);
   SIGNAL YC_AWREADY            : std_logic;
   SIGNAL YC_AWVALID            : std_logic;
   SIGNAL YC_WDATA              : std_logic_vector(7 DOWNTO 0);
   SIGNAL YC_WLAST              : std_logic;
   SIGNAL YC_WREADY             : std_logic;
   SIGNAL YC_WVALID             : std_logic;
   SIGNAL Z_Req                 : std_logic;
   SIGNAL dout                  : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout1                 : std_logic;
   SIGNAL dout10                : std_logic_vector(63 DOWNTO 0);
   SIGNAL dout11                : std_logic;
   SIGNAL dout12                : std_logic;
   SIGNAL dout13                : std_logic_vector(9 DOWNTO 0);
   SIGNAL dout14                : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout18                : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout19                : std_logic_vector(15 DOWNTO 0);
   SIGNAL dout2                 : std_logic;
   SIGNAL dout3                 : std_logic;
   SIGNAL dout4                 : std_logic;
   SIGNAL dout5                 : std_logic;
   SIGNAL dout6                 : std_logic;
   SIGNAL dout7                 : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout8                 : std_logic_vector(20 DOWNTO 0);
   SIGNAL dout9                 : std_logic_vector(2 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL Eng_Start_internal : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_26' of 'adff'
   SIGNAL mw_U_26reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_41' of 'adff'
   SIGNAL mw_U_41reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_42' of 'adff'
   SIGNAL mw_U_42reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_43' of 'adff'
   SIGNAL mw_U_43reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_44' of 'adff'
   SIGNAL mw_U_44reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_45' of 'adff'
   SIGNAL mw_U_45reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_46' of 'adff'
   SIGNAL mw_U_46reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_47' of 'adff'
   SIGNAL mw_U_47reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_48' of 'adff'
   SIGNAL mw_U_48reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_50' of 'adff'
   SIGNAL mw_U_50reg_cval : std_logic_vector(20 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_51' of 'adff'
   SIGNAL mw_U_51reg_cval : std_logic_vector(16 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_52' of 'adff'
   SIGNAL mw_U_52reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_79' of 'adff'
   SIGNAL mw_U_79reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_80' of 'adff'
   SIGNAL mw_U_80reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_88' of 'adff'
   SIGNAL mw_U_88reg_cval : std_logic_vector(2 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_89' of 'adff'
   SIGNAL mw_U_89reg_cval : std_logic;

attribute keep: string;

attribute keep of QZ_TDATA: signal is "true";
attribute keep of QZ_TVALID: signal is "true";
attribute keep of QZ_TLAST: signal is "true";

   -- Component Declarations
   COMPONENT AXI2GTX_C250324
   GENERIC (
      CHA_LABEL : std_logic_vector(7 downto 0) := X"33"
   );
   PORT (
      Clk           : IN     std_logic ;
      REG_BASE_TIME : IN     std_logic_vector (63 DOWNTO 0);
      REG_TIME      : IN     std_logic_vector (63 DOWNTO 0);
      Reset         : IN     std_logic ;
      TASKID        : IN     std_logic_vector (16 DOWNTO 0);
      TDATA         : IN     std_logic_vector (15 DOWNTO 0);
      TLAST         : IN     std_logic ;
      TUSER         : IN     std_logic_vector (1 DOWNTO 0);
      TVALID        : IN     std_logic ;
      VERSION       : IN     std_logic_vector (3 DOWNTO 0);
      D_REG_H_CNT   : OUT    std_logic_vector (15 DOWNTO 0);
      RG_Dout       : OUT    std_logic_vector (15 DOWNTO 0);
      RG_EOP        : OUT    std_logic ;
      RG_SOP        : OUT    std_logic ;
      RG_Vout       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT AXI2UART_BUG250302
   GENERIC (
      SYNC_HEAD : std_logic_vector(15 downto 0) := X"EB90"
   );
   PORT (
      Clk            : IN     std_logic ;
      REG_TIME       : IN     std_logic_vector (63 DOWNTO 0);
      Reset          : IN     std_logic ;
      TDATA          : IN     std_logic_vector (7 DOWNTO 0);
      TLAST          : IN     std_logic ;
      TUSER          : IN     std_logic_vector (7 DOWNTO 0);
      TVALID         : IN     std_logic ;
      UART_Clk       : IN     std_logic ;
      UART_ClkEn     : IN     std_logic ;
      UART_Reset_n   : IN     std_logic ;
      DEBUG_TX_Data  : OUT    std_logic_vector (7 DOWNTO 0);
      DEBUG_TX_Valid : OUT    std_logic ;
      TX_PAD_O       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BASIC_SEND_C220509
   PORT (
      Clk        : IN     std_logic ;
      FIFO_Din   : IN     std_logic_vector (16 DOWNTO 0);
      FIFO_Empty : IN     std_logic ;
      LS         : IN     std_logic_vector (15 DOWNTO 0);
      Req        : IN     std_logic ;
      Reset      : IN     std_logic ;
      Dout       : OUT    std_logic_vector (15 DOWNTO 0);
      FIFO_Rd    : OUT    std_logic ;
      Kout       : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT BING
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (11 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic ;
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BorderProcess
   PORT (
      Clk       : IN     std_logic ;
      GReset    : IN     std_logic ;
      S_TDATA   : IN     std_logic_vector (11 DOWNTO 0);
      S_TLAST   : IN     std_logic ;
      S_TUSER   : IN     std_logic_vector (1 DOWNTO 0);
      S_TVALID  : IN     std_logic ;
      FOP_Reset : OUT    std_logic ;
      M_TDATA   : OUT    std_logic_vector (11 DOWNTO 0);
      M_TLAST   : OUT    std_logic ;
      M_TUSER   : OUT    std_logic ;
      M_TVALID  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT CB_Window
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      X        : IN     std_logic_vector (11 DOWNTO 0);
      Y        : IN     std_logic_vector (11 DOWNTO 0);
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic_vector (1 DOWNTO 0);
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DownSample
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic ;
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FrameCtrl_C250414
   GENERIC (
      DEF_CLKNUM : std_logic_vector(15 downto 0) := X"03E8"
   );
   PORT (
      Clk      : IN     std_logic ;
      ClkMs_En : IN     std_logic ;
      Din      : IN     std_logic_vector (7 DOWNTO 0);
      Reset    : IN     std_logic ;
      Start    : IN     std_logic ;
      Stop     : IN     std_logic ;
      FOP      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FrameGenPingPang_C250322
   PORT (
      Clk100M   : IN     std_logic ;
      Clk25M    : IN     std_logic ;
      DinA      : IN     std_logic_vector (11 DOWNTO 0);
      DinB      : IN     std_logic_vector (11 DOWNTO 0);
      DinC      : IN     std_logic_vector (11 DOWNTO 0);
      DinD      : IN     std_logic_vector (11 DOWNTO 0);
      DinE      : IN     std_logic_vector (11 DOWNTO 0);
      DinF      : IN     std_logic_vector (11 DOWNTO 0);
      DinG      : IN     std_logic_vector (11 DOWNTO 0);
      DinH      : IN     std_logic_vector (11 DOWNTO 0);
      FOP       : IN     std_logic ;
      REG_H     : IN     std_logic ;
      Reset100M : IN     std_logic ;
      Reset25M  : IN     std_logic ;
      SOP       : IN     std_logic ;
      D_FIFOH   : OUT    std_logic_vector (2 DOWNTO 0);
      TDATA     : OUT    std_logic_vector (11 DOWNTO 0);
      TLAST     : OUT    std_logic ;
      TUSER     : OUT    std_logic_vector (1 DOWNTO 0);
      TVALID    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT GTX_FIFO
   PORT (
      din         : IN     std_logic_vector (16 DOWNTO 0);
      rd_clk      : IN     std_logic;
      rd_en       : IN     std_logic;
      rst         : IN     std_logic;
      wr_clk      : IN     std_logic;
      wr_en       : IN     std_logic;
      dout        : OUT    std_logic_vector (16 DOWNTO 0);
      empty       : OUT    std_logic;
      full        : OUT    std_logic;
      rd_rst_busy : OUT    std_logic;
      wr_rst_busy : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT JWXJ_YC
   PORT (
      AWREADY         : IN     std_logic ;
      Clk             : IN     std_logic ;
      REGA_CAP_ENABLE : IN     std_logic ;
      REGA_EXPOTIME   : IN     std_logic_vector (15 DOWNTO 0);
      REGA_FRAME_FREQ : IN     std_logic_vector (7 DOWNTO 0);
      REGA_GAIN_MODE  : IN     std_logic ;
      REGA_GAIN_VAL   : IN     std_logic_vector (7 DOWNTO 0);
      REGA_IN_NUM     : IN     std_logic_vector (15 DOWNTO 0);
      REGA_KC_X       : IN     std_logic_vector (15 DOWNTO 0);
      REGA_KC_Y       : IN     std_logic_vector (15 DOWNTO 0);
      REGA_OUT_NUM    : IN     std_logic_vector (15 DOWNTO 0);
      REGA_STATE      : IN     std_logic_vector (7 DOWNTO 0);
      REGB_CAP_ENABLE : IN     std_logic ;
      REGB_EXPOTIME   : IN     std_logic_vector (15 DOWNTO 0);
      REGB_FRAME_FREQ : IN     std_logic_vector (7 DOWNTO 0);
      REGB_GAIN_MODE  : IN     std_logic ;
      REGB_GAIN_VAL   : IN     std_logic_vector (7 DOWNTO 0);
      REGB_IN_NUM     : IN     std_logic_vector (15 DOWNTO 0);
      REGB_KC_X       : IN     std_logic_vector (15 DOWNTO 0);
      REGB_KC_Y       : IN     std_logic_vector (15 DOWNTO 0);
      REGB_OUT_NUM    : IN     std_logic_vector (15 DOWNTO 0);
      REGB_STATE      : IN     std_logic_vector (7 DOWNTO 0);
      REG_CAP_MODE    : IN     std_logic_vector (7 DOWNTO 0);
      REG_CMD_NUM     : IN     std_logic_vector (15 DOWNTO 0);
      REG_CX          : IN     std_logic_vector (15 DOWNTO 0);
      REG_ERR         : IN     std_logic_vector (15 DOWNTO 0);
      REG_NUM         : IN     std_logic_vector (15 DOWNTO 0);
      REG_OUTPUT_MODE : IN     std_logic_vector (7 DOWNTO 0);
      REG_STATE       : IN     std_logic_vector (7 DOWNTO 0);
      REG_TASKID      : IN     std_logic_vector (7 DOWNTO 0);
      REG_VERSION     : IN     std_logic_vector (7 DOWNTO 0);
      Reset           : IN     std_logic ;
      WREADY          : IN     std_logic ;
      AWADDR          : OUT    std_logic_vector (7 DOWNTO 0);
      AWLEN           : OUT    std_logic_vector (7 DOWNTO 0);
      AWVALID         : OUT    std_logic ;
      WDATA           : OUT    std_logic_vector (7 DOWNTO 0);
      WLAST           : OUT    std_logic ;
      WVALID          : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT MTFC_FRAME_REGROUP_L2_C211227
   PORT (
      BUSA_Din : IN     std_logic_vector (15 DOWNTO 0);
      BUSA_Eop : IN     std_logic ;
      BUSA_Sop : IN     std_logic ;
      BUSA_Vin : IN     std_logic ;
      BUSB_Din : IN     std_logic_vector (15 DOWNTO 0);
      BUSB_Eop : IN     std_logic ;
      BUSB_Sop : IN     std_logic ;
      BUSB_Vin : IN     std_logic ;
      Clk      : IN     std_logic ;
      Reset    : IN     std_logic ;
      MG_Dout  : OUT    std_logic_vector (16 DOWNTO 0);
      MG_Vout  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT RX_RAM_GROUP_C250114
   PORT (
      ARADDR          : IN     std_logic_vector (9 DOWNTO 0);
      ARLEN           : IN     std_logic_vector (7 DOWNTO 0);
      ARVALID         : IN     std_logic ;
      AWADDR          : IN     std_logic_vector (9 DOWNTO 0);
      AWLEN           : IN     std_logic_vector (7 DOWNTO 0);
      AWVALID         : IN     std_logic ;
      BREADY          : IN     std_logic ;
      Clk             : IN     std_logic ;
      Eng_Ack         : IN     std_logic ;
      RREADY          : IN     std_logic ;
      Reset           : IN     std_logic ;
      Time_Ack        : IN     std_logic ;
      WDATA           : IN     std_logic_vector (7 DOWNTO 0);
      WLAST           : IN     std_logic ;
      WVALID          : IN     std_logic ;
      ARREADY         : OUT    std_logic ;
      AWREADY         : OUT    std_logic ;
      BRESP           : OUT    std_logic_vector (1 DOWNTO 0);
      BVALID          : OUT    std_logic ;
      Eng_Start       : OUT    std_logic ;
      RDATA           : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_CAP_ENABLE : OUT    std_logic ;
      REGA_CAP_MODE   : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_CAP_START  : OUT    std_logic ;
      REGA_CAP_STOP   : OUT    std_logic ;
      REGA_EXPOTIME   : OUT    std_logic_vector (15 DOWNTO 0);
      REGA_FRAME_FREQ : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_GAIN_MODE  : OUT    std_logic ;
      REGA_GAIN_VAL   : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_KC_X       : OUT    std_logic_vector (15 DOWNTO 0);
      REGA_KC_Y       : OUT    std_logic_vector (15 DOWNTO 0);
      REGB_CAP_ENABLE : OUT    std_logic ;
      REGB_CAP_MODE   : OUT    std_logic_vector (7 DOWNTO 0);
      REGB_CAP_START  : OUT    std_logic ;
      REGB_CAP_STOP   : OUT    std_logic ;
      REGB_EXPOTIME   : OUT    std_logic_vector (15 DOWNTO 0);
      REGB_FRAME_FREQ : OUT    std_logic_vector (7 DOWNTO 0);
      REGB_GAIN_MODE  : OUT    std_logic ;
      REGB_GAIN_VAL   : OUT    std_logic_vector (7 DOWNTO 0);
      REGB_KC_X       : OUT    std_logic_vector (15 DOWNTO 0);
      REGB_KC_Y       : OUT    std_logic_vector (15 DOWNTO 0);
      REG_CX          : OUT    std_logic_vector (15 DOWNTO 0);
      REG_OUTPUT_MODE : OUT    std_logic_vector (7 DOWNTO 0);
      REG_SET_PULSE   : OUT    std_logic ;
      REG_SYNCTIME    : OUT    std_logic_vector (63 DOWNTO 0);
      REG_TASKID      : OUT    std_logic_vector (7 DOWNTO 0);
      RLAST           : OUT    std_logic ;
      RVALID          : OUT    std_logic ;
      Time_Start      : OUT    std_logic ;
      WREADY          : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT SENSOR
   GENERIC (
      Cms_Delay      : STD_LOGIC_VECTOR (11 downto 0) := X"001"
   );
   PORT (
      ---------TOP---------
      Power_On       : IN     STD_LOGIC ;                     -- sensor power supply, 1 power on, 0 power off
      Sen_Supply1    : OUT    STD_LOGIC ;                     -- sensor supply1 signal
      Sen_Supply2    : OUT    STD_LOGIC ;                     -- sensor supply2 signal
      Set_Pulse      : IN     STD_LOGIC ;                     -- the set signal pulse
      Shoot_Pulse    : IN     STD_LOGIC ;                     -- the shoot signal pulse
      Image_Mode     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);  -- set image mode 11H shoot, 22H selfcheck1, 33H selfcheck2
      Exposure_Time  : IN     STD_LOGIC_VECTOR (15 DOWNTO 0); -- Exposure_Line 0000H~FFFFH default 0100H
      Gain_Value     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);  -- gain value, default odd 0100, even 0111
      Sen_Status     : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);  -- the status of sensor, 00H none, 01H training, 10H shooting
      Spi_Gain       : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);  -- read spi gain register, odd & even
      Sync_Rx        : OUT    STD_LOGIC ;                     -- the one clk sync signal of every line
      Image_Out      : OUT    STD_LOGIC ;                     -- pull high when the image's output is valid
      Data_Par_Chan1 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel1 data
      Data_Par_Chan2 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel2 data
      Data_Par_Chan3 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel3 data
      Data_Par_Chan4 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel4 data
      Data_Par_Chan5 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel5 data
      Data_Par_Chan6 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel6 data
      Data_Par_Chan7 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel7 data
      Data_Par_Chan8 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- training output channel8 data
      Self_Sync_Rx   : OUT    STD_LOGIC ;                     -- the one clk sync signal of every line
      Self_Image_Out : OUT    STD_LOGIC ;                     -- pull high when the image is ready TO output
      Self_Par_Chan1 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel1 data
      Self_Par_Chan2 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel2 data
      Self_Par_Chan3 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel3 data
      Self_Par_Chan4 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel4 data
      Self_Par_Chan5 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel5 data
      Self_Par_Chan6 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel6 data
      Self_Par_Chan7 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel7 data
      Self_Par_Chan8 : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- selfcheck output channel8 data
      ---------CLOCKING---------
      Clk_Ref        : IN     STD_LOGIC ;                     -- cmos main clk 25MHz, same as CLK_PIX in datasheet
      Rst_Ref        : IN     STD_LOGIC ;                     -- Clk_Ref correspond rst signal
      Clk_Ddr        : IN     STD_LOGIC ;                     -- cmos sample ddr clk, 150MHz
      Rst_Ddr        : IN     STD_LOGIC ;                     -- Clk_Ddr correspond rst signal
      ---------pin---------
      --SEN_CTRL
      SEN_RST_N      : OUT    STD_LOGIC ;                     -- the rst of sensor, low level valid
      --SEN_SPI
      SPI_OUT        : IN     STD_LOGIC ;                     -- sensor spi output signal
      SPI_CLK        : OUT    STD_LOGIC ;                     -- sensor spi clk in 25MHz/50ns
      SPI_IN         : OUT    STD_LOGIC ;                     -- sensor spi input signal
      SPI_WRITE      : OUT    STD_LOGIC ;                     -- the enable of of writing spi
      SPI_READ       : OUT    STD_LOGIC ;                     -- the enable of of reading spi
      --SEN_DRIVE
      ROW            : OUT    STD_LOGIC_VECTOR (11 DOWNTO 0); -- sensor read and reset addr
      TX             : OUT    STD_LOGIC ;                     -- digital control signal
      RS             : OUT    STD_LOGIC ;                     -- digital control signal
      RST            : OUT    STD_LOGIC ;                     -- digital control signal
      HDR            : OUT    STD_LOGIC ;                     -- digital control signal
      TAZ            : OUT    STD_LOGIC ;                     -- digital control signal
      TAB            : OUT    STD_LOGIC ;                     -- digital control signal
      TPC            : OUT    STD_LOGIC ;                     -- digital control signal
      TINITO         : OUT    STD_LOGIC ;                     -- digital control signal
      TINITE         : OUT    STD_LOGIC ;                     -- digital control signal
      TSO            : OUT    STD_LOGIC ;                     -- digital control signal
      TSE            : OUT    STD_LOGIC ;                     -- digital control signal
      TAC            : OUT    STD_LOGIC ;                     -- digital control signal
      TRD            : OUT    STD_LOGIC ;                     -- digital control signal
      TADR           : OUT    STD_LOGIC ;                     -- digital control signal
      TADS           : OUT    STD_LOGIC ;                     -- digital control signal
      TWS            : OUT    STD_LOGIC ;                     -- digital control signal
      SYNC           : OUT    STD_LOGIC ;                     -- digital control signal
      TBS            : OUT    STD_LOGIC ;                     -- digital control signal
      TS             : OUT    STD_LOGIC ;                     -- digital control signal
      TRAIN          : OUT    STD_LOGIC ;                     -- digital control signal
      --TRAINING
      DATA_SER_P     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);  -- the positive LVDS outputs of the sensor, 8 channels
      DATA_SER_N     : IN     STD_LOGIC_VECTOR (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT TIMER
   PORT (
      Clk        : IN     std_logic ;
      Reset      : IN     std_logic ;
      TICK_START : IN     std_logic ;                     --对时脉冲
      TICK_SEC   : IN     std_logic_vector (31 DOWNTO 0); --对时秒值
      TICK_MS    : IN     std_logic_vector (11 DOWNTO 0); --对时毫秒值
      TICK_NS    : IN     std_logic_vector (19 DOWNTO 0); --对时纳秒值
      CALIB_SEC  : OUT    std_logic_vector (31 DOWNTO 0); --校时秒值
      CALIB_MS   : OUT    std_logic_vector (11 DOWNTO 0);
      CALIB_NS   : OUT    std_logic_vector (19 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT TX_RAM_GROUP_C250114
   PORT (
      AWADDR    : IN     std_logic_vector (7 DOWNTO 0);
      AWLEN     : IN     std_logic_vector (7 DOWNTO 0);
      AWVALID   : IN     std_logic ;
      Clk       : IN     std_logic ;
      Eng_Start : IN     std_logic ;
      Reset     : IN     std_logic ;
      Rsp_Start : IN     std_logic ;
      Rsp_State : IN     std_logic_vector (1 DOWNTO 0);
      WDATA     : IN     std_logic_vector (7 DOWNTO 0);
      WLAST     : IN     std_logic ;
      WVALID    : IN     std_logic ;
      AWREADY   : OUT    std_logic ;
      Eng_Ack   : OUT    std_logic ;
      Rsp_Ack   : OUT    std_logic ;
      TDATA     : OUT    std_logic_vector (7 DOWNTO 0);
      TLAST     : OUT    std_logic ;
      TUSER     : OUT    std_logic_vector (7 DOWNTO 0);
      TVALID    : OUT    std_logic ;
      WREADY    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT UART2AXI_C250414
   GENERIC (
      P_HEAD1 : std_logic_vector(7 downto 0) := X"7E";
      P_HEAD2 : std_logic_vector(7 downto 0) := X"E7"
   );
   PORT (
      AWREADY          : IN     std_logic ;
      BVALID           : IN     std_logic ;
      B_RX_PAD_I       : IN     std_logic ;
      Clk              : IN     std_logic ;
      Reset            : IN     std_logic ;
      Rsp_Ack          : IN     std_logic ;
      UART_Clk         : IN     std_logic ;
      UART_ClkEn       : IN     std_logic ;
      UART_Reset_n     : IN     std_logic ;
      WREADY           : IN     std_logic ;
      Z_RX_PAD_I       : IN     std_logic ;
      AWADDR           : OUT    std_logic_vector (9 DOWNTO 0);
      AWLEN            : OUT    std_logic_vector (7 DOWNTO 0);
      AWVALID          : OUT    std_logic ;
      BREADY           : OUT    std_logic ;
      DEBUG_UART_Dout  : OUT    std_logic_vector (7 DOWNTO 0);
      DEBUG_UART_Valid : OUT    std_logic ;
      Debug_State      : OUT    std_logic_vector (3 DOWNTO 0);
      REG_CMD_NUM      : OUT    std_logic_vector (15 DOWNTO 0);
      REG_ERR          : OUT    std_logic_vector (15 DOWNTO 0);
      REG_NUM          : OUT    std_logic_vector (15 DOWNTO 0);
      Rsp_Start        : OUT    std_logic ;
      Rsp_State        : OUT    std_logic_vector (1 DOWNTO 0);
      WDATA            : OUT    std_logic_vector (7 DOWNTO 0);
      WLAST            : OUT    std_logic ;
      WVALID           : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Window
   PORT (
      Clk      : IN     std_logic ;
      FOP      : IN     std_logic ;
      GReset   : IN     std_logic ;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic ;
      S_TUSER  : IN     std_logic ;
      S_TVALID : IN     std_logic ;
      X        : IN     std_logic_vector (11 DOWNTO 0);
      Y        : IN     std_logic_vector (11 DOWNTO 0);
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic ;
      M_TUSER  : OUT    std_logic_vector (1 DOWNTO 0);
      M_TVALID : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT xpm_cdc_pulse
   GENERIC (
      DEST_SYNC_FF   : integer := 4;
      INIT_SYNC_FF   : integer := 0;
      REG_OUTPUT     : integer := 0;
      RST_USED       : integer := 1;
      SIM_ASSERT_CHK : integer := 0;
      VERSION        : integer := 0
   );
   PORT (
      dest_clk   : IN     std_logic;
      dest_rst   : IN     std_logic;
      src_clk    : IN     std_logic;
      src_pulse  : IN     std_logic;
      src_rst    : IN     std_logic;
      dest_pulse : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AXI2GTX_C250324 USE ENTITY JWXJ.AXI2GTX_C250324;
   FOR ALL : AXI2UART_BUG250302 USE ENTITY JWXJ.AXI2UART_BUG250302;
   FOR ALL : BASIC_SEND_C220509 USE ENTITY JWXJ.BASIC_SEND_C220509;
   FOR ALL : BING USE ENTITY JWXJ.BING;
   FOR ALL : BorderProcess USE ENTITY JWXJ.BorderProcess;
   FOR ALL : CB_Window USE ENTITY JWXJ.CB_Window;
   FOR ALL : DownSample USE ENTITY JWXJ.DownSample;
   FOR ALL : FrameCtrl_C250414 USE ENTITY JWXJ.FrameCtrl_C250414;
   FOR ALL : FrameGenPingPang_C250322 USE ENTITY JWXJ.FrameGenPingPang_C250322;
   FOR ALL : JWXJ_YC USE ENTITY JWXJ.JWXJ_YC;
   FOR ALL : MTFC_FRAME_REGROUP_L2_C211227 USE ENTITY JWXJ.MTFC_FRAME_REGROUP_L2_C211227;
   FOR ALL : RX_RAM_GROUP_C250114 USE ENTITY JWXJ.RX_RAM_GROUP_C250114;
   FOR ALL : SENSOR USE ENTITY JWXJ.SENSOR;
   FOR ALL : TIMER USE ENTITY JWXJ.TIMER;
   FOR ALL : TX_RAM_GROUP_C250114 USE ENTITY JWXJ.TX_RAM_GROUP_C250114;
   FOR ALL : UART2AXI_C250414 USE ENTITY JWXJ.UART2AXI_C250414;
   FOR ALL : Window USE ENTITY JWXJ.Window;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process(Reset25M, Clk25M) begin
   	if(Reset25M = '1') then
   		REG_FRAME_NUM_b <= (others => '0');
   	elsif rising_edge(Clk25M) then
   		if(CMA_Shoot_Pulse='1') then
   			REG_FRAME_NUM_b <= (others => '0');
   		elsif(GLOBAL_SOP='1') then
   			REG_FRAME_NUM_b <= REG_FRAME_NUM_b + X"0001";
   		end if;
   	end if;
   end process;
   
   REG_FRAME_NUM <= REG_FRAME_NUM_b;

   -- HDL Embedded Text Block 2 eb2
   --CMOSA
   SUP_EN1     <= CMA_Sen_Supply1;
   SUP_EN2     <= '1';
   SUP_EN3     <= CMA_Sen_Supply1;
   SUP_EN4     <= CMA_Sen_Supply2;
   SUP_EN5     <= CMA_Sen_Supply2;
   SUP_EN6     <= CMA_Sen_Supply2;
   SUP_EN7     <= CMA_Sen_Supply2;
   SUP_EN8     <= CMA_Sen_Supply2;
   -- CMA_CLK_REF <= Clk25M;
   --CMOSB
   SUP_EN9     <= CMB_Sen_Supply1;
   SUP_EN10    <= '1';
   SUP_EN11    <= CMB_Sen_Supply1;
   SUP_EN12    <= CMB_Sen_Supply2;
   SUP_EN13    <= CMB_Sen_Supply2;
   SUP_EN14    <= CMB_Sen_Supply2;
   SUP_EN15    <= CMB_Sen_Supply2;
   SUP_EN16    <= CMB_Sen_Supply2;
   -- CMB_CLK_REF <= Clk25M;
   

   -- HDL Embedded Text Block 3 eb3
   -- eb3 3 
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_Check <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_CAP_MODE = X"33") then
   			REG_Check <= '1';
   		else
   			REG_Check <= '0';
   		end if;
   	end if;
   end process;
                                          

   -- HDL Embedded Text Block 4 eb4
   -- eb4 4                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		KC_En <= "00";
   	elsif rising_edge(Clk) then
   		case REG_OUTPUT_MODE is
   			when X"22" =>
   				KC_En <= "01";
   			when X"33" =>
   				KC_En <= "10";
   			when others =>
   				KC_En <= "00";
   		end case;
   	end if;
   end process;


   -- ModuleWare code(v1.9) for instance 'U_26' of 'adff'
   D_GLOBAL_SOP <= mw_U_26reg_cval;
   u_26seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_26reg_cval <= GLOBAL_SOP;
      END IF;
   END PROCESS u_26seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_41' of 'adff'
   D_DinA <= mw_U_41reg_cval;
   u_41seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_41reg_cval <= DinA;
      END IF;
   END PROCESS u_41seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_42' of 'adff'
   D_DinB <= mw_U_42reg_cval;
   u_42seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_42reg_cval <= DinB;
      END IF;
   END PROCESS u_42seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_43' of 'adff'
   D_DinC <= mw_U_43reg_cval;
   u_43seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_43reg_cval <= DinC;
      END IF;
   END PROCESS u_43seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_44' of 'adff'
   D_DinD <= mw_U_44reg_cval;
   u_44seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_44reg_cval <= DinD;
      END IF;
   END PROCESS u_44seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_45' of 'adff'
   D_DinE <= mw_U_45reg_cval;
   u_45seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_45reg_cval <= DinE;
      END IF;
   END PROCESS u_45seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_46' of 'adff'
   D_DinF <= mw_U_46reg_cval;
   u_46seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_46reg_cval <= DinF;
      END IF;
   END PROCESS u_46seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_47' of 'adff'
   D_DinG <= mw_U_47reg_cval;
   u_47seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_47reg_cval <= DinG;
      END IF;
   END PROCESS u_47seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_48' of 'adff'
   D_DinH <= mw_U_48reg_cval;
   u_48seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_48reg_cval <= DinH;
      END IF;
   END PROCESS u_48seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_50' of 'adff'
   D_QZ <= mw_U_50reg_cval;
   u_50seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_50reg_cval <= dout8;
      END IF;
   END PROCESS u_50seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_51' of 'adff'
   D_RG_Dout <= mw_U_51reg_cval;
   u_51seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_51reg_cval <= RG_Dout;
      END IF;
   END PROCESS u_51seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_52' of 'adff'
   D_RG_Vout <= mw_U_52reg_cval;
   u_52seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_52reg_cval <= RG_Vout;
      END IF;
   END PROCESS u_52seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_79' of 'adff'
   Z_TX_PAD_O <= mw_U_79reg_cval;
   u_79seq_proc: PROCESS (UART_Clk)BEGIN
      IF (UART_Clk'EVENT AND UART_Clk='1') THEN
         mw_U_79reg_cval <= TX_PAD_O;
      END IF;
   END PROCESS u_79seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_80' of 'adff'
   B_TX_PAD_O <= mw_U_80reg_cval;
   u_80seq_proc: PROCESS (UART_Clk)BEGIN
      IF (UART_Clk'EVENT AND UART_Clk='1') THEN
         mw_U_80reg_cval <= TX_PAD_O;
      END IF;
   END PROCESS u_80seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_88' of 'adff'
   DEBUG_FC <= mw_U_88reg_cval;
   u_88seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_88reg_cval <= dout9;
      END IF;
   END PROCESS u_88seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_89' of 'adff'
   D_FOP_Reset <= mw_U_89reg_cval;
   u_89seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_89reg_cval <= FOP_Reset;
      END IF;
   END PROCESS u_89seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_9' of 'and'
   dout2 <= RG_Vout AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'and'
   dout5 <= RG_Vout AND dout3;

   -- ModuleWare code(v1.9) for instance 'U_18' of 'constval'
   LS <= "0000000000101000";

   -- ModuleWare code(v1.9) for instance 'U_97' of 'constval'
   X1 <= "001100100000";

   -- ModuleWare code(v1.9) for instance 'U_98' of 'constval'
   Y1 <= "000000000011";

   -- ModuleWare code(v1.9) for instance 'U_8' of 'gnd'
   VERSION <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_15' of 'gnd'
   TASKID <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_16' of 'gnd'
   REG_BASE_TIME <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_17' of 'gnd'
   REG_TIME <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_31' of 'gnd'
   dout7 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_66' of 'gnd'
   dout <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_72' of 'gnd'
   dout11 <= '0';

   -- ModuleWare code(v1.9) for instance 'U_73' of 'gnd'
   dout13 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_74' of 'gnd'
   dout14 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_75' of 'gnd'
   dout12 <= '0';

   -- ModuleWare code(v1.9) for instance 'U_82' of 'gnd'
   dout19 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_83' of 'gnd'
   dout18 <= (OTHERS => '0');

   -- ModuleWare code(v1.9) for instance 'U_10' of 'inv'
   dout1 <= NOT(GTXFIFO_Z_Full);

   -- ModuleWare code(v1.9) for instance 'U_12' of 'inv'
   Z_Req <= NOT(GTXFIFO_Z_Empty);

   -- ModuleWare code(v1.9) for instance 'U_19' of 'inv'
   Reset25M <= NOT(Reset25M_n);

   -- ModuleWare code(v1.9) for instance 'U_21' of 'inv'
   B_Req <= NOT(GTXFIFO_B_Empty);

   -- ModuleWare code(v1.9) for instance 'U_23' of 'inv'
   dout3 <= NOT(GTXFIFO_B_Full);

   -- ModuleWare code(v1.9) for instance 'U_0' of 'merge'
   dout8 <= D_FIFOH & QZ_TLAST & QZ_TVALID & QZ_TDATA;

   -- ModuleWare code(v1.9) for instance 'U_24' of 'merge'
   dout9 <= CMA_FOP & REGA_CAP_STOP & REGA_CAP_START;

   -- ModuleWare code(v1.9) for instance 'U_30' of 'merge'
   QZ_TDATA <= dout7 & TDATA;

   -- ModuleWare code(v1.9) for instance 'U_65' of 'merge'
   CMB_QZ_TDATA <= dout & CMB_TDATA;

   -- ModuleWare code(v1.9) for instance 'U_69' of 'merge'
   dout10 <= CALIB_SEC & CALIB_MS & CALIB_NS;

   -- ModuleWare code(v1.9) for instance 'U_76' of 'merge'
   DEBUG_ENG <= ENG_TLAST & ENG_TVALID & ENG_TDATA;

   -- ModuleWare code(v1.9) for instance 'U_85' of 'merge'
   DEBUG_TX <= DEBUG_TX_Valid & DEBUG_TX_Data;

   -- ModuleWare code(v1.9) for instance 'U_87' of 'merge'
   u_87combo_proc: PROCESS(CMB_TDATA, dout11)
   VARIABLE temp_dout : std_logic_vector(15 DOWNTO 0);
   BEGIN
      temp_dout := (OTHERS => 'X');
      temp_dout(12 DOWNTO 0) := dout11 & CMB_TDATA;
      CB_QZ_TDATA <= temp_dout;
   END PROCESS u_87combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_95' of 'merge'
   QZ_Dout <= QZ_EOP & QZ_Data;

   -- ModuleWare code(v1.9) for instance 'U_96' of 'merge'
   CMB_QZ_Dout <= CMB_QZ_EOP & CMB_QZ_Data;

   -- ModuleWare code(v1.9) for instance 'U_28' of 'mux'
   u_28combo_proc: PROCESS(MG_Dout, QZ_Dout, CMB_QZ_Dout, KC_En)
   BEGIN
      CASE KC_En IS
      WHEN "00" => RG_Dout <= MG_Dout;
      WHEN "01" => RG_Dout <= QZ_Dout;
      WHEN "10" => RG_Dout <= CMB_QZ_Dout;
      WHEN OTHERS => RG_Dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_28combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_29' of 'mux'
   u_29combo_proc: PROCESS(MG_Vout, QZ_Vout, CMB_QZ_Vout, KC_En)
   BEGIN
      CASE KC_En IS
      WHEN "00" => RG_Vout <= MG_Vout;
      WHEN "01" => RG_Vout <= QZ_Vout;
      WHEN "10" => RG_Vout <= CMB_QZ_Vout;
      WHEN OTHERS => RG_Vout <= 'X';
      END CASE;
   END PROCESS u_29combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_32' of 'mux'
   u_32combo_proc: PROCESS(CMA_Data_Par_Chan1, CMA_Self_Par_Chan1, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinA <= CMA_Data_Par_Chan1;
      WHEN '1' => DinA <= CMA_Self_Par_Chan1;
      WHEN OTHERS => DinA <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_32combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_33' of 'mux'
   u_33combo_proc: PROCESS(CMA_Data_Par_Chan2, CMA_Self_Par_Chan2, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinB <= CMA_Data_Par_Chan2;
      WHEN '1' => DinB <= CMA_Self_Par_Chan2;
      WHEN OTHERS => DinB <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_33combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_34' of 'mux'
   u_34combo_proc: PROCESS(CMA_Data_Par_Chan3, CMA_Self_Par_Chan3, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinC <= CMA_Data_Par_Chan3;
      WHEN '1' => DinC <= CMA_Self_Par_Chan3;
      WHEN OTHERS => DinC <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_34combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_35' of 'mux'
   u_35combo_proc: PROCESS(CMA_Data_Par_Chan4, CMA_Self_Par_Chan4, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinD <= CMA_Data_Par_Chan4;
      WHEN '1' => DinD <= CMA_Self_Par_Chan4;
      WHEN OTHERS => DinD <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_35combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_36' of 'mux'
   u_36combo_proc: PROCESS(CMA_Data_Par_Chan5, CMA_Self_Par_Chan5, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinE <= CMA_Data_Par_Chan5;
      WHEN '1' => DinE <= CMA_Self_Par_Chan5;
      WHEN OTHERS => DinE <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_36combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_37' of 'mux'
   u_37combo_proc: PROCESS(CMA_Data_Par_Chan6, CMA_Self_Par_Chan6, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinF <= CMA_Data_Par_Chan6;
      WHEN '1' => DinF <= CMA_Self_Par_Chan6;
      WHEN OTHERS => DinF <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_37combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_38' of 'mux'
   u_38combo_proc: PROCESS(CMA_Data_Par_Chan7, CMA_Self_Par_Chan7, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinG <= CMA_Data_Par_Chan7;
      WHEN '1' => DinG <= CMA_Self_Par_Chan7;
      WHEN OTHERS => DinG <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_38combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_39' of 'mux'
   u_39combo_proc: PROCESS(CMA_Data_Par_Chan8, CMA_Self_Par_Chan8, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => DinH <= CMA_Data_Par_Chan8;
      WHEN '1' => DinH <= CMA_Self_Par_Chan8;
      WHEN OTHERS => DinH <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_39combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_40' of 'mux'
   u_40combo_proc: PROCESS(CMA_Sync_Rx, CMA_Self_Sync_Rx, REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => GLOBAL_SOP <= CMA_Sync_Rx;
      WHEN '1' => GLOBAL_SOP <= CMA_Self_Sync_Rx;
      WHEN OTHERS => GLOBAL_SOP <= 'X';
      END CASE;
   END PROCESS u_40combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_56' of 'mux'
   u_56combo_proc: PROCESS(CMB_Sync_Rx, CMB_Self_Sync_Rx, REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_GLOBAL_SOP <= CMB_Sync_Rx;
      WHEN '1' => CMB_GLOBAL_SOP <= CMB_Self_Sync_Rx;
      WHEN OTHERS => CMB_GLOBAL_SOP <= 'X';
      END CASE;
   END PROCESS u_56combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_57' of 'mux'
   u_57combo_proc: PROCESS(CMB_Data_Par_Chan1, CMB_Self_Par_Chan1, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinA <= CMB_Data_Par_Chan1;
      WHEN '1' => CMB_DinA <= CMB_Self_Par_Chan1;
      WHEN OTHERS => CMB_DinA <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_57combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_58' of 'mux'
   u_58combo_proc: PROCESS(CMB_Data_Par_Chan2, CMB_Self_Par_Chan2, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinB <= CMB_Data_Par_Chan2;
      WHEN '1' => CMB_DinB <= CMB_Self_Par_Chan2;
      WHEN OTHERS => CMB_DinB <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_58combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_59' of 'mux'
   u_59combo_proc: PROCESS(CMB_Data_Par_Chan3, CMB_Self_Par_Chan3, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinC <= CMB_Data_Par_Chan3;
      WHEN '1' => CMB_DinC <= CMB_Self_Par_Chan3;
      WHEN OTHERS => CMB_DinC <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_59combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_60' of 'mux'
   u_60combo_proc: PROCESS(CMB_Data_Par_Chan4, CMB_Self_Par_Chan4, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinD <= CMB_Data_Par_Chan4;
      WHEN '1' => CMB_DinD <= CMB_Self_Par_Chan4;
      WHEN OTHERS => CMB_DinD <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_60combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_61' of 'mux'
   u_61combo_proc: PROCESS(CMB_Data_Par_Chan5, CMB_Self_Par_Chan5, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinE <= CMB_Data_Par_Chan5;
      WHEN '1' => CMB_DinE <= CMB_Self_Par_Chan5;
      WHEN OTHERS => CMB_DinE <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_61combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_62' of 'mux'
   u_62combo_proc: PROCESS(CMB_Data_Par_Chan6, CMB_Self_Par_Chan6, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinF <= CMB_Data_Par_Chan6;
      WHEN '1' => CMB_DinF <= CMB_Self_Par_Chan6;
      WHEN OTHERS => CMB_DinF <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_62combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_63' of 'mux'
   u_63combo_proc: PROCESS(CMB_Data_Par_Chan7, CMB_Self_Par_Chan7, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinG <= CMB_Data_Par_Chan7;
      WHEN '1' => CMB_DinG <= CMB_Self_Par_Chan7;
      WHEN OTHERS => CMB_DinG <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_63combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_64' of 'mux'
   u_64combo_proc: PROCESS(CMB_Data_Par_Chan8, CMB_Self_Par_Chan8, 
                           REG_Check)
   BEGIN
      CASE REG_Check IS
      WHEN '0' => CMB_DinH <= CMB_Data_Par_Chan8;
      WHEN '1' => CMB_DinH <= CMB_Self_Par_Chan8;
      WHEN OTHERS => CMB_DinH <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_64combo_proc;

   -- ModuleWare code(v1.9) for instance 'U_92' of 'or'
   dout4 <= GTXFIFO_Z_rd_rst_busy OR OPT_Z_Reset;

   -- ModuleWare code(v1.9) for instance 'U_93' of 'or'
   dout6 <= GTXFIFO_B_rd_rst_busy OR OPT_B_Reset;

   -- Instance port mappings.
   U_14 : AXI2GTX_C250324
      GENERIC MAP (
         CHA_LABEL => X"33"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => FOP_Reset,
         TASKID        => TASKID,
         TDATA         => W_TDATA,
         TLAST         => W_TLAST,
         TUSER         => W_TUSER,
         TVALID        => W_TVALID,
         VERSION       => VERSION,
         D_REG_H_CNT   => D_REG_H_CNT,
         RG_Dout       => KC_Dout,
         RG_EOP        => KC_Eop,
         RG_SOP        => KC_Sop,
         RG_Vout       => KC_Vout
      );
   U_27 : AXI2GTX_C250324
      GENERIC MAP (
         CHA_LABEL => X"55"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => Reset,
         TASKID        => TASKID,
         TDATA         => QZ_TDATA,
         TLAST         => QZ_TLAST,
         TUSER         => QZ_TUSER,
         TVALID        => QZ_TVALID,
         VERSION       => VERSION,
         D_REG_H_CNT   => OPEN,
         RG_Dout       => QZ_Data,
         RG_EOP        => QZ_EOP,
         RG_SOP        => OPEN,
         RG_Vout       => QZ_Vout
      );
   U_55 : AXI2GTX_C250324
      GENERIC MAP (
         CHA_LABEL => X"66"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => Reset,
         TASKID        => TASKID,
         TDATA         => CMB_QZ_TDATA,
         TLAST         => CMB_QZ_TLAST,
         TUSER         => CMB_QZ_TUSER,
         TVALID        => CMB_QZ_TVALID,
         VERSION       => VERSION,
         D_REG_H_CNT   => OPEN,
         RG_Dout       => CMB_QZ_Data,
         RG_EOP        => CMB_QZ_EOP,
         RG_SOP        => OPEN,
         RG_Vout       => CMB_QZ_Vout
      );
   U_91 : AXI2GTX_C250324
      GENERIC MAP (
         CHA_LABEL => X"44"
      )
      PORT MAP (
         Clk           => Clk,
         REG_BASE_TIME => REG_BASE_TIME,
         REG_TIME      => REG_TIME,
         Reset         => CMB_QZ_TUSER(1),
         TASKID        => TASKID,
         TDATA         => CB_M_TDATA,
         TLAST         => CB_M_TLAST,
         TUSER         => CB_M_TUSER,
         TVALID        => CB_M_TVALID,
         VERSION       => VERSION,
         D_REG_H_CNT   => OPEN,
         RG_Dout       => CB_KC_Dout,
         RG_EOP        => CB_KC_EOP,
         RG_SOP        => CB_KC_SOP,
         RG_Vout       => CB_KC_Vout
      );
   U_68 : AXI2UART_BUG250302
      GENERIC MAP (
         SYNC_HEAD => X"E77E"
      )
      PORT MAP (
         Clk            => Clk,
         REG_TIME       => dout10,
         Reset          => Reset,
         TDATA          => ENG_TDATA,
         TLAST          => ENG_TLAST,
         TUSER          => ENG_TUSER,
         TVALID         => ENG_TVALID,
         UART_Clk       => UART_Clk,
         UART_ClkEn     => UART_ClkEn,
         UART_Reset_n   => UART_Reset_n,
         DEBUG_TX_Data  => DEBUG_TX_Data,
         DEBUG_TX_Valid => DEBUG_TX_Valid,
         TX_PAD_O       => TX_PAD_O
      );
   U_11 : BASIC_SEND_C220509
      PORT MAP (
         Clk        => OPT_Z_Clk,
         FIFO_Din   => GTXFIFO_Z_Dout,
         FIFO_Empty => GTXFIFO_Z_Empty,
         LS         => LS,
         Req        => Z_Req,
         Reset      => dout4,
         Dout       => GTX_Z_Dout,
         FIFO_Rd    => GTXFIFO_Z_Rd,
         Kout       => GTX_Z_Kout
      );
   U_13 : BASIC_SEND_C220509
      PORT MAP (
         Clk        => OPT_B_Clk,
         FIFO_Din   => GTXFIFO_B_Dout,
         FIFO_Empty => GTXFIFO_B_Empty,
         LS         => LS,
         Req        => B_Req,
         Reset      => dout6,
         Dout       => GTX_B_Dout,
         FIFO_Rd    => GTXFIFO_B_Rd,
         Kout       => GTX_B_Kout
      );
   U_3 : BING
      PORT MAP (
         Clk      => Clk,
         FOP      => FOP_Reset,
         GReset   => Reset,
         S_TDATA  => M_TDATA,
         S_TLAST  => M_TLAST,
         S_TUSER  => M_TUSER,
         S_TVALID => M_TVALID,
         M_TDATA  => BING_TDATA,
         M_TLAST  => BING_TLAST,
         M_TUSER  => BING_TUSER,
         M_TVALID => BING_TVALID
      );
   U_2 : BorderProcess
      PORT MAP (
         Clk       => Clk,
         GReset    => Reset,
         S_TDATA   => TDATA,
         S_TLAST   => QZ_TLAST,
         S_TUSER   => QZ_TUSER,
         S_TVALID  => QZ_TVALID,
         FOP_Reset => FOP_Reset,
         M_TDATA   => M_TDATA,
         M_TLAST   => M_TLAST,
         M_TUSER   => M_TUSER,
         M_TVALID  => M_TVALID
      );
   U_90 : CB_Window
      PORT MAP (
         Clk      => Clk,
         FOP      => CMB_QZ_TUSER(1),
         GReset   => Reset,
         S_TDATA  => CB_QZ_TDATA,
         S_TLAST  => CMB_QZ_TLAST,
         S_TUSER  => CMB_QZ_TUSER(0),
         S_TVALID => CMB_QZ_TVALID,
         X        => X1,
         Y        => Y1,
         M_TDATA  => CB_M_TDATA,
         M_TLAST  => CB_M_TLAST,
         M_TUSER  => CB_M_TUSER,
         M_TVALID => CB_M_TVALID
      );
   U_5 : DownSample
      PORT MAP (
         Clk      => Clk,
         FOP      => FOP_Reset,
         GReset   => Reset,
         S_TDATA  => BING_TDATA,
         S_TLAST  => BING_TLAST,
         S_TUSER  => BING_TUSER,
         S_TVALID => BING_TVALID,
         M_TDATA  => D_TDATA,
         M_TLAST  => D_TLAST,
         M_TUSER  => D_TUSER,
         M_TVALID => D_TVALID
      );
   U_71 : FrameCtrl_C250414
      GENERIC MAP (
         DEF_CLKNUM => X"0032"
      )
      PORT MAP (
         Clk      => Clk,
         ClkMs_En => ClkMs_En,
         Din      => REGA_FRAME_FREQ,
         Reset    => Reset,
         Start    => REGA_CAP_START,
         Stop     => REGA_CAP_STOP,
         FOP      => CMA_FOP
      );
   U_86 : FrameCtrl_C250414
      GENERIC MAP (
         DEF_CLKNUM => X"00C8"
      )
      PORT MAP (
         Clk      => Clk,
         ClkMs_En => ClkMs_En,
         Din      => REGB_FRAME_FREQ,
         Reset    => Reset,
         Start    => REGB_CAP_START,
         Stop     => REGB_CAP_STOP,
         FOP      => CMB_FOP
      );
   U_1 : FrameGenPingPang_C250322
      PORT MAP (
         Clk100M   => Clk,
         Clk25M    => Clk25M,
         DinA      => DinA,
         DinB      => DinB,
         DinC      => DinC,
         DinD      => DinD,
         DinE      => DinE,
         DinF      => DinF,
         DinG      => DinG,
         DinH      => DinH,
         FOP       => CMA_Shoot_Pulse,
         REG_H     => REGA_GAIN_MODE,
         Reset100M => Reset,
         Reset25M  => Reset25M,
         SOP       => GLOBAL_SOP,
         D_FIFOH   => D_FIFOH,
         TDATA     => TDATA,
         TLAST     => QZ_TLAST,
         TUSER     => QZ_TUSER,
         TVALID    => QZ_TVALID
      );
   U_54 : FrameGenPingPang_C250322
      PORT MAP (
         Clk100M   => Clk,
         Clk25M    => Clk25M,
         DinA      => CMB_DinA,
         DinB      => CMB_DinB,
         DinC      => CMB_DinC,
         DinD      => CMB_DinD,
         DinE      => CMB_DinE,
         DinF      => CMB_DinF,
         DinG      => CMB_DinG,
         DinH      => CMB_DinH,
         FOP       => CMB_Shoot_Pulse,
         REG_H     => REGB_GAIN_MODE,
         Reset100M => Reset,
         Reset25M  => Reset25M,
         SOP       => CMB_GLOBAL_SOP,
         D_FIFOH   => OPEN,
         TDATA     => CMB_TDATA,
         TLAST     => CMB_QZ_TLAST,
         TUSER     => CMB_QZ_TUSER,
         TVALID    => CMB_QZ_TVALID
      );
   U_4 : GTX_FIFO
      PORT MAP (
         rst         => Reset,
         wr_clk      => Clk,
         rd_clk      => OPT_Z_Clk,
         din         => RG_Dout,
         wr_en       => dout2,
         rd_en       => GTXFIFO_Z_Rd,
         dout        => GTXFIFO_Z_Dout,
         full        => GTXFIFO_Z_Full,
         empty       => GTXFIFO_Z_Empty,
         wr_rst_busy => OPEN,
         rd_rst_busy => GTXFIFO_Z_rd_rst_busy
      );
   U_20 : GTX_FIFO
      PORT MAP (
         rst         => Reset,
         wr_clk      => Clk,
         rd_clk      => OPT_B_Clk,
         din         => RG_Dout,
         wr_en       => dout5,
         rd_en       => GTXFIFO_B_Rd,
         dout        => GTXFIFO_B_Dout,
         full        => GTXFIFO_B_Full,
         empty       => GTXFIFO_B_Empty,
         wr_rst_busy => OPEN,
         rd_rst_busy => GTXFIFO_B_rd_rst_busy
      );
   U_81 : JWXJ_YC
      PORT MAP (
         AWREADY         => YC_AWREADY,
         Clk             => Clk,
         REGA_CAP_ENABLE => REGA_CAP_ENABLE,
         REGA_EXPOTIME   => REGA_EXPOTIME,          --  Exposure_Line 0000H~FFFFH default 0100H 
         REGA_FRAME_FREQ => REGA_FRAME_FREQ,
         REGA_GAIN_MODE  => REGA_GAIN_MODE,
         REGA_GAIN_VAL   => REGA_GAIN_VAL,          --  gain value, default odd 0100, even 0111 
         REGA_IN_NUM     => dout19,
         REGA_KC_X       => REGA_KC_X,
         REGA_KC_Y       => REGA_KC_Y,
         REGA_OUT_NUM    => dout19,
         REGA_STATE      => dout18,
         REGB_CAP_ENABLE => REGB_CAP_ENABLE,
         REGB_EXPOTIME   => REGB_EXPOTIME,
         REGB_FRAME_FREQ => REGB_FRAME_FREQ,
         REGB_GAIN_MODE  => REGB_GAIN_MODE,
         REGB_GAIN_VAL   => REGB_GAIN_VAL,
         REGB_IN_NUM     => dout19,
         REGB_KC_X       => REGB_KC_X,
         REGB_KC_Y       => REGB_KC_Y,
         REGB_OUT_NUM    => dout19,
         REGB_STATE      => dout18,
         REG_CAP_MODE    => REG_CAP_MODE,
         REG_CMD_NUM     => REG_CMD_NUM,
         REG_CX          => REG_CX,
         REG_ERR         => REG_ERR,
         REG_NUM         => REG_NUM,
         REG_OUTPUT_MODE => REG_OUTPUT_MODE,
         REG_STATE       => dout18,
         REG_TASKID      => REG_TASKID,
         REG_VERSION     => dout18,
         Reset           => Reset,
         WREADY          => YC_WREADY,
         AWADDR          => YC_AWADDR,
         AWLEN           => YC_AWLEN,
         AWVALID         => YC_AWVALID,
         WDATA           => YC_WDATA,
         WLAST           => YC_WLAST,
         WVALID          => YC_WVALID
      );
   U_94 : MTFC_FRAME_REGROUP_L2_C211227
      PORT MAP (
         BUSA_Din => KC_Dout,
         BUSA_Eop => KC_Eop,
         BUSA_Sop => KC_Sop,
         BUSA_Vin => KC_Vout,
         BUSB_Din => CB_KC_Dout,
         BUSB_Eop => CB_KC_EOP,
         BUSB_Sop => CB_KC_SOP,
         BUSB_Vin => CB_KC_Vout,
         Clk      => Clk,
         Reset    => Reset,
         MG_Dout  => MG_Dout,
         MG_Vout  => MG_Vout
      );
   U_49 : RX_RAM_GROUP_C250114
      PORT MAP (
         ARADDR          => dout13,
         ARLEN           => dout14,
         ARVALID         => dout12,
         AWADDR          => AWADDR,
         AWLEN           => AWLEN,
         AWVALID         => AWVALID,
         BREADY          => BREADY,
         Clk             => Clk,
         Eng_Ack         => Eng_Ack,
         RREADY          => dout12,
         Reset           => Reset,
         Time_Ack        => dout11,
         WDATA           => WDATA,
         WLAST           => WLAST,
         WVALID          => WVALID,
         ARREADY         => OPEN,
         AWREADY         => AWREADY,
         BRESP           => OPEN,
         BVALID          => BVALID,
         Eng_Start       => Eng_Start_internal,
         RDATA           => OPEN,
         REGA_CAP_ENABLE => REGA_CAP_ENABLE,
         REGA_CAP_MODE   => REG_CAP_MODE,
         REGA_CAP_START  => REGA_CAP_START,
         REGA_CAP_STOP   => REGA_CAP_STOP,
         REGA_EXPOTIME   => REGA_EXPOTIME,          --  Exposure_Line 0000H~FFFFH default 0100H 
         REGA_FRAME_FREQ => REGA_FRAME_FREQ,
         REGA_GAIN_MODE  => REGA_GAIN_MODE,
         REGA_GAIN_VAL   => REGA_GAIN_VAL,          --  gain value, default odd 0100, even 0111 
         REGA_KC_X       => REGA_KC_X,
         REGA_KC_Y       => REGA_KC_Y,
         REGB_CAP_ENABLE => OPEN,
         REGB_CAP_MODE   => OPEN,
         REGB_CAP_START  => REGB_CAP_START,
         REGB_CAP_STOP   => REGB_CAP_STOP,
         REGB_EXPOTIME   => REGB_EXPOTIME,
         REGB_FRAME_FREQ => REGB_FRAME_FREQ,
         REGB_GAIN_MODE  => REGB_GAIN_MODE,
         REGB_GAIN_VAL   => REGB_GAIN_VAL,
         REGB_KC_X       => REGB_KC_X,
         REGB_KC_Y       => REGB_KC_Y,
         REG_CX          => REG_CX,
         REG_OUTPUT_MODE => REG_OUTPUT_MODE,
         -- -------TOP---------
         -- CMOSA
         REG_SET_PULSE   => REG_SET_PULSE_b,          --  the set signal pulse 
         REG_SYNCTIME    => REG_SYNCTIME,
         REG_TASKID      => REG_TASKID,
         RLAST           => OPEN,
         RVALID          => OPEN,
         Time_Start      => OPEN,
         WREADY          => WREADY
      );
   U2 : SENSOR
      GENERIC MAP (
         Cms_Delay => X"001"
      )
      PORT MAP (
         Power_On       => CMA_Power_On,
         Sen_Supply1    => CMA_Sen_Supply1,
         Sen_Supply2    => CMA_Sen_Supply2,
         Set_Pulse      => REG_SET_PULSE,
         Shoot_Pulse    => CMA_Shoot_Pulse,
         Image_Mode     => REG_CAP_MODE,
         Exposure_Time  => REGA_EXPOTIME,
         Gain_Value     => REGA_GAIN_VAL,
         Sen_Status     => CMA_Sen_Status,
         Spi_Gain       => CMA_Spi_Gain,
         Sync_Rx        => CMA_Sync_Rx,
         Image_Out      => CMA_Image_Out,
         Data_Par_Chan1 => CMA_Data_Par_Chan1,
         Data_Par_Chan2 => CMA_Data_Par_Chan2,
         Data_Par_Chan3 => CMA_Data_Par_Chan3,
         Data_Par_Chan4 => CMA_Data_Par_Chan4,
         Data_Par_Chan5 => CMA_Data_Par_Chan5,
         Data_Par_Chan6 => CMA_Data_Par_Chan6,
         Data_Par_Chan7 => CMA_Data_Par_Chan7,
         Data_Par_Chan8 => CMA_Data_Par_Chan8,
         Self_Sync_Rx   => CMA_Self_Sync_Rx,
         Self_Image_Out => CMA_Self_Image_Out,
         Self_Par_Chan1 => CMA_Self_Par_Chan1,
         Self_Par_Chan2 => CMA_Self_Par_Chan2,
         Self_Par_Chan3 => CMA_Self_Par_Chan3,
         Self_Par_Chan4 => CMA_Self_Par_Chan4,
         Self_Par_Chan5 => CMA_Self_Par_Chan5,
         Self_Par_Chan6 => CMA_Self_Par_Chan6,
         Self_Par_Chan7 => CMA_Self_Par_Chan7,
         Self_Par_Chan8 => CMA_Self_Par_Chan8,
         Clk_Ref        => Clk25M,
         Rst_Ref        => Reset25M_n,
         Clk_Ddr        => Clk_Ddr,
         Rst_Ddr        => Rst_Ddr_n,
         SEN_RST_N      => CMA_SEN_RST_N,
         SPI_OUT        => CMA_SPI_OUT,
         SPI_CLK        => CMA_SPI_CLK,
         SPI_IN         => CMA_SPI_IN,
         SPI_WRITE      => CMA_SPI_WRITE,
         SPI_READ       => CMA_SPI_READ,
         ROW            => CMA_ROW,
         TX             => CMA_TX,
         RS             => CMA_RS,
         RST            => CMA_RST,
         HDR            => CMA_HDR,
         TAZ            => CMA_TAZ,
         TAB            => CMA_TAB,
         TPC            => CMA_TPC,
         TINITO         => CMA_TINITO,
         TINITE         => CMA_TINITE,
         TSO            => CMA_TSO,
         TSE            => CMA_TSE,
         TAC            => CMA_TAC,
         TRD            => CMA_TRD,
         TADR           => CMA_TADR,
         TADS           => CMA_TADS,
         TWS            => CMA_TWS,
         SYNC           => CMA_SYNC,
         TBS            => CMA_TBS,
         TS             => CMA_TS,
         TRAIN          => CMA_TRAIN,
         DATA_SER_P     => CMA_DATA_SER_P,
         DATA_SER_N     => CMA_DATA_SER_N
      );
   U_53 : SENSOR
      GENERIC MAP (
         Cms_Delay => X"001"
      )
      PORT MAP (
         Power_On       => CMB_Power_On,
         Sen_Supply1    => CMB_Sen_Supply1,
         Sen_Supply2    => CMB_Sen_Supply2,
         Set_Pulse      => REG_SET_PULSE,
         Shoot_Pulse    => CMB_Shoot_Pulse,
         Image_Mode     => REG_CAP_MODE,
         Exposure_Time  => REGB_EXPOTIME,
         Gain_Value     => REGB_GAIN_VAL,
         Sen_Status     => CMB_Sen_Status,
         Spi_Gain       => CMB_Spi_Gain,
         Sync_Rx        => CMB_Sync_Rx,
         Image_Out      => CMB_Image_Out,
         Data_Par_Chan1 => CMB_Data_Par_Chan1,
         Data_Par_Chan2 => CMB_Data_Par_Chan2,
         Data_Par_Chan3 => CMB_Data_Par_Chan3,
         Data_Par_Chan4 => CMB_Data_Par_Chan4,
         Data_Par_Chan5 => CMB_Data_Par_Chan5,
         Data_Par_Chan6 => CMB_Data_Par_Chan6,
         Data_Par_Chan7 => CMB_Data_Par_Chan7,
         Data_Par_Chan8 => CMB_Data_Par_Chan8,
         Self_Sync_Rx   => CMB_Self_Sync_Rx,
         Self_Image_Out => CMB_Self_Image_Out,
         Self_Par_Chan1 => CMB_Self_Par_Chan1,
         Self_Par_Chan2 => CMB_Self_Par_Chan2,
         Self_Par_Chan3 => CMB_Self_Par_Chan3,
         Self_Par_Chan4 => CMB_Self_Par_Chan4,
         Self_Par_Chan5 => CMB_Self_Par_Chan5,
         Self_Par_Chan6 => CMB_Self_Par_Chan6,
         Self_Par_Chan7 => CMB_Self_Par_Chan7,
         Self_Par_Chan8 => CMB_Self_Par_Chan8,
         Clk_Ref        => Clk25M,
         Rst_Ref        => Reset25M_n,
         Clk_Ddr        => Clk_Ddr,
         Rst_Ddr        => Rst_Ddr_n,
         SEN_RST_N      => CMB_SEN_RST_N,
         SPI_OUT        => CMB_SPI_OUT,
         SPI_CLK        => CMB_SPI_CLK,
         SPI_IN         => CMB_SPI_IN,
         SPI_WRITE      => CMB_SPI_WRITE,
         SPI_READ       => CMB_SPI_READ,
         ROW            => CMB_ROW,
         TX             => CMB_TX,
         RS             => CMB_RS,
         RST            => CMB_RST,
         HDR            => CMB_HDR,
         TAZ            => CMB_TAZ,
         TAB            => CMB_TAB,
         TPC            => CMB_TPC,
         TINITO         => CMB_TINITO,
         TINITE         => CMB_TINITE,
         TSO            => CMB_TSO,
         TSE            => CMB_TSE,
         TAC            => CMB_TAC,
         TRD            => CMB_TRD,
         TADR           => CMB_TADR,
         TADS           => CMB_TADS,
         TWS            => CMB_TWS,
         SYNC           => CMB_SYNC,
         TBS            => CMB_TBS,
         TS             => CMB_TS,
         TRAIN          => CMB_TRAIN,
         DATA_SER_P     => CMB_DATA_SER_P,
         DATA_SER_N     => CMB_DATA_SER_N
      );
   U_70 : TIMER
      PORT MAP (
         Clk        => Clk,
         Reset      => Reset,
         TICK_START => TICK_START,
         TICK_SEC   => REG_SYNCTIME(63 DOWNTO 32),
         TICK_MS    => REG_SYNCTIME(31 DOWNTO 20),
         TICK_NS    => REG_SYNCTIME(19 DOWNTO 0),
         CALIB_SEC  => CALIB_SEC,
         CALIB_MS   => CALIB_MS,
         CALIB_NS   => CALIB_NS
      );
   U_67 : TX_RAM_GROUP_C250114
      PORT MAP (
         AWADDR    => YC_AWADDR,
         AWLEN     => YC_AWLEN,
         AWVALID   => YC_AWVALID,
         Clk       => Clk,
         Eng_Start => Eng_Start_internal,
         Reset     => Reset,
         Rsp_Start => Rsp_Start,
         Rsp_State => Rsp_State,
         WDATA     => YC_WDATA,
         WLAST     => YC_WLAST,
         WVALID    => YC_WVALID,
         AWREADY   => YC_AWREADY,
         Eng_Ack   => Eng_Ack,
         Rsp_Ack   => Rsp_Ack,
         TDATA     => ENG_TDATA,
         TLAST     => ENG_TLAST,
         TUSER     => ENG_TUSER,
         TVALID    => ENG_TVALID,
         WREADY    => YC_WREADY
      );
   U_7 : UART2AXI_C250414
      GENERIC MAP (
         P_HEAD1 => X"7E",
         P_HEAD2 => X"E7"
      )
      PORT MAP (
         AWREADY          => AWREADY,
         BVALID           => BVALID,
         B_RX_PAD_I       => B_RX_PAD_I,
         Clk              => Clk,
         Reset            => Reset,
         Rsp_Ack          => Rsp_Ack,
         UART_Clk         => UART_Clk,
         UART_ClkEn       => UART_ClkEn,
         UART_Reset_n     => UART_Reset_n,
         WREADY           => WREADY,
         Z_RX_PAD_I       => Z_RX_PAD_I,
         AWADDR           => AWADDR,
         AWLEN            => AWLEN,
         AWVALID          => AWVALID,
         BREADY           => BREADY,
         DEBUG_UART_Dout  => DEBUG_UART_Dout,
         DEBUG_UART_Valid => DEBUG_UART_Valid,
         Debug_State      => OPEN,
         REG_CMD_NUM      => REG_CMD_NUM,
         REG_ERR          => REG_ERR,
         REG_NUM          => REG_NUM,
         Rsp_Start        => Rsp_Start,
         Rsp_State        => Rsp_State,
         WDATA            => WDATA,
         WLAST            => WLAST,
         WVALID           => WVALID
      );
   U_6 : Window
      PORT MAP (
         Clk      => Clk,
         FOP      => FOP_Reset,
         GReset   => Reset,
         S_TDATA  => D_TDATA,
         S_TLAST  => D_TLAST,
         S_TUSER  => D_TUSER,
         S_TVALID => D_TVALID,
         X        => REGA_KC_X(12 downto 1),
         Y        => REGA_KC_Y(12 downto 1),
         M_TDATA  => W_TDATA,
         M_TLAST  => W_TLAST,
         M_TUSER  => W_TUSER,
         M_TVALID => W_TVALID
      );
   U_77 : xpm_cdc_pulse
      PORT MAP (
         src_clk    => Clk,
         src_pulse  => CMA_FOP,
         dest_clk   => Clk25M,
         src_rst    => Reset,
         dest_rst   => Reset25M,
         dest_pulse => CMA_Shoot_Pulse
      );
   U_78 : xpm_cdc_pulse
      PORT MAP (
         src_clk    => Clk,
         src_pulse  => CMB_FOP,
         dest_clk   => Clk25M,
         src_rst    => Reset,
         dest_rst   => Reset25M,
         dest_pulse => CMB_Shoot_Pulse
      );
   U_84 : xpm_cdc_pulse
      PORT MAP (
         src_clk    => Clk,
         src_pulse  => REG_SET_PULSE_b,
         dest_clk   => Clk25M,
         src_rst    => Reset,
         dest_rst   => Reset25M,
         dest_pulse => REG_SET_PULSE
      );

   -- Implicit buffered output assignments
   Eng_Start <= Eng_Start_internal;

END struct;
