-- VHDL Entity JWXJ.RX_RAM_GROUP_C250114.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 08:39:48 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY RX_RAM_GROUP_C250114 IS
   PORT( 
      ARADDR          : IN     std_logic_vector (9 DOWNTO 0);
      ARLEN           : IN     std_logic_vector (7 DOWNTO 0);
      ARVALID         : IN     std_logic;
      AWADDR          : IN     std_logic_vector (9 DOWNTO 0);
      AWLEN           : IN     std_logic_vector (7 DOWNTO 0);
      AWVALID         : IN     std_logic;
      BREADY          : IN     std_logic;
      Clk             : IN     std_logic;
      Eng_Ack         : IN     std_logic;
      RREADY          : IN     std_logic;
      Reset           : IN     std_logic;
      Time_Ack        : IN     std_logic;
      WDATA           : IN     std_logic_vector (7 DOWNTO 0);
      WLAST           : IN     std_logic;
      WVALID          : IN     std_logic;
      ARREADY         : OUT    std_logic;
      AWREADY         : OUT    std_logic;
      BRESP           : OUT    std_logic_vector (1 DOWNTO 0);
      BVALID          : OUT    std_logic;
      Eng_Start       : OUT    std_logic;
      RDATA           : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_CAP_ENABLE : OUT    std_logic;
      REGA_CAP_MODE   : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_CAP_START  : OUT    std_logic;
      REGA_CAP_STOP   : OUT    std_logic;
      REGA_EXPOTIME   : OUT    std_logic_vector (15 DOWNTO 0);
      REGA_FRAME_FREQ : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_GAIN_MODE  : OUT    std_logic;
      REGA_GAIN_VAL   : OUT    std_logic_vector (7 DOWNTO 0);
      REGA_KC_X       : OUT    std_logic_vector (15 DOWNTO 0);
      REGA_KC_Y       : OUT    std_logic_vector (15 DOWNTO 0);
      REGB_CAP_ENABLE : OUT    std_logic;
      REGB_CAP_MODE   : OUT    std_logic_vector (7 DOWNTO 0);
      REGB_CAP_START  : OUT    std_logic;
      REGB_CAP_STOP   : OUT    std_logic;
      REGB_EXPOTIME   : OUT    std_logic_vector (15 DOWNTO 0);
      REGB_FRAME_FREQ : OUT    std_logic_vector (7 DOWNTO 0);
      REGB_GAIN_MODE  : OUT    std_logic;
      REGB_GAIN_VAL   : OUT    std_logic_vector (7 DOWNTO 0);
      REGB_KC_X       : OUT    std_logic_vector (15 DOWNTO 0);
      REGB_KC_Y       : OUT    std_logic_vector (15 DOWNTO 0);
      REG_CX          : OUT    std_logic_vector (15 DOWNTO 0);
      REG_OUTPUT_MODE : OUT    std_logic_vector (7 DOWNTO 0);
      REG_SET_PULSE   : OUT    std_logic;
      REG_SYNCTIME    : OUT    std_logic_vector (63 DOWNTO 0);
      REG_TASKID      : OUT    std_logic_vector (7 DOWNTO 0);
      RLAST           : OUT    std_logic;
      RVALID          : OUT    std_logic;
      Time_Start      : OUT    std_logic;
      WREADY          : OUT    std_logic
   );

-- Declarations

END RX_RAM_GROUP_C250114 ;

--
-- VHDL Architecture JWXJ.RX_RAM_GROUP_C250114.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 08:39:49 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF RX_RAM_GROUP_C250114 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_ADDR,
      ST_DATA,
      ST_ERR,
      ST_RSP,
      ST_WAIT,
      ST_RD_ADDR,
      ST_RD_DATA,
      ST_RD_ERR
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(13 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(13 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_DATA : std_logic;
   SIGNAL csm1_to_ST_RSP : std_logic;
   SIGNAL csm1_to_ST_WAIT : std_logic;
   SIGNAL csm1_to_ST_RD_DATA : std_logic;


   -- Internal signal declarations
   SIGNAL ARADDR_r          : std_logic_vector(9 DOWNTO 0);
   SIGNAL ARADDR_r2         : std_logic_vector(9 DOWNTO 0);
   SIGNAL ARLEN_r           : std_logic_vector(7 DOWNTO 0);
   SIGNAL ARLEN_r2          : std_logic_vector(7 DOWNTO 0);
   SIGNAL ARVALID_r         : std_logic;
   SIGNAL ARVALID_r2        : std_logic;
   SIGNAL AWADDR_r          : std_logic_vector(9 DOWNTO 0);
   SIGNAL AWADDR_r2         : std_logic_vector(9 DOWNTO 0);
   SIGNAL AWLEN_r           : std_logic_vector(7 DOWNTO 0);
   SIGNAL AWLEN_r2          : std_logic_vector(7 DOWNTO 0);
   SIGNAL AWVALID_r         : std_logic;
   SIGNAL AWVALID_r2        : std_logic;
   SIGNAL Add_RAM_Cnt       : std_logic;
   SIGNAL Add_RAM_RdCnt     : std_logic;
   SIGNAL Dout              : std_logic;
   SIGNAL Dout1             : std_logic;
   SIGNAL End_RAM_RdCnt     : std_logic;
   SIGNAL RAM_Addr_Start    : std_logic_vector(9 DOWNTO 0);
   SIGNAL RAM_Cnt           : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_Dout          : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL RAM_RdAddr        : std_logic_vector(9 DOWNTO 0);
   SIGNAL RAM_RdAddr_Start  : std_logic_vector(9 DOWNTO 0);
   SIGNAL RAM_RdCnt         : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_RdEn          : STD_LOGIC;
   SIGNAL RAM_WrAddr        : std_logic_vector(9 DOWNTO 0);
   SIGNAL RAM_WrEn          : std_logic;
   SIGNAL REGA_CAP_ENABLE_b : std_logic;
   SIGNAL REGA_KC_Check     : std_logic;
   SIGNAL REGA_KC_Err       : std_logic;
   SIGNAL REGA_KC_X_b       : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGA_KC_Y_b       : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGB_CAP_ENABLE_b : std_logic;
   SIGNAL REGB_KC_Check     : std_logic;
   SIGNAL REGB_KC_Err       : std_logic;
   SIGNAL REGB_KC_X_b       : std_logic_vector(15 DOWNTO 0);
   SIGNAL REGB_KC_Y_b       : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_CX_b          : std_logic_vector(15 DOWNTO 0);
   SIGNAL REG_CX_p          : std_logic;
   SIGNAL REG_LEN           : std_logic_vector(7 DOWNTO 0);
   SIGNAL REG_RLEN          : std_logic_vector(7 DOWNTO 0);
   SIGNAL REG_WrEn          : STD_LOGIC;
   SIGNAL RLAST_b           : std_logic;
   SIGNAL RLAST_b2          : std_logic;
   SIGNAL RREADY_r          : std_logic;
   SIGNAL RREADY_r2         : std_logic;
   SIGNAL RVALID_b1         : std_logic;
   SIGNAL RVALID_b2         : std_logic;
   SIGNAL WDATA_r           : std_logic_vector(7 DOWNTO 0);
   SIGNAL WDATA_r2          : std_logic_vector(7 DOWNTO 0);
   SIGNAL WDATA_r3          : std_logic_vector(7 DOWNTO 0);
   SIGNAL WLAST_r           : std_logic;
   SIGNAL WLAST_r2          : std_logic;
   SIGNAL WVALID_r          : std_logic;
   SIGNAL WVALID_r2         : std_logic;
   SIGNAL wea               : std_logic_vector(0 DOWNTO 0);


   -- ModuleWare signal declarations(v1.9) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(9 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_8' of 'adff'
   SIGNAL mw_U_8reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_9' of 'adff'
   SIGNAL mw_U_9reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_10' of 'adff'
   SIGNAL mw_U_10reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_11' of 'adff'
   SIGNAL mw_U_11reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_12' of 'adff'
   SIGNAL mw_U_12reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_13' of 'adff'
   SIGNAL mw_U_13reg_cval : std_logic_vector(9 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_14' of 'adff'
   SIGNAL mw_U_14reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_15' of 'adff'
   SIGNAL mw_U_15reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_16' of 'adff'
   SIGNAL mw_U_16reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_17' of 'adff'
   SIGNAL mw_U_17reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_18' of 'adff'
   SIGNAL mw_U_18reg_cval : std_logic_vector(9 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_19' of 'adff'
   SIGNAL mw_U_19reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_20' of 'adff'
   SIGNAL mw_U_20reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_21' of 'adff'
   SIGNAL mw_U_21reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_22' of 'adff'
   SIGNAL mw_U_22reg_cval : std_logic_vector(9 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_23' of 'adff'
   SIGNAL mw_U_23reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_24' of 'adff'
   SIGNAL mw_U_24reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_25' of 'adff'
   SIGNAL mw_U_25reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_26' of 'adff'
   SIGNAL mw_U_26reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_27' of 'adff'
   SIGNAL mw_U_27reg_cval : std_logic;

attribute fsm_safe_state : string;
attribute fsm_safe_state of State_c : signal is "default_state";

   -- Component Declarations
   COMPONENT CAP_POS
   PORT (
      Clk  : IN     std_logic;
      Din  : IN     std_logic;
      Dout : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT PARAM_RAM_C250116
   PORT (
      addra : IN     STD_LOGIC_VECTOR ( 9 DOWNTO 0 );
      addrb : IN     STD_LOGIC_VECTOR ( 9 DOWNTO 0 );
      clka  : IN     STD_LOGIC;
      clkb  : IN     STD_LOGIC;
      dina  : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      ena   : IN     STD_LOGIC;
      enb   : IN     STD_LOGIC;
      wea   : IN     STD_LOGIC_VECTOR ( 0 TO 0 );
      doutb : OUT    STD_LOGIC_VECTOR ( 7 DOWNTO 0 )
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CAP_POS USE ENTITY JWXJ.CAP_POS;
   FOR ALL : PARAM_RAM_C250116 USE ENTITY JWXJ.PARAM_RAM_C250116;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      ARVALID_r,
      AWVALID_r,
      BREADY,
      End_RAM_RdCnt,
      RREADY_r,
      State_c,
      WLAST_r2,
      WVALID_r,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_DATA <= '0';
      csm1_to_ST_RSP <= '0';
      csm1_to_ST_WAIT <= '0';
      csm1_to_ST_RD_DATA <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (AWVALID_r='1') THEN 
               State_n <= ST_ADDR;
            ELSIF (ARVALID_r='1') THEN 
               State_n <= ST_RD_ADDR;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_ADDR => 
            IF (WVALID_r='1') THEN 
               State_n <= ST_DATA;
               csm1_to_ST_DATA <= '1';
            ELSE
               State_n <= ST_ADDR;
            END IF;
         WHEN ST_DATA => 
            IF (WLAST_r2 = '1') THEN 
               State_n <= ST_WAIT;
               csm1_to_ST_WAIT <= '1';
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_ERR;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_ERR => 
            State_n <= ST_IDLE;
         WHEN ST_RSP => 
            IF (BREADY='1') THEN 
               State_n <= ST_IDLE;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_RSP;
            END IF;
         WHEN ST_WAIT => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_RSP;
               csm1_to_ST_RSP <= '1';
            ELSE
               State_n <= ST_WAIT;
            END IF;
         WHEN ST_RD_ADDR => 
            IF (RREADY_r='1') THEN 
               State_n <= ST_RD_DATA;
               csm1_to_ST_RD_DATA <= '1';
            ELSE
               State_n <= ST_RD_ADDR;
            END IF;
         WHEN ST_RD_DATA => 
            IF (End_RAM_RdCnt='1') THEN 
               State_n <= ST_IDLE;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_RD_ERR;
            ELSE
               State_n <= ST_RD_DATA;
            END IF;
         WHEN ST_RD_ERR => 
            State_n <= ST_IDLE;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_DATA,
      csm1_to_ST_RSP,
      csm1_to_ST_WAIT,
      csm1_to_ST_RD_DATA
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_DATA = '1') THEN
         csm1_next_timer <= "10011100001111"; -- no cycles(10000)-1=9999
      ELSIF (csm1_to_ST_RSP = '1') THEN
         csm1_next_timer <= "10011100001111"; -- no cycles(10000)-1=9999
      ELSIF (csm1_to_ST_WAIT = '1') THEN
         csm1_next_timer <= "00000000000010"; -- no cycles(3)-1=2
      ELSIF (csm1_to_ST_RD_DATA = '1') THEN
         csm1_next_timer <= "10011100001111"; -- no cycles(10000)-1=9999
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   ------------------------------------------------------------
   -- 计数器
   ------------------------------------------------------------
      
      process(Clk, Reset) begin
         if(Reset = '1') then
            RAM_Cnt <= (others => '0');
         elsif rising_edge(Clk) then
   		if(State_c = ST_IDLE) then
   			RAM_Cnt <= (others => '0');
   		elsif(Add_RAM_Cnt = '1') then
   			RAM_Cnt <= RAM_Cnt + X"01";
   		end if;
         end if;
      end process;
      
      Add_RAM_Cnt <= '1' when (State_c = ST_DATA) and (WVALID_r2 = '1') else '0';
      
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			RAM_Addr_Start <= (others => '0');
   	   elsif rising_edge(Clk) then
   		  if(State_c = ST_ADDR) then
   			RAM_Addr_Start <=  AWADDR_r2;
   		  end if;
   	   end if;
      end process;
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			RAM_WrAddr <= (others => '0');
   	   elsif rising_edge(Clk) then
   		   if(State_c = ST_DATA) then
   				if(WVALID_r2 = '1') then
   					RAM_WrAddr <= RAM_Addr_Start + RAM_Cnt;
   				end if;
   		   else
   				RAM_WrAddr <= (others => '0');
   		   end if;
   	   end if;
      end process;
      
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			RAM_WrEn <= '0';
   	   elsif rising_edge(Clk) then
   			if(State_c = ST_DATA) and (WVALID_r2 = '1') and (RAM_Addr_Start(9 downto 8) = "00") then
   				RAM_WrEn <= '1';
   			else
   				RAM_WrEn <= '0';
   			end if;
   	   end if;
      end process;
      
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			REG_WrEn <= '0';
   	   elsif rising_edge(Clk) then
   			if(State_c = ST_DATA) and (WVALID_r2 = '1') and (RAM_Addr_Start(9 downto 8) /= "00") then
   				REG_WrEn <= '1';
   			else
   				REG_WrEn <= '0';
   			end if;
   	   end if;
      end process;
      
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   		   REG_LEN <= (others => '0');
   	   elsif rising_edge(Clk) then
   		   if(State_c = ST_ADDR ) and (AWVALID_r2 = '1') then
   				REG_LEN <= AWLEN_r2;
   		   end if;
   	   end if;
      end process;
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			BRESP <= "00";
   	   elsif rising_edge(Clk) then
   			if(State_c = ST_RSP) then
   				if(RAM_Cnt = REG_LEN) then
   					BRESP <= "00";
   				else
   					BRESP <= "11";
   				end if;
   			elsif(State_c = ST_ERR) then
   				BRESP <= "11";
   			end if;
   	   end if;
      end process;
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			BVALID <= '0';
   	   elsif rising_edge(Clk) then
   			if(State_c = ST_RSP) or (State_c = ST_ERR) then
   				BVALID <= '1';
   			else
   				BVALID <= '0';
   			end if;
   	   end if;
      end process;
      
      
      
      
      
      
   
   
   
   
   
   
   
   
   
   
   

   -- HDL Embedded Text Block 3 eb3
   -- eb3 3  
   
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Eng_Start <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"08")) then
   			Eng_Start <= '1';
   		elsif(Eng_Ack = '1') then
   			Eng_Start <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		Time_Start <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"05")) then
   			Time_Start <= '1';
   		else
   			Time_Start <= '0';
   		end if;
   	end if;
   end process;
   
   -- 4-5 探测器1曝光时间
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_EXPOTIME(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"04")) then
   			REGA_EXPOTIME(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_EXPOTIME(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"05")) then
   			REGA_EXPOTIME(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   
   -- 6 探测器1增益模式
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_GAIN_MODE <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"06")) then
   			if(WDATA_r3 = X"22") then
   				REGA_GAIN_MODE <= '1';
   			else
   				REGA_GAIN_MODE <= '0';
   			end if;
   		end if;
   	end if;
   end process;                 
   
   -- 7 探测器1增益值
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_GAIN_VAL <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"07")) then
   			REGA_GAIN_VAL <= WDATA_r3;
   		end if;
   	end if;
   end process; 
   
   -- 8 探测器1使能
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_CAP_ENABLE_b <= '1';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"08")) then
   			if(WDATA_r3 = X"00") then
   				REGA_CAP_ENABLE_b <= '0';
   			else
   				REGA_CAP_ENABLE_b <= '1';
   			end if;
   		end if;
   	end if;
   end process;
   
   --10-11 探测器2曝光时间
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_EXPOTIME(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"0A")) then
   			REGB_EXPOTIME(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_EXPOTIME(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"0B")) then
   			REGB_EXPOTIME(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   -- 12 探测器2增益模式 ---
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_GAIN_MODE <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"0C")) then
   			if(WDATA_r3 = X"22") then
   				REGB_GAIN_MODE <= '1';
   			else
   				REGB_GAIN_MODE <= '0';
   			end if;
   		end if;
   	end if;
   end process;                 
   
   -- 13 探测器2增益值
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_GAIN_VAL <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"0D")) then
   			REGB_GAIN_VAL <= WDATA_r3;
   		end if;
   	end if;
   end process; 
   
   
   -- 14 探测器2使能
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_CAP_ENABLE_b <= '1';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"0E")) then
   			if(WDATA_r3 = X"00") then
   				REGB_CAP_ENABLE_b <= '0';
   			else
   				REGB_CAP_ENABLE_b <= '1';
   			end if;
   		end if;
   	end if;
   end process;
   
   -- 16 探测器1每秒帧数
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_FRAME_FREQ <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"10")) then
   			REGA_FRAME_FREQ <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   -- 17 探测器1图像输出模式
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_OUTPUT_MODE <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"11")) then
   			REG_OUTPUT_MODE <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   -- 18-19 探测器1开窗X位置
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_KC_X_b(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"12")) then
   			REGA_KC_X_b(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_KC_X_b(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"13")) then
   			REGA_KC_X_b(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   
   
   -- 20-21 探测器1开窗Y位置
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_KC_Y_b(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"14")) then
   			REGA_KC_Y_b(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_KC_Y_b(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"15")) then
   			REGA_KC_Y_b(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_KC_Check <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"15")) then
   			REGA_KC_Check <= '1';
   		else
   			REGA_KC_Check <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_KC_X <= (others => '0');
   		REGA_KC_Y <= (others => '0');
   		REGA_KC_Err <= '0';
   	elsif rising_edge(Clk) then
   		if(REGA_KC_Check = '1') then
   			if(REGA_KC_X_b < conv_std_logic_vector(728,16)) and 
   			   (REGA_KC_Y_b < conv_std_logic_vector(1008,16)) then
   				REGA_KC_X <= REGA_KC_X_b;
   				REGA_KC_Y <= REGA_KC_Y_b;
   				REGA_KC_Err <= '0';
   			else
   				REGA_KC_Err <= '1';
   			end if;
   		else
   			REGA_KC_Err <= '0';
   		end if;
   	end if;
   end process;
   
   -- 28 探测器2每秒帧数
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_FRAME_FREQ <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"1C")) then
   			REGB_FRAME_FREQ <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   
   --- 30-31 探测器2开窗X位置
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_KC_X_b(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"1E")) then
   			REGB_KC_X_b(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_KC_X_b(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"1F")) then
   			REGB_KC_X_b(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   -- 32-33 探测器2开窗Y位置
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_KC_Y_b(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"20")) then
   			REGB_KC_Y_b(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_KC_Y_b(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"21")) then
   			REGB_KC_Y_b(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_KC_Check <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"21")) then
   			REGB_KC_Check <= '1';
   		else
   			REGB_KC_Check <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_KC_X <= (others => '0');
   		REGB_KC_Y <= (others => '0');
   		REGB_KC_Err <= '0';
   	elsif rising_edge(Clk) then
   		if(REGA_KC_Check = '1') then
   			if(REGB_KC_X_b < conv_std_logic_vector(728,16)) and 
   			   (REGB_KC_Y_b < conv_std_logic_vector(1008,16)) then
   				REGB_KC_X <= REGB_KC_X_b;
   				REGB_KC_Y <= REGB_KC_Y_b;
   				REGB_KC_Err <= '0';
   			else
   				REGB_KC_Err <= '1';
   			end if;
   		else
   			REGB_KC_Err <= '0';
   		end if;
   	end if;
   end process;
   
   --40 探测器1自校图形控制参数
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_CAP_MODE <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"28")) then
   			REGA_CAP_MODE <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SET_PULSE <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"28")) then
   			REG_SET_PULSE <= '1';
   		else
   			REG_SET_PULSE <= '0';
   		end if;
   	end if;
   end process;
   
   
   -- 41 探测器2自校图形控制参数
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_CAP_MODE <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("01"& X"29")) then
   			REGB_CAP_MODE <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   
   ----------------------------------------------------------------------------
   
   --- 同步时间码 ------
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(63 downto 56) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"00") ) then
   			REG_SYNCTIME(63 downto 56) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(55 downto 48) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"01") ) then
   			REG_SYNCTIME(55 downto 48) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(47 downto 40) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"02") ) then
   			REG_SYNCTIME(47 downto 40) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(39 downto 32) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = "10" & X"03") then
   			REG_SYNCTIME(39 downto 32) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(31 downto 24) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"04")) then
   			REG_SYNCTIME(31 downto 24) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(23 downto 16) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"05")) then
   			REG_SYNCTIME(23 downto 16) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(15 downto 8) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"06")) then
   			REG_SYNCTIME(15 downto 8) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_SYNCTIME(7 downto 0) <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10" & X"07")) then
   			REG_SYNCTIME(7 downto 0) <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   
   -- 探测器1拍摄开始
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_CAP_START <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"10")) then
   			if(WDATA_r3 = X"11") then --and (REGA_CAP_ENABLE_b = '1') then
   				REGA_CAP_START <= '1';
   			else
   				REGA_CAP_START <= '0';
   			end if;
   		else
   			REGA_CAP_START <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGA_CAP_STOP <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"10")) then
   			if(WDATA_r3 = X"00") then --and (REGA_CAP_ENABLE_b = '1') then
   				REGA_CAP_STOP <= '1';
   			else
   				REGA_CAP_STOP <= '0';
   			end if;
   		else
   			REGA_CAP_STOP <= '0';
   		end if;
   	end if;
   end process;
   
   -- 探测器2拍摄停止
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_CAP_START <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"10")) then
   			if(WDATA_r3 = X"11") and (REGB_CAP_ENABLE_b = '1') then
   				REGB_CAP_START <= '1';
   			else
   				REGB_CAP_START <= '0';
   			end if;
   		else
   			REGB_CAP_START <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REGB_CAP_STOP <= '0';
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"10")) then
   			if(WDATA_r3 = X"00") and (REGB_CAP_ENABLE_b = '1') then
   				REGB_CAP_STOP <= '1';
   			else
   				REGB_CAP_STOP <= '0';
   			end if;
   		else
   			REGB_CAP_STOP <= '0';
   		end if;
   	end if;
   end process;
   
   
   -- 探测器2拍摄停止
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_TASKID <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_WrEn = '1') and (RAM_WrAddr = ("10"& X"11")) then
   			REG_TASKID <= WDATA_r3;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_CX_b <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(REG_CX_p = '1') then
   			REG_CX_b <= REG_CX_b + X"0001";
   		end if;
   	end if;
   end process;
   REG_CX <= REG_CX_b;

   -- HDL Embedded Text Block 4 eb4
   -- eb4 4                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RAM_RdAddr_Start <= (others => '1');
   		REG_RLEN <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_IDLE) then
   			RAM_RdAddr_Start <= (others => '1');
   			REG_RLEN <= (others => '0');
   		elsif(State_c = ST_RD_ADDR) and (ARVALID_r2 = '1') then
   			RAM_RdAddr_Start <= ARADDR_r2;
   			REG_RLEN         <= ARLEN_r2;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RAM_RdEn <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_RD_DATA) and (RREADY_r2 = '1') then
   			RAM_RdEn <= '1';
   		else
   			RAM_RdEn <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RAM_RdAddr <= (others => '1');
   
   	elsif rising_edge(Clk) then
   		if(State_c = ST_RD_DATA) and (RREADY_r2 = '1') then
   			RAM_RdAddr <= RAM_RdAddr_Start + ('0'&RAM_RdCnt);
   			
   		end if;
   	end if;
   end process;
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RVALID_b1  <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_RD_DATA) and (RREADY_r2 = '1') then
   			RVALID_b1 <=  '1';
   		else
   			RVALID_b1  <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RVALID_b2  <= '0';
   		RVALID     <= '0';
   	elsif rising_edge(Clk) then
   		RVALID_b2 <= RVALID_b1;
   		RVALID    <= RVALID_b2;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RDATA      <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(RVALID_b2 = '1') then
   			RDATA     <= RAM_Dout;
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RAM_RdCnt <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(Add_RAM_RdCnt = '1') then
   			if(End_RAM_RdCnt = '1') then
   				RAM_RdCnt <= (others => '0');
   			else
   				RAM_RdCnt <=  RAM_RdCnt + X"01";
   			end if;
   		end if;
   	end if;
   end process;
   
   Add_RAM_RdCnt <= '1' when (State_c = ST_RD_DATA) and (RREADY_r2 = '1') else '0';
   End_RAM_RdCnt <= '1' when (Add_RAM_RdCnt = '1') and (RAM_RdCnt = REG_RLEN) else '0';
   
   
   process(Clk) begin
   	if rising_edge(Clk) then
   		RLAST_b <= End_RAM_RdCnt;
   		RLAST_b2 <= RLAST_b;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RLAST <= '0';
   	elsif rising_edge(Clk) then
   		RLAST <= RLAST_b2;
   	end if;
   end process;
   
   
   
   
   
   
   
   
   
   
   
   


   -- ModuleWare code(v1.9) for instance 'U_5' of 'adff'
   AWVALID_r <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_5reg_cval <= AWVALID;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'adff'
   AWLEN_r <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_6reg_cval <= AWLEN;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'adff'
   AWADDR_r <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_7reg_cval <= AWADDR;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'adff'
   WVALID_r <= mw_U_8reg_cval;
   u_8seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_8reg_cval <= WVALID;
      END IF;
   END PROCESS u_8seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_9' of 'adff'
   WDATA_r <= mw_U_9reg_cval;
   u_9seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_9reg_cval <= WDATA;
      END IF;
   END PROCESS u_9seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_10' of 'adff'
   WLAST_r <= mw_U_10reg_cval;
   u_10seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_10reg_cval <= WLAST;
      END IF;
   END PROCESS u_10seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_11' of 'adff'
   WVALID_r2 <= mw_U_11reg_cval;
   u_11seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_11reg_cval <= WVALID_r;
      END IF;
   END PROCESS u_11seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_12' of 'adff'
   WDATA_r2 <= mw_U_12reg_cval;
   u_12seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_12reg_cval <= WDATA_r;
      END IF;
   END PROCESS u_12seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_13' of 'adff'
   AWADDR_r2 <= mw_U_13reg_cval;
   u_13seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_13reg_cval <= AWADDR_r;
      END IF;
   END PROCESS u_13seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_14' of 'adff'
   AWLEN_r2 <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_14reg_cval <= AWLEN_r;
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_15' of 'adff'
   AWVALID_r2 <= mw_U_15reg_cval;
   u_15seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_15reg_cval <= AWVALID_r;
      END IF;
   END PROCESS u_15seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_16' of 'adff'
   WLAST_r2 <= mw_U_16reg_cval;
   u_16seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_16reg_cval <= WLAST_r;
      END IF;
   END PROCESS u_16seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_17' of 'adff'
   WDATA_r3 <= mw_U_17reg_cval;
   u_17seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_17reg_cval <= WDATA_r2;
      END IF;
   END PROCESS u_17seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_18' of 'adff'
   ARADDR_r <= mw_U_18reg_cval;
   u_18seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_18reg_cval <= ARADDR;
      END IF;
   END PROCESS u_18seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_19' of 'adff'
   ARLEN_r <= mw_U_19reg_cval;
   u_19seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_19reg_cval <= ARLEN;
      END IF;
   END PROCESS u_19seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_20' of 'adff'
   ARVALID_r <= mw_U_20reg_cval;
   u_20seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_20reg_cval <= ARVALID;
      END IF;
   END PROCESS u_20seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_21' of 'adff'
   RREADY_r <= mw_U_21reg_cval;
   u_21seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_21reg_cval <= RREADY;
      END IF;
   END PROCESS u_21seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'adff'
   ARADDR_r2 <= mw_U_22reg_cval;
   u_22seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_22reg_cval <= ARADDR_r;
      END IF;
   END PROCESS u_22seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_23' of 'adff'
   RREADY_r2 <= mw_U_23reg_cval;
   u_23seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_23reg_cval <= RREADY_r;
      END IF;
   END PROCESS u_23seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_24' of 'adff'
   ARLEN_r2 <= mw_U_24reg_cval;
   u_24seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_24reg_cval <= ARLEN_r;
      END IF;
   END PROCESS u_24seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_25' of 'adff'
   REGA_CAP_ENABLE <= mw_U_25reg_cval;
   u_25seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_25reg_cval <= REGA_CAP_ENABLE_b;
      END IF;
   END PROCESS u_25seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_26' of 'adff'
   ARVALID_r2 <= mw_U_26reg_cval;
   u_26seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_26reg_cval <= ARVALID_r;
      END IF;
   END PROCESS u_26seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_27' of 'adff'
   REGB_CAP_ENABLE <= mw_U_27reg_cval;
   u_27seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_27reg_cval <= REGB_CAP_ENABLE_b;
      END IF;
   END PROCESS u_27seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_30' of 'or'
   REG_CX_p <= Dout OR Dout1;

   -- ModuleWare code(v1.9) for instance 'U_2' of 'vdd'
   WREADY <= '1';

   -- ModuleWare code(v1.9) for instance 'U_3' of 'vdd'
   AWREADY <= '1';

   -- ModuleWare code(v1.9) for instance 'U_4' of 'vdd'
   ARREADY <= '1';

   -- ModuleWare code(v1.9) for instance 'U_1' of 'wordfill'
   wea(0) <= RAM_WrEn;

   -- Instance port mappings.
   U_28 : CAP_POS
      PORT MAP (
         Clk  => Clk,
         Din  => REGA_KC_Err,
         Dout => Dout
      );
   U_29 : CAP_POS
      PORT MAP (
         Clk  => Clk,
         Din  => REGB_KC_Err,
         Dout => Dout1
      );
   U_0 : PARAM_RAM_C250116
      PORT MAP (
         clka  => Clk,
         ena   => RAM_WrEn,
         wea   => wea,
         addra => RAM_WrAddr,
         dina  => WDATA_r3,
         clkb  => Clk,
         enb   => RAM_RdEn,
         addrb => RAM_RdAddr,
         doutb => RAM_Dout
      );

END struct;
