-- VHDL Entity JWXJ.TIME_TICK_SEL.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 17:24:50 2025/12/ 5
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY TIME_TICK_SEL IS
   PORT( 
      Clk        : IN     std_logic;
      Reset      : IN     std_logic;
      TICK_Start : IN     std_logic;
      TIME_Start : IN     std_logic;
      TICK_OUT   : OUT    std_logic
   );

-- Declarations

END TIME_TICK_SEL ;

--
-- VHDL Architecture JWXJ.TIME_TICK_SEL.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 17:24:50 2025/12/ 5
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--d
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF TIME_TICK_SEL IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_TICK_W,
      ST_TICK,
      ST_TIME
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(28 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(28 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_TICK_W : std_logic;


   -- Internal signal declarations
   SIGNAL TIME_Start_r : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_25' of 'adff'
   SIGNAL mw_U_25reg_cval : std_logic;


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      State_c,
      TICK_Start,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_TICK_W <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            State_n <= ST_TICK_W;
            csm1_to_ST_TICK_W <= '1';
         WHEN ST_TICK_W => 
            IF (TICK_Start='1') THEN 
               State_n <= ST_TICK;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_TIME;
            ELSE
               State_n <= ST_TICK_W;
            END IF;
         WHEN ST_TICK => 
            State_n <= ST_TICK_W;
            csm1_to_ST_TICK_W <= '1';
         WHEN ST_TIME => 
            IF (TICK_Start='1') THEN 
               State_n <= ST_TICK_W;
               csm1_to_ST_TICK_W <= '1';
            ELSE
               State_n <= ST_TIME;
            END IF;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_TICK_W
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_TICK_W = '1') THEN
         csm1_next_timer <= "11101110011010110010011111111"; -- no cycles(500000000)-1=499999999
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		TICK_OUT <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_TICK_W) or (State_c = ST_TICK) then
   				TICK_OUT <= TICK_Start;
   		elsif(State_c = ST_TIME) then
   				TICK_OUT <= TIME_Start_r;
   		end if;
   	end if;
   end process;
   
   
   


   -- ModuleWare code(v1.9) for instance 'U_25' of 'adff'
   TIME_Start_r <= mw_U_25reg_cval;
   u_25seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_25reg_cval <= TIME_Start;
      END IF;
   END PROCESS u_25seq_proc;

   -- Instance port mappings.

END struct;
