
#################################################################
# MAIN CLK
#################################################################
set_property PACKAGE_PIN AB27 [get_ports FPGA_CLK80M_Z]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_CLK80M_Z]

set_property PACKAGE_PIN R8 [get_ports Q0_CLK0_GTREFCLK_PAD_P_IN]
set_property PACKAGE_PIN R7 [get_ports Q0_CLK0_GTREFCLK_PAD_N_IN]

set_property LOC GTXE2_CHANNEL_X0Y0 [get_cells mGTX_DRV/GTX_support_i/inst/GTX_init_i/GTX_i/gt0_GTX_i/gtxe2_i]
set_property LOC GTXE2_CHANNEL_X0Y1 [get_cells mGTX_DRV/GTX_support_i/inst/GTX_init_i/GTX_i/gt1_GTX_i/gtxe2_i]


#################################################################
# GTX TIMING
#################################################################
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/CLR}]
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/D}]

#################################################################
# VGAP
#################################################################
set_property PACKAGE_PIN Y26 [get_ports VGAP]
set_property IOSTANDARD LVCMOS33 [get_ports VGAP]

#####################SUPPLY_EN#####################
set_property PACKAGE_PIN C26 [get_ports SUP_EN9]
set_property PACKAGE_PIN C25 [get_ports SUP_EN10]
set_property PACKAGE_PIN B25 [get_ports SUP_EN11]
set_property PACKAGE_PIN D27 [get_ports SUP_EN12]
set_property PACKAGE_PIN C27 [get_ports SUP_EN13]
set_property PACKAGE_PIN E28 [get_ports SUP_EN14]
set_property PACKAGE_PIN D28 [get_ports SUP_EN15]
set_property PACKAGE_PIN C29 [get_ports SUP_EN16]
set_property PACKAGE_PIN G24 [get_ports SUP_EN1]
set_property PACKAGE_PIN B27 [get_ports SUP_EN2]
set_property PACKAGE_PIN A27 [get_ports SUP_EN3]
set_property PACKAGE_PIN C24 [get_ports SUP_EN4]
set_property PACKAGE_PIN B24 [get_ports SUP_EN5]
set_property PACKAGE_PIN A25 [get_ports SUP_EN6]
set_property PACKAGE_PIN A26 [get_ports SUP_EN7]
set_property PACKAGE_PIN D26 [get_ports SUP_EN8]


set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN1]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN2]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN3]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN4]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN5]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN6]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN7]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN8]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN9]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN10]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN11]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN12]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN13]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN14]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN15]
set_property IOSTANDARD LVCMOS33 [get_ports SUP_EN16]
#####################CMOS1#####################
## CLOCK
set_property PACKAGE_PIN AH26 [get_ports CMB_CLK_PIX]
##set_property PACKAGE_PIN Y20  [get_ports {CMB_CLK_REF}]
set_property PACKAGE_PIN G22 [get_ports CMB_CLKIN_P]
set_property PACKAGE_PIN F22 [get_ports CMB_CLKIN_N]
## SPI
set_property PACKAGE_PIN AH30 [get_ports CMB_SEN_RST_N]
set_property PACKAGE_PIN AK26 [get_ports CMB_SPI_OUT]
set_property PACKAGE_PIN Y29 [get_ports CMB_SPI_CLK]
set_property PACKAGE_PIN W29 [get_ports CMB_SPI_IN]
set_property PACKAGE_PIN AA25 [get_ports CMB_SPI_WRITE]
set_property PACKAGE_PIN AC30 [get_ports CMB_SPI_READ]
## DRIVE
set_property PACKAGE_PIN AF25 [get_ports {CMB_ROW[0]}]
set_property PACKAGE_PIN AC29 [get_ports {CMB_ROW[1]}]
set_property PACKAGE_PIN AH25 [get_ports {CMB_ROW[2]}]
set_property PACKAGE_PIN AC26 [get_ports {CMB_ROW[3]}]
set_property PACKAGE_PIN AH21 [get_ports {CMB_ROW[4]}]
set_property PACKAGE_PIN AE25 [get_ports {CMB_ROW[5]}]
set_property PACKAGE_PIN AH22 [get_ports {CMB_ROW[6]}]
set_property PACKAGE_PIN AK23 [get_ports {CMB_ROW[7]}]
set_property PACKAGE_PIN AG22 [get_ports {CMB_ROW[8]}]
set_property PACKAGE_PIN AK24 [get_ports {CMB_ROW[9]}]
set_property PACKAGE_PIN AG25 [get_ports {CMB_ROW[10]}]
set_property PACKAGE_PIN AA30 [get_ports {CMB_ROW[11]}]
set_property PACKAGE_PIN AF27 [get_ports CMB_TX]
set_property PACKAGE_PIN AF20 [get_ports CMB_RS]
set_property PACKAGE_PIN AA26 [get_ports CMB_RST]
set_property PACKAGE_PIN AG20 [get_ports CMB_HDR]
set_property PACKAGE_PIN AJ21 [get_ports CMB_TAZ]
set_property PACKAGE_PIN AJ26 [get_ports CMB_TAB]
set_property PACKAGE_PIN AF26 [get_ports CMB_TPC]
set_property PACKAGE_PIN AJ27 [get_ports CMB_TINITO]
set_property PACKAGE_PIN AH27 [get_ports CMB_TINITE]
set_property PACKAGE_PIN AB29 [get_ports CMB_TSO]
set_property PACKAGE_PIN W27 [get_ports CMB_TSE]
set_property PACKAGE_PIN W28 [get_ports CMB_TAC]
set_property PACKAGE_PIN Y25 [get_ports CMB_TRD]
set_property PACKAGE_PIN AB28 [get_ports CMB_TADR]
set_property PACKAGE_PIN AK28 [get_ports CMB_TADS]
set_property PACKAGE_PIN AG30 [get_ports CMB_TWS]
set_property PACKAGE_PIN Y30 [get_ports CMB_SYNC]
set_property PACKAGE_PIN AA27 [get_ports CMB_TBS]
set_property PACKAGE_PIN AH20 [get_ports CMB_TS]
set_property PACKAGE_PIN AE20 [get_ports CMB_TRAIN]
## TRAINING
set_property PACKAGE_PIN C20 [get_ports {CMB_DATA_SER_P[0]}]
set_property PACKAGE_PIN B20 [get_ports {CMB_DATA_SER_N[0]}]
set_property PACKAGE_PIN D21 [get_ports {CMB_DATA_SER_P[1]}]
set_property PACKAGE_PIN C21 [get_ports {CMB_DATA_SER_N[1]}]
set_property PACKAGE_PIN D22 [get_ports {CMB_DATA_SER_P[2]}]
set_property PACKAGE_PIN C22 [get_ports {CMB_DATA_SER_N[2]}]
set_property PACKAGE_PIN A20 [get_ports {CMB_DATA_SER_P[3]}]
set_property PACKAGE_PIN A21 [get_ports {CMB_DATA_SER_N[3]}]
set_property PACKAGE_PIN C19 [get_ports {CMB_DATA_SER_P[4]}]
set_property PACKAGE_PIN B19 [get_ports {CMB_DATA_SER_N[4]}]
set_property PACKAGE_PIN B18 [get_ports {CMB_DATA_SER_P[5]}]
set_property PACKAGE_PIN A18 [get_ports {CMB_DATA_SER_N[5]}]
set_property PACKAGE_PIN C17 [get_ports {CMB_DATA_SER_P[6]}]
set_property PACKAGE_PIN B17 [get_ports {CMB_DATA_SER_N[6]}]
set_property PACKAGE_PIN A16 [get_ports {CMB_DATA_SER_P[7]}]
set_property PACKAGE_PIN A17 [get_ports {CMB_DATA_SER_N[7]}]


## CLOCK
set_property IOSTANDARD LVCMOS33 [get_ports CMB_CLK_PIX]
##set_property IOSTANDARD LVCMOS33 [get_ports {CMB_CLK_REF}]
set_property IOSTANDARD LVDS_25 [get_ports CMB_CLKIN_P]
set_property IOSTANDARD LVDS_25 [get_ports CMB_CLKIN_N]
set_property DIFF_TERM TRUE [get_ports CMB_CLKIN_P]
set_property DIFF_TERM TRUE [get_ports CMB_CLKIN_N]
## SPI
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SEN_RST_N]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SPI_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SPI_READ]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SPI_WRITE]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SPI_IN]
## DRIVE
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMB_ROW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TX]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_RS]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_RST]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_HDR]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TAZ]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TAB]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TPC]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TINITO]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TINITE]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TSO]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TSE]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TAC]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TRD]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TADR]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TADS]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TWS]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TBS]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TS]
set_property IOSTANDARD LVCMOS33 [get_ports CMB_TRAIN]
## TRAINING
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMB_DATA_SER_N[7]}]


#####################CMOS2#####################
## CLOCK
set_property PACKAGE_PIN H12 [get_ports CMA_CLK_PIX]
##set_property PACKAGE_PIN J11  [get_ports {CMA_CLK_REF}]
set_property PACKAGE_PIN D16 [get_ports CMA_CLKIN_P]
set_property PACKAGE_PIN C16 [get_ports CMA_CLKIN_N]
## SPI
set_property PACKAGE_PIN H11 [get_ports CMA_SEN_RST_N]
set_property PACKAGE_PIN C12 [get_ports CMA_SPI_CLK]
set_property PACKAGE_PIN G15 [get_ports CMA_SPI_OUT]
set_property PACKAGE_PIN AF22 [get_ports CMA_SPI_READ]
set_property PACKAGE_PIN D12 [get_ports CMA_SPI_WRITE]
set_property PACKAGE_PIN A11 [get_ports CMA_SPI_IN]
## DRIVE
set_property PACKAGE_PIN C14 [get_ports {CMA_ROW[0]}]
set_property PACKAGE_PIN AG28 [get_ports {CMA_ROW[1]}]
set_property PACKAGE_PIN AD28 [get_ports {CMA_ROW[2]}]
set_property PACKAGE_PIN AG27 [get_ports {CMA_ROW[3]}]
set_property PACKAGE_PIN B14 [get_ports {CMA_ROW[4]}]
set_property PACKAGE_PIN B15 [get_ports {CMA_ROW[5]}]
set_property PACKAGE_PIN A13 [get_ports {CMA_ROW[6]}]
set_property PACKAGE_PIN D13 [get_ports {CMA_ROW[7]}]
set_property PACKAGE_PIN A12 [get_ports {CMA_ROW[8]}]
set_property PACKAGE_PIN B13 [get_ports {CMA_ROW[9]}]
set_property PACKAGE_PIN B12 [get_ports {CMA_ROW[10]}]
set_property PACKAGE_PIN AH24 [get_ports {CMA_ROW[11]}]
set_property PACKAGE_PIN C15 [get_ports CMA_TX]
set_property PACKAGE_PIN AD29 [get_ports CMA_RS]
set_property PACKAGE_PIN T28 [get_ports CMA_RST]
set_property PACKAGE_PIN U28 [get_ports CMA_HDR]
set_property PACKAGE_PIN E13 [get_ports CMA_TAZ]
set_property PACKAGE_PIN E14 [get_ports CMA_TAB]
set_property PACKAGE_PIN D14 [get_ports CMA_TPC]
set_property PACKAGE_PIN E15 [get_ports CMA_TINITO]
set_property PACKAGE_PIN G30 [get_ports CMA_TINITE]
set_property PACKAGE_PIN AD27 [get_ports CMA_TSO]
set_property PACKAGE_PIN AF21 [get_ports CMA_TSE]
set_property PACKAGE_PIN H15 [get_ports CMA_TAC]
set_property PACKAGE_PIN AG23 [get_ports CMA_TRD]
set_property PACKAGE_PIN AG24 [get_ports CMA_TADR]
set_property PACKAGE_PIN G12 [get_ports CMA_TADS]
set_property PACKAGE_PIN J12 [get_ports CMA_TWS]
set_property PACKAGE_PIN J13 [get_ports CMA_SYNC]
set_property PACKAGE_PIN AD26 [get_ports CMA_TBS]
set_property PACKAGE_PIN C11 [get_ports CMA_TS]
set_property PACKAGE_PIN K13 [get_ports CMA_TRAIN]
## TRAINING
set_property PACKAGE_PIN J17 [get_ports {CMA_DATA_SER_P[0]}]
set_property PACKAGE_PIN H17 [get_ports {CMA_DATA_SER_N[0]}]
set_property PACKAGE_PIN G17 [get_ports {CMA_DATA_SER_P[1]}]
set_property PACKAGE_PIN F17 [get_ports {CMA_DATA_SER_N[1]}]
set_property PACKAGE_PIN G18 [get_ports {CMA_DATA_SER_P[2]}]
set_property PACKAGE_PIN F18 [get_ports {CMA_DATA_SER_N[2]}]
set_property PACKAGE_PIN K18 [get_ports {CMA_DATA_SER_P[3]}]
set_property PACKAGE_PIN J18 [get_ports {CMA_DATA_SER_N[3]}]
set_property PACKAGE_PIN K19 [get_ports {CMA_DATA_SER_P[4]}]
set_property PACKAGE_PIN K20 [get_ports {CMA_DATA_SER_N[4]}]
set_property PACKAGE_PIN J19 [get_ports {CMA_DATA_SER_P[5]}]
set_property PACKAGE_PIN H19 [get_ports {CMA_DATA_SER_N[5]}]
set_property PACKAGE_PIN H20 [get_ports {CMA_DATA_SER_P[6]}]
set_property PACKAGE_PIN G20 [get_ports {CMA_DATA_SER_N[6]}]
set_property PACKAGE_PIN H21 [get_ports {CMA_DATA_SER_P[7]}]
set_property PACKAGE_PIN H22 [get_ports {CMA_DATA_SER_N[7]}]

#####################CMOS2#####################
## CLOCK
set_property IOSTANDARD LVCMOS33 [get_ports CMA_CLK_PIX]
##set_property IOSTANDARD LVCMOS33 [get_ports {CMA_CLK_REF}]
set_property IOSTANDARD LVDS_25 [get_ports CMA_CLKIN_P]
set_property IOSTANDARD LVDS_25 [get_ports CMA_CLKIN_N]
set_property DIFF_TERM TRUE [get_ports CMA_CLKIN_P]
set_property DIFF_TERM TRUE [get_ports CMA_CLKIN_N]
## SPI
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SEN_RST_N]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SPI_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SPI_READ]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SPI_WRITE]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SPI_IN]
## DRIVE
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CMA_ROW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TX]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_RS]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_RST]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_HDR]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TAZ]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TAB]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TPC]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TINITO]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TINITE]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TSO]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TSE]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TAC]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TRD]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TADR]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TADS]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TWS]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TBS]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TS]
set_property IOSTANDARD LVCMOS33 [get_ports CMA_TRAIN]
## TRAINING
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {CMA_DATA_SER_N[7]}]


set_property PACKAGE_PIN R29 [get_ports Z_TX_PAD_O]
set_property IOSTANDARD LVCMOS33 [get_ports Z_TX_PAD_O]

set_property PACKAGE_PIN P27 [get_ports B_TX_PAD_O]
set_property IOSTANDARD LVCMOS33 [get_ports B_TX_PAD_O]


set_property PACKAGE_PIN P28 [get_ports Z_RX_PAD_I]
set_property IOSTANDARD LVCMOS33 [get_ports Z_RX_PAD_I]

set_property PACKAGE_PIN P26 [get_ports B_RX_PAD_I]
set_property IOSTANDARD LVCMOS33 [get_ports B_RX_PAD_I]


set_property PACKAGE_PIN R26 [get_ports TICK_START]
set_property IOSTANDARD LVCMOS33 [get_ports TICK_START]

set_property PACKAGE_PIN V25 [get_ports CF1]
set_property IOSTANDARD LVCMOS33 [get_ports CF1]

set_property PACKAGE_PIN P29 [get_ports CF2]
set_property IOSTANDARD LVCMOS33 [get_ports CF2]

set_property PACKAGE_PIN W24 [get_ports TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports TX_EN]

set_false_path -from [get_pins U_11/Rst_100M_Int_reg/C] -to [get_pins {U_0/U_7/SYNCFIFO_Din_reg[*]/CLR}]
set_false_path -from [get_pins U_11/Rst_100M_Int_reg/C] -to [get_pins U_0/U_7/SYNCFIFO_WrEn_reg/D]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_MODE S_SELECTMAP [current_design]
set_property BITSTREAM.CONFIG.PERSIST YES [current_design]