-- VHDL Entity JWXJ.TX_RAM_GROUP_C250114.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 10:53:50 2025/05/ 9
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY TX_RAM_GROUP_C250114 IS
   PORT( 
      AWADDR    : IN     std_logic_vector (7 DOWNTO 0);
      AWLEN     : IN     std_logic_vector (7 DOWNTO 0);
      AWVALID   : IN     std_logic;
      Clk       : IN     std_logic;
      Eng_Start : IN     std_logic;
      Reset     : IN     std_logic;
      Rsp_Start : IN     std_logic;
      Rsp_State : IN     std_logic_vector (1 DOWNTO 0);
      WDATA     : IN     std_logic_vector (7 DOWNTO 0);
      WLAST     : IN     std_logic;
      WVALID    : IN     std_logic;
      AWREADY   : OUT    std_logic;
      Eng_Ack   : OUT    std_logic;
      Rsp_Ack   : OUT    std_logic;
      TDATA     : OUT    std_logic_vector (7 DOWNTO 0);
      TLAST     : OUT    std_logic;
      TUSER     : OUT    std_logic_vector (7 DOWNTO 0);
      TVALID    : OUT    std_logic;
      WREADY    : OUT    std_logic
   );

-- Declarations

END TX_RAM_GROUP_C250114 ;

--
-- VHDL Architecture JWXJ.TX_RAM_GROUP_C250114.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 10:53:51 2025/05/ 9
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY JWXJ;

ARCHITECTURE struct OF TX_RAM_GROUP_C250114 IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_RSP_USER,
      ST_RSP_DATA,
      ST_ENG_USER,
      ST_RSP_ACK,
      ST_ENG_ACK,
      ST_ENG_DATA
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(18 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(18 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_ENG_DATA : std_logic;


   -- Internal signal declarations
   SIGNAL Add_RAM_Cnt   : std_logic;
   SIGNAL End_RAM_Cnt   : std_logic;
   SIGNAL End_WrRAM_Cnt : std_logic;
   SIGNAL Output_En     : std_logic;
   SIGNAL Output_En_r   : std_logic;
   SIGNAL RAM_Cnt       : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_Din       : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_Dout      : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_RdAddr    : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_RdEn      : std_logic;
   SIGNAL RAM_WrAddr    : std_logic_vector(7 DOWNTO 0);
   SIGNAL RAM_WrEn      : std_logic;
   SIGNAL RAM_WrEn_Bus  : std_logic_vector(0 DOWNTO 0);
   SIGNAL TLAST_b       : std_logic;
   SIGNAL TLAST_b2      : std_logic;
   SIGNAL WrAddr_Start  : std_logic_vector(7 DOWNTO 0);
   SIGNAL WrLength      : std_logic_vector(7 DOWNTO 0);
   SIGNAL WrRAM_Cnt     : std_logic_vector(7 DOWNTO 0);


attribute fsm_safe_state : string;
attribute fsm_safe_state of State_c : signal is "default_state";

   -- Component Declarations
   COMPONENT ENG_RAM
   PORT (
      addra : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      addrb : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      clka  : IN     STD_LOGIC;
      clkb  : IN     STD_LOGIC;
      dina  : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      ena   : IN     STD_LOGIC;
      enb   : IN     STD_LOGIC;
      wea   : IN     STD_LOGIC_VECTOR ( 0 TO 0 );
      doutb : OUT    STD_LOGIC_VECTOR ( 7 DOWNTO 0 )
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   --FOR ALL : ENG_RAM USE ENTITY JWXJ.ENG_RAM;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Block 1 eb1
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      End_RAM_Cnt,
      Eng_Start,
      Rsp_Start,
      State_c,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_ENG_DATA <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF (Eng_Start='1') THEN 
               State_n <= ST_ENG_ACK;
            ELSIF (Rsp_Start = '1') THEN 
               State_n <= ST_RSP_ACK;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_RSP_USER => 
            State_n <= ST_RSP_DATA;
         WHEN ST_RSP_DATA => 
            State_n <= ST_IDLE;
         WHEN ST_ENG_USER => 
            State_n <= ST_ENG_DATA;
            csm1_to_ST_ENG_DATA <= '1';
         WHEN ST_RSP_ACK => 
            State_n <= ST_RSP_USER;
         WHEN ST_ENG_ACK => 
            State_n <= ST_ENG_USER;
         WHEN ST_ENG_DATA => 
            IF (End_RAM_Cnt='1') THEN 
               State_n <= ST_IDLE;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_ENG_DATA;
            END IF;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_ENG_DATA
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_ENG_DATA = '1') THEN
         csm1_next_timer <= "1001001001111011111"; -- no cycles(300000)-1=299999
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;



   -- HDL Embedded Text Block 2 eb2
   
   
   
   ------------------------------------------------------------
   -- 计数器
   ------------------------------------------------------------
      
      process(Clk, Reset) begin
         if(Reset = '1') then
            RAM_Cnt <= (others => '0');
         elsif rising_edge(Clk) then
   		if(Add_RAM_Cnt = '1') then
   		   if(End_RAM_Cnt = '1') then
   			  RAM_Cnt <= (others => '0');
   		   else
   			  RAM_Cnt <= RAM_Cnt + X"01";
   		   end if;
   		end if;
         end if;
      end process;
      
      Add_RAM_Cnt <= '1' when (State_c = ST_ENG_DATA) else '0';
      End_RAM_Cnt <= '1' when (Add_RAM_Cnt = '1') and (RAM_Cnt = conv_std_logic_vector(60,8)) else '0';
      
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			RAM_RdEn <= '0';
   			RAM_RdAddr <= X"FF";
   	   elsif rising_edge(Clk) then
   			if(State_c = ST_ENG_DATA) then
   				RAM_RdEn <= '1';
   				RAM_RdAddr <= RAM_RdAddr + X"01";
   			else
   				RAM_RdEn <= '0';
   				RAM_RdAddr <= X"FF";
   			end if;
   	   end if;
      end process;
      
      process(Clk) begin
   	   if rising_edge(Clk) then
   			if(State_c = ST_ENG_DATA) then
   				Output_En <= '1';
   			else
   				Output_En <= '0';
   			end if;
   	   end if;
      end process;
      
      process(Clk) begin
   	   if rising_edge(Clk) then
   			Output_En_r <= Output_En;
   	   end if;
      end process;
      
   
   	process(Reset, Clk) begin
   		if(Reset = '1') then
   			TLAST_b <= '0';
   		elsif rising_edge(Clk) then
   			if(End_RAM_Cnt = '1') then
   				TLAST_b <= '1';
   			else
   				TLAST_b <= '0';
   			end if;
   		end if;
   	end process;
   	
   	process(Clk) begin
   		if rising_edge(Clk) then
   			TLAST_b2 <= TLAST_b;
   			
   		end if;
   	end process;
   	
   	process(Reset, Clk) begin
   		if(Reset = '1') then
   	
   		elsif rising_edge(Clk) then
   			if(State_c = ST_RSP_DATA) then
   				TLAST    <= '1';
   			else
   				TLAST    <= TLAST_b2;
   			end if;
   		end if;
   	end process;
   	
   	
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   			TDATA <= (others => '0');
   			TVALID <= '0';
   	   elsif rising_edge(Clk) then
   			if(Output_En_r = '1') then
   				TDATA <= RAM_Dout;
   				TVALID <= '1';
   			elsif(State_c = ST_RSP_DATA) then
   				TDATA <= X"00";
   				TVALID <= '1';
   			else
   				TDATA <= (others => '0');
   				TVALID <= '0';
   			end if;
   	   end if;
      end process;
      
      process(Reset, Clk) begin
   	   if(Reset = '1') then
   		  TUSER <= X"FF";
   	   elsif rising_edge(Clk) then
   		  if(State_c = ST_RSP_USER) then
   			  if(Rsp_State = "01") then
   					TUSER <= X"01";
   			  elsif(Rsp_State = "10") then
   					TUSER <= X"10";
   			  else
   					TUSER <= X"11";
   			  end if;
   		  elsif(State_c = ST_ENG_USER) then
   			  TUSER <= X"00";
   		  end if;
   	   end if;
      end process;
      
      process(Clk) begin
   	   if rising_edge(Clk) then
   			if(State_c = ST_RSP_ACK) then
   				Rsp_Ack <= '1';
   			else
   				Rsp_Ack <= '0';
   			end if;
   	   end if;
      end process;
      
      process(Clk) begin
   	   if rising_edge(Clk) then
   		   if(State_c = ST_ENG_ACK) then
   				Eng_Ack <= '1';
   		   else
   				Eng_Ack <= '0';
   		   end if;
   	   end if;
      end process;
      
      
      
      
      
      
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   

   -- HDL Embedded Text Block 3 eb3
   -- eb3 3
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		WrAddr_Start <= (others => '0');
   		WrLength     <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(AWVALID = '1') then
   			WrAddr_Start <= AWADDR;
   			WrLength <= AWLEN;
   		end if;
   	end if;
   end process;
   
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		WrRAM_Cnt <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(AWVALID = '1') then
   			WrRAM_Cnt <= (others => '0');
   		elsif(WVALID = '1') then
   			if(WLAST = '1') or (End_WrRAM_Cnt = '1') then
   				WrRAM_Cnt <= (others => '0');
   			else
   				WrRAM_Cnt <= WrRAM_Cnt + X"01";
   			end if;
   		end if;
   	end if;
   end process;
   
   End_WrRAM_Cnt <= '1' when (WVALID = '1') and (WrRAM_Cnt = WrLength) else '0';
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RAM_WrAddr <= (others => '0');
   		RAM_Din <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(WVALID = '1') then 
   			RAM_WrAddr <= WrAddr_Start + WrRAM_Cnt;
   			RAM_Din    <= WDATA;
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if rising_edge(Clk) then
   		if(WVALID = '1') then 
   			RAM_WrEn <= '1';
   		else
   			RAM_WrEn <= '0';
   		end if;
   	end if;
   end process;
   
   AWREADY <= '1';
   WREADY  <= '1';
   
   
   
   
                                           
   
   
   
   


   -- ModuleWare code(v1.9) for instance 'U_0' of 'wordfill'
   RAM_WrEn_Bus(0) <= RAM_WrEn;

   -- Instance port mappings.
   U_1 : ENG_RAM
      PORT MAP (
         clka  => Clk,
         ena   => RAM_WrEn,
         wea   => RAM_WrEn_Bus,
         addra => RAM_WrAddr,
         dina  => RAM_Din,
         clkb  => Clk,
         enb   => RAM_RdEn,
         addrb => RAM_RdAddr,
         doutb => RAM_Dout
      );

END struct;
