-- VHDL Entity JWXJ.Window.symbol
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 07:57:22 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Window IS
   PORT( 
      Clk      : IN     std_logic;
      FOP      : IN     std_logic;
      GReset   : IN     std_logic;
      S_TDATA  : IN     std_logic_vector (15 DOWNTO 0);
      S_TLAST  : IN     std_logic;
      S_TUSER  : IN     std_logic;
      S_TVALID : IN     std_logic;
      X        : IN     std_logic_vector (11 DOWNTO 0);
      Y        : IN     std_logic_vector (11 DOWNTO 0);
      M_TDATA  : OUT    std_logic_vector (15 DOWNTO 0);
      M_TLAST  : OUT    std_logic;
      M_TUSER  : OUT    std_logic_vector (1 DOWNTO 0);
      M_TVALID : OUT    std_logic
   );

-- Declarations

END Window ;

--
-- VHDL Architecture JWXJ.Window.struct
--
-- Created:
--          by - zb5700.UNKNOWN (LAPTOP-IBGQUTEL)
--          at - 07:57:22 2025/05/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;


ARCHITECTURE struct OF Window IS

   -- Architecture declarations
   -- Non hierarchical state machine declarations
   TYPE CSM1_STATE_TYPE IS (
      ST_IDLE,
      ST_SOP,
      ST_DATA,
      ST_EOP,
      ST_NEWROW,
      ST_ROWGAP,
      ST_WAIT,
      ST_BSOP,
      ST_BDATA,
      ST_BEOP
   );
 
   -- Declare current and next state signals
   SIGNAL State_c : CSM1_STATE_TYPE;
   SIGNAL State_n : CSM1_STATE_TYPE;
   -- Declare Wait State internal signals
   SIGNAL csm1_timer : std_logic_vector(16 DOWNTO 0);
   SIGNAL csm1_next_timer : std_logic_vector(16 DOWNTO 0);
   SIGNAL csm1_timeout : std_logic;
   SIGNAL csm1_to_ST_DATA : std_logic;
   SIGNAL csm1_to_ST_ROWGAP : std_logic;
   SIGNAL csm1_to_ST_WAIT : std_logic;
   SIGNAL csm1_to_ST_BDATA : std_logic;


   -- Internal signal declarations
   SIGNAL Add_EopCnt  : std_logic;
   SIGNAL ColCnt      : std_logic_vector(11 DOWNTO 0);
   SIGNAL DATA        : std_logic_vector(15 DOWNTO 0);
   SIGNAL EOP         : std_logic;
   SIGNAL End_EopCnt  : std_logic;
   SIGNAL EopCnt      : std_logic_vector(11 DOWNTO 0);
   SIGNAL M_DATA      : std_logic_vector(15 DOWNTO 0);
   SIGNAL M_EOP       : std_logic;
   SIGNAL M_FOP       : std_logic;
   SIGNAL M_SOP       : std_logic;
   SIGNAL M_SOP_r     : std_logic;
   SIGNAL M_VALID     : std_logic;
   SIGNAL REG_FIRST   : std_logic;
   SIGNAL REG_X       : std_logic_vector(11 DOWNTO 0);
   SIGNAL REG_Y       : std_logic_vector(11 DOWNTO 0);
   SIGNAL Reset       : std_logic;
   SIGNAL RowCnt      : std_logic_vector(11 DOWNTO 0);
   SIGNAL SOP         : std_logic;
   SIGNAL S_TDATA_r   : std_logic_vector(15 DOWNTO 0);
   SIGNAL S_TDATA_r2  : std_logic_vector(15 DOWNTO 0);
   SIGNAL S_TDATA_r3  : std_logic_vector(15 DOWNTO 0);
   SIGNAL S_TLAST_r   : std_logic;
   SIGNAL S_TLAST_r2  : std_logic;
   SIGNAL S_TLAST_r3  : std_logic;
   SIGNAL S_TVALID_r  : std_logic;
   SIGNAL S_TVALID_r2 : std_logic;
   SIGNAL S_TVALID_r3 : std_logic;
   SIGNAL VALID       : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_19' of 'adff'
   SIGNAL mw_U_19reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_20' of 'adff'
   SIGNAL mw_U_20reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_21' of 'adff'
   SIGNAL mw_U_21reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_22' of 'adff'
   SIGNAL mw_U_22reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_23' of 'adff'
   SIGNAL mw_U_23reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_24' of 'adff'
   SIGNAL mw_U_24reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_25' of 'adff'
   SIGNAL mw_U_25reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_26' of 'adff'
   SIGNAL mw_U_26reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_27' of 'adff'
   SIGNAL mw_U_27reg_cval : std_logic_vector(11 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_33' of 'adff'
   SIGNAL mw_U_33reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_34' of 'adff'
   SIGNAL mw_U_34reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_35' of 'adff'
   SIGNAL mw_U_35reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_36' of 'adff'
   SIGNAL mw_U_36reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_37' of 'adff'
   SIGNAL mw_U_37reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_38' of 'adff'
   SIGNAL mw_U_38reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_39' of 'adff'
   SIGNAL mw_U_39reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_40' of 'adff'
   SIGNAL mw_U_40reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.9) for instance 'U_41' of 'adff'
   SIGNAL mw_U_41reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.9) for instance 'U_42' of 'adff'
   SIGNAL mw_U_42reg_cval : std_logic;


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		RowCnt <= (others => '1');
   	elsif rising_edge(Clk) then
   		if(SOP = '1') then
   			RowCnt <= RowCnt + X"001";
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		ColCnt <= (others => '1');
   	elsif rising_edge(Clk) then
   		if(SOP = '1') then
   			ColCnt <= (others => '0');
   		elsif(VALID = '1') then
   			ColCnt <= ColCnt + X"001";
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_VALID <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SOP) or (State_c = ST_DATA) or (State_c = ST_EOP) or
   		  (State_c = ST_BSOP) or (State_c = ST_BDATA) or (State_c = ST_BEOP) then
   			M_VALID <= '1';
   		else
   			M_VALID <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_DATA <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SOP) or (State_c = ST_DATA) or (State_c = ST_EOP) then
   			M_DATA <= DATA;
   		else
   			M_DATA <= (others => '0');
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_SOP <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_SOP) or (State_c = ST_BSOP) then
   			M_SOP <= '1';
   		else
   			M_SOP <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		REG_FIRST <= '1';
   	elsif rising_edge(Clk) then
   		if(M_SOP = '1') then
   			REG_FIRST <= '0';
   		end if;
   	end if;
   end process;
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_FOP <= '0';
   	elsif rising_edge(Clk) then
   		if(M_SOP = '1') and (REG_FIRST='1') then
   			M_FOP <= '1';
   		else
   			M_FOP <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		M_EOP <= '0';
   	elsif rising_edge(Clk) then
   		if(State_c = ST_EOP) or (State_c = ST_BEOP) then
   			M_EOP <= '1';
   		else
   			M_EOP <= '0';
   		end if;
   	end if;
   end process;
   
   
   process(Reset, Clk) begin
   	if(Reset = '1') then
   		EopCnt <= (others => '0');
   	elsif rising_edge(Clk) then
   		if(Add_EopCnt='1') then
   			if(End_EopCnt='1') then
   				EopCnt <= (others => '0');
   			else
   				EopCnt <= EopCnt + X"001";
   			end if;
   		end if;
   	end if;
   end process;
   
   Add_EopCnt <= '1' when (State_c = ST_EOP) or (State_c = ST_BEOP) else '0';
   End_EopCnt <= '1' when (Add_EopCnt = '1') and (EopCnt = conv_std_logic_vector(519,12)) else '0';
   
   
   
   
   
   
   
   
   

   -- HDL Embedded Block 2 eb2
   -- Non hierarchical state machine
   -----------------------------------------------------------------
   csm1_clocked_proc : PROCESS ( 
      Clk,
      Reset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset = '1') THEN
         State_c <= ST_IDLE;
         csm1_timer <= (OTHERS => '0');
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         State_c <= State_n;
         csm1_timer <= csm1_next_timer;
      END IF;
   END PROCESS csm1_clocked_proc;
 
   -----------------------------------------------------------------
   csm1_nextstate_proc : PROCESS ( 
      ColCnt,
      End_EopCnt,
      REG_X,
      REG_Y,
      RowCnt,
      SOP,
      State_c,
      csm1_timeout
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm1_to_ST_DATA <= '0';
      csm1_to_ST_ROWGAP <= '0';
      csm1_to_ST_WAIT <= '0';
      csm1_to_ST_BDATA <= '0';
      CASE State_c IS
         WHEN ST_IDLE => 
            IF ((RowCnt=REG_Y) and (ColCnt=REG_X)) THEN 
               State_n <= ST_SOP;
            ELSE
               State_n <= ST_IDLE;
            END IF;
         WHEN ST_SOP => 
            State_n <= ST_DATA;
            csm1_to_ST_DATA <= '1';
         WHEN ST_DATA => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_EOP;
            ELSE
               State_n <= ST_DATA;
            END IF;
         WHEN ST_EOP => 
            IF (End_EopCnt='1') THEN 
               State_n <= ST_IDLE;
            ELSIF (RowCnt=X"7FF") THEN 
               State_n <= ST_ROWGAP;
               csm1_to_ST_ROWGAP <= '1';
            ELSE
               State_n <= ST_WAIT;
               csm1_to_ST_WAIT <= '1';
            END IF;
         WHEN ST_NEWROW => 
            IF (ColCnt=REG_X) THEN 
               State_n <= ST_SOP;
            ELSE
               State_n <= ST_NEWROW;
            END IF;
         WHEN ST_ROWGAP => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_BSOP;
            ELSE
               State_n <= ST_ROWGAP;
            END IF;
         WHEN ST_WAIT => 
            IF (SOP='1') THEN 
               State_n <= ST_NEWROW;
            ELSIF (csm1_timeout = '1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_WAIT;
            END IF;
         WHEN ST_BSOP => 
            State_n <= ST_BDATA;
            csm1_to_ST_BDATA <= '1';
         WHEN ST_BDATA => 
            IF (csm1_timeout = '1') THEN 
               State_n <= ST_BEOP;
            ELSE
               State_n <= ST_BDATA;
            END IF;
         WHEN ST_BEOP => 
            IF (End_EopCnt='1') THEN 
               State_n <= ST_IDLE;
            ELSE
               State_n <= ST_ROWGAP;
               csm1_to_ST_ROWGAP <= '1';
            END IF;
         WHEN OTHERS =>
            State_n <= ST_IDLE;
      END CASE;
   END PROCESS csm1_nextstate_proc;
 
   -----------------------------------------------------------------
   csm1_wait_combo_proc: PROCESS (
      csm1_timer,
      csm1_to_ST_DATA,
      csm1_to_ST_ROWGAP,
      csm1_to_ST_WAIT,
      csm1_to_ST_BDATA
   )
   -----------------------------------------------------------------
   VARIABLE csm1_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm1_timer) = 0) THEN
         csm1_temp_timeout := '1';
      ELSE
         csm1_temp_timeout := '0';
      END IF;

      IF (csm1_to_ST_DATA = '1') THEN
         csm1_next_timer <= "00000001010010001"; -- no cycles(658)-1=657
      ELSIF (csm1_to_ST_ROWGAP = '1') THEN
         csm1_next_timer <= "00000000101011101"; -- no cycles(350)-1=349
      ELSIF (csm1_to_ST_WAIT = '1') THEN
         csm1_next_timer <= "11000011010011111"; -- no cycles(100000)-1=99999
      ELSIF (csm1_to_ST_BDATA = '1') THEN
         csm1_next_timer <= "00000001010010001"; -- no cycles(658)-1=657
      ELSE
         IF (csm1_temp_timeout = '1') THEN
            csm1_next_timer <= (OTHERS=>'0');
         ELSE
            csm1_next_timer <= unsigned(csm1_timer) - '1';
         END IF;
      END IF;
      csm1_timeout <= csm1_temp_timeout;
   END PROCESS csm1_wait_combo_proc;




   -- ModuleWare code(v1.9) for instance 'U_19' of 'adff'
   SOP <= mw_U_19reg_cval;
   u_19seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_19reg_cval <= S_TUSER;
      END IF;
   END PROCESS u_19seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_20' of 'adff'
   S_TVALID_r <= mw_U_20reg_cval;
   u_20seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_20reg_cval <= S_TVALID;
      END IF;
   END PROCESS u_20seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_21' of 'adff'
   S_TVALID_r2 <= mw_U_21reg_cval;
   u_21seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_21reg_cval <= S_TVALID_r;
      END IF;
   END PROCESS u_21seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_22' of 'adff'
   S_TDATA_r <= mw_U_22reg_cval;
   u_22seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_22reg_cval <= S_TDATA;
      END IF;
   END PROCESS u_22seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_23' of 'adff'
   S_TDATA_r2 <= mw_U_23reg_cval;
   u_23seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_23reg_cval <= S_TDATA_r;
      END IF;
   END PROCESS u_23seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_24' of 'adff'
   S_TLAST_r <= mw_U_24reg_cval;
   u_24seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_24reg_cval <= S_TLAST;
      END IF;
   END PROCESS u_24seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_25' of 'adff'
   S_TLAST_r2 <= mw_U_25reg_cval;
   u_25seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_25reg_cval <= S_TLAST_r;
      END IF;
   END PROCESS u_25seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_26' of 'adff'
   REG_X <= mw_U_26reg_cval;
   u_26seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_26reg_cval <= X;
      END IF;
   END PROCESS u_26seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_27' of 'adff'
   REG_Y <= mw_U_27reg_cval;
   u_27seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_27reg_cval <= Y;
      END IF;
   END PROCESS u_27seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_33' of 'adff'
   VALID <= mw_U_33reg_cval;
   u_33seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_33reg_cval <= S_TVALID_r3;
      END IF;
   END PROCESS u_33seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_34' of 'adff'
   DATA <= mw_U_34reg_cval;
   u_34seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_34reg_cval <= S_TDATA_r3;
      END IF;
   END PROCESS u_34seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_35' of 'adff'
   EOP <= mw_U_35reg_cval;
   u_35seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_35reg_cval <= S_TLAST_r3;
      END IF;
   END PROCESS u_35seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_36' of 'adff'
   S_TVALID_r3 <= mw_U_36reg_cval;
   u_36seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_36reg_cval <= S_TVALID_r2;
      END IF;
   END PROCESS u_36seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_37' of 'adff'
   S_TDATA_r3 <= mw_U_37reg_cval;
   u_37seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_37reg_cval <= S_TDATA_r2;
      END IF;
   END PROCESS u_37seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_38' of 'adff'
   S_TLAST_r3 <= mw_U_38reg_cval;
   u_38seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_38reg_cval <= S_TLAST_r2;
      END IF;
   END PROCESS u_38seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_39' of 'adff'
   M_SOP_r <= mw_U_39reg_cval;
   u_39seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_39reg_cval <= M_SOP;
      END IF;
   END PROCESS u_39seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_40' of 'adff'
   M_TDATA <= mw_U_40reg_cval;
   u_40seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_40reg_cval <= M_DATA;
      END IF;
   END PROCESS u_40seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_41' of 'adff'
   M_TVALID <= mw_U_41reg_cval;
   u_41seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_41reg_cval <= M_VALID;
      END IF;
   END PROCESS u_41seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_42' of 'adff'
   M_TLAST <= mw_U_42reg_cval;
   u_42seq_proc: PROCESS (Clk)BEGIN
      IF (Clk'EVENT AND Clk='1') THEN
         mw_U_42reg_cval <= M_EOP;
      END IF;
   END PROCESS u_42seq_proc;

   -- ModuleWare code(v1.9) for instance 'U_0' of 'merge'
   M_TUSER <= M_FOP & M_SOP_r;

   -- ModuleWare code(v1.9) for instance 'U_2' of 'or'
   Reset <= GReset OR FOP;

   -- Instance port mappings.

END struct;
